import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../main.dart';

Lang strings = Lang();

class Lang {

  var direction = TextDirection.ltr;
  String locale = "en"; // ISO 639-1

  Map<int, String> langEng = {
    0 : "HANDYMAN",
    1 : "PROVIDER",
    2 : "SUBMIT",
    3 : "Language",
    4 : "Preferred Language",
    5 : "Select Preferred Language",
    6 : "Sign in now",
    7 : "Email",
    8 : "Enter your Email",
    9 : "Password",
    10 : "Enter your Password",
    11 : "CONTINUE",
    12 : "REGISTER",
    13 : "or continue with",
    14 : "Register",
    15 : "in less than a minute",
    16 : "Name",
    17 : "Enter Name",
    18 : "Confirm Password",
    19 : "Verification",
    20 : "Phone number",
    21 : "Enter your Phone number",
    22 : "We'll sent verification code.",
    23 : "We've sent 6 digit verification code.",
    24 : "Enter code",
    25 : "Enter 6 digits code",
    26 : "Chat",
    27 : "Booking",
    28 : "Account",
    29 : "Write your message ...",
    30 : "Any Time",
    31 : "Upcoming",
    32 : "Completed",
    33 : "Canceled",
    34 : "New",
    35 : "Canceled",
    36 : "Completed",
    37 : "Accepted",
    38 : "Call now",
    39 : "Message",
    40 : "Accept",
    41 : "Start a job",
    42 : "Job complete",
    43 : "Waiting for Confirmation from Customer",
    44 : "Booking ID",
    45 : "Request Received",
    46 : "Time",
    47 : "Booking Confirmed",
    48 : "Confirmed on",
    49 : "Start a job",
    50 : "Scheduled on",
    51 : "Job Completed",
    52 : "Payment will appear here",
    53 : "Pricing",
    54 : "Quantity",
    55 : "Tax amount",
    56 : "Total",
    57 : "Press for view profile",
    58 : "reviews",
    59 : "Read all",
    60 : "Change Language",
    61 : "Set your Preferred language",
    62 : "Enter your Email",
    63 : "Address",
    64 : "Enter address for customers",
    65 : "Description",
    66 : "Enter Short description about you",
    67 : "SAVE",
    68 : "Change password",
    69 : "New password",
    70 : "Enter Password",
    71 : "Confirm New password",
    72 : "CHANGE PASSWORD",
    73 : "My Profile",
    74 : "Everything about you",
    75 : "Average Ratings",
    76 : "Enable Dark Mode",
    77 : "Set you favorite mode",
    78 : "Wallet",
    79 : "Know your earnings",
    80 : "My Portfolio",
    81 : "Upload your best works",
    82 : "Privacy Policy",
    83 : "Known our Privacy Policy",
    84 : "From Gallery",
    85 : "From Camera",
    86 : "Delete",
    87 : "Set invisible",
    88 : "Available Balance",
    89 : "Notifications",
    90 : "Lots of important information",
    91 : "Log Out",
    92 : "End the session",
    93 : "Please Enter Email",
    94 : "Please Enter Password",
    95 : "User not found",
    96 : "User is disabled. Connect to Administrator for more information.",
    97 : "Passwords are not equal",
    98 : "Email are wrong",
    99 : "User don't create",
    100 : "You account created. After moderation your account will be activated. We will inform you.",
    101 : "Chatting online",
    102 : "Search",
    103 : "Chat message",
    104 : "Notifications",
    105 : "Lots of important information",
    106 : "Today",
    107 : "Not found ...",
    108 : "About Us",
    109 : "Known About Us",
    110 : "Terms & Conditions",
    111 : "Known Terms & Conditions",
    112 : "Enter your name",
    113 : "Enter Confirm Password",
    114 : "Password changed",
    115 : "Please Enter name",
    116 : "Data saved",
    117 : "Booking status was changed",
    118 : "Now status:",
    119 : "by customer",
    120 : "by provider",
    121 : "by administrator",
    122 : "Money transfer",
    123 : "My page",
    124 : "Edit Provider information",
    125 : "Monday",
    126 : "Tuesday",
    127 : "Wednesday",
    128 : "Thursday",
    129 : "Friday",
    130 : "Saturday",
    131 : "Sunday",
    132 : "Galleries",
    133 : "Edit",
    134 : "Save",
    135 : "Enter your Phone",
    136 : "Enter your Web Page address",
    137 : "Enter your Instagram address",
    138 : "Enter your Telegram address",
    139 : "Change",
    140 : "Add from galley",
    141 : "Add from camera",
    142 : "My Services",
    143 : "Edit Service information",
    144 : "Search service",
    145 : "Do you want to delete this item? You will can't recover this item.",
    146 : "No",
    147 : "This is Demo Mode. You can't modify this section",
    148 : "Edit Service",
    149 : "Visible",
    150 : "Select Language",
    151 : "Tax",
    152 : "Description Title",
    153 : "Price",
    154 : "Discount price",
    155 : "Price Unit",
    156 : "Hourly",
    157 : "Fixed",
    158 : "Select image",
    159 : "Addons",
    160 : "Add addon",
    161 : "Gallery",
    162 : "Image deleted",
    163 : "Add image from gallery",
    164 : "Service duration",
    165 : "min",
    166 : "Only selected",
    167 : "Categories",
    168 : "Providers",
    169 : "Save current service",
    170 : "Please enter price",
    171 : "Please select provider",
    172 : "Please enter category",
    173 : "Save addon",
    174 : "Close",
    175 : "Select",
    176 : "Addon will be deleted from all services in current Provider. Do you want to delete this item? You will can't recover this item. ",
    177 : "Data deleted",
    178 : "Create new service",
    179 : "My Work Area",
    180 : "Edit your work area",
    181 : "Delete current",
    182 : "Forgot password?",
    183 : "Reset password",
    184 : "Send new password",
    185 : "Reset password email sent. Please check your mail.",
    186 : "Time creation",
    187 : "Please Enter phone",
    188 : "Please leave information for us to make it easier for us to work with you.",
    189 : "Provider Name",
    190 : "Home service",
    191 : "Login",
    192 : "Phone",
    193 : "Set my Work Area",
    194 : "Set Provider Logo",
    195 : "Please Enter Provider Name",
    196 : "Please Enter description",
    197 : "Please Enter address",
    198 : "Please upload Provider Logo",
    199 : "Please select work area",
    200 : "Please select Category where you will work",
    201 : "Please Enter Login",
    202 : "Payment method",
    203 : "Subtotal",
    204 : "Discount",
    205 : "User must be Provider",
    206 : "Provider Information not found",
    207 : "Are you sure you want to exit?",
    208 : "Exit",
    209 : "On map",
    210 : "Customer location",
    211 : "Customer address",
    212 : "Enable Notify",
    213 : "Provider Available/Unavailable",
    214 : "Temporary disable your account",
    215 : "VAT/TAX",
    216 : "Total amount",
    217 : "Booking At",
    218 : "Customer name",
    219 : "To Admin",
    220 : "To Provider",
    221 : "TAX/VAT",
    222 : "Payouts",
    223 : "Balance",
    224 : "Orders",
    225 : "My Products",
    226 : "Edit Products information",
    227 : "Search in this list",
    228 : "Create new product",
    229 : "Not available Now",
    230 : "Add image URL",
    231 : "Description:",
    232 : "You can use HTML tags (<p>, <br>, <h1> and other)",
    233 : "Variants",
    234 : "Add new group",
    235 : "Add new variant",
    236 : "Save current product",
    237 : "Add New Product",
    238 : "Unit",
    239 : "In Stock",
    240 : "pcs",
    241 : "Please select variant",
    242 : "Save group",
    243 : "Add group",
    244 : "Group name",
    245 : "Preview",
    246 : "URL",
    247 : "Add image",
    248 : "Variant name",
    249 : "Add image from gallery (optional)",
    250 : "or",
    251 : "Add image URL (optional)",
    252 : "influence on price +/-",
    253 : "Save variant",
    254 : "Add variant",
    255 : "Please select stock",
    256 : "influence must start with + or -",
    257 : "Close",
    258 : "Add image from camera",
    259 : "Add image from camera (optional)",
    260 : "Please upload image",
    261 : "Cancel",
    262 : "You have exceeded the limit on the number of services. Contact support for more information.",
    263 : "Category tree",
    264 : "Price can't be 0",
    265 : "You have exceeded the limit on the number of addons on one service. Contact support for more information.",
    266 : "You have exceeded the limit on the number of products. Contact support for more information.",
    267 : "Minimum order amount",
    268 : "Maximum order amount",
    269 : "Settings",
    270 : "Set minimum amd maximum order amounts",
    271 : "Please enter minimum order amount",
    272 : "Please enter maximum order amount",
    273 : "Allow booking only if customer located in provider work area",
    274 : "Subscription Status",
    275 : "Expire date",
    276 : "Subscribed",
    277 : "Not Subscribed",
    278 : "Subscribe now",
    279 : "Extend your subscription",
    280 : "",
    281 : "Start Free Trial Now",
    282 : "Start",
    283 : "Pay with",
    284 : "You subscriptions expired",
    285 : "Expired",
    286 : "Confirm Subscription. Do you want to subscribe for Two month for",
    287 : "Free Trial",
  };

  Map<String, dynamic>? defaultLang;

  setLang(Map<String, dynamic> _def, String _locale, BuildContext context, TextDirection _direction){
    defaultLang = _def;
    locale = _locale;
    direction = _direction;
    Provider.of<LanguageChangeNotifierProvider>(context,listen:false).changeLocale(locale);
  }

  String get(int id){
    if (defaultLang == null) {
      return langEng[id] == null ? "" : langEng[id]!;
    }else{
      if (defaultLang![id.toString()] != null)
        return defaultLang![id.toString()];
      return langEng[id] == null ? "" : langEng[id]!;
    }
  }

}

