import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../main.dart';

Lang strings = Lang();

class Lang {

  int languageVersion = 30;
  var direction = TextDirection.ltr;
  String locale = "en";

  Map<int, String> langEng = {
    0 : "HANDYMAN",
    1 : "Settings | Payment Gateways",
    2 : "Enable Stripe Payment",
    3 : "Publishable key:",
    4 : "Secret key:",
    5 : "Enable PayPal Payment",
    6 : "Client Id:",
    7 : "Secret key:",
    8 : "Enable Razorpay Payment",
    9 : "Save",
    10 : "Key Id:",
    11 : "Your company name:",
    12 : "Dark Mode",
    13 : "Send Notification",
    14 : "All users",
    15 : "Select user:",
    16 : "Message Title:",
    17 : "Send",
    18 : "Message Text:",
    19 : "Title of message",
    20 : "Text of message",
    21 : "View all messages",
    22 : "Settings | Documents",
    23 : "Copyright text:",
    24 : "About Us",
    25 : "Preview",
    26 : "Privacy Policy",
    27 : "Terms & Conditions",
    28 : "Settings | General",
    29 : "App Name:",
    30 : "Default unit of distance:",
    31 : "Currency",
    32 : "General",
    33 : "Settings",
    34 : "Settings | Currency",
    35 : "Currency Code:",
    36 : "Currency Symbol:",
    37 : "Digits after comma:",
    38 : "Currency symbol in right",
    39 : "Time Format:",
    40 : "Share This App",
    41 : "Payment Gateways",
    42 : "Settings | Share This App Menu",
    43 : "Google Play Link",
    44 : "AppStore Link",
    45 : "Date Format:",
    46 : "Google Maps Api Key:",
    47 : "Firebase Cloud Messaging Key:",
    48 : "Firebase OTP",
    49 : "Enable irebase OTP",
    50 : "OTP prefix (ex: for India +91)",
    51 : "Number of digits (without prefix)",
    52 : "Settings | Firebase OTP",
    53 : "Data copied to clipboard",
    54 : "Name",
    55 : "Preview",
    56 : "Categories",
    57 : "Add New Category",
    58 : "Copy",
    59 : "Export to CSV",
    60 : "Search",
    61 : "No",
    62 : "Delete",
    63 : "Do you want to delete this item? You will can't recover this item.",
    64 : "Data deleted",
    65 : "This is Demo Mode. You can't modify this section",
    66 : "Action",
    67 : "Search service",
    68 : "Edit",
    69 : "Data deleted",
    70 : "Visible",
    71 : "Show Category Details in Main Screen",
    72 : "Select color",
    73 : "Description",
    74 : "Select parent category",
    75 : "Select image",
    76 : "Save current category",
    77 : "Create new category",
    78 : "Users",
    79 : "Roles",
    80 : "Please Enter Role name",
    81 : "Data saved",
    82 : "Save All",
    83 : "Role name",
    84 : "Add Role",
    85 : "Add New User",
    86 : "Email",
    87 : "Role",
    88 : "from",
    89 : "Show",
    90 : "entries",
    91 : "Please Enter Name",
    92 : "Please enter email",
    93 : "Password",
    94 : "Please enter password",
    95 : "Select role:",
    96 : "Providers",
    97 : "Address",
    98 : "Customer App Settings",
    99 : "Customer App Settings",
    100 : "Splash Screen",
    101 : "Login Screen",
    102 : "Register Screen",
    103 : "Main color",
    104 : "Main background color",
    105 : "Words in screen",
    106 : "Apps Settings",
    107 : "Languages",
    108 : "Select language",
    109 : "Select Application",
    110 : "Customer Service Application",
    111 : "Provider Application",
    112 : "Admin Panel",
    113 : "Word",
    114 : "Id",
    115 : "Cancel",
    116 : "Main Screen",
    117 : "Provider Screen",
    118 : "Upper image",
    119 : "Logo image",
    120 : "Description Title",
    121 : "Create new provider",
    122 : "Save current provider",
    123 : "Add New Provider",
    124 : "Phone",
    125 : "Web Page",
    126 : "Telegram",
    127 : "Instagram",
    128 : "Gallery",
    129 : "Add image to gallery",
    130 : "Tax",
    131 : "Default language",
    132 : "default",
    133 : "Working time",
    134 : "Monday",
    135 : "Tuesday",
    136 : "Wednesday",
    137 : "Thursday",
    138 : "Friday",
    139 : "Saturday",
    140 : "Sunday",
    141 : "Weekend",
    142 : "Services",
    143 : "Service Screen",
    144 : "Price",
    145 : "Discount price",
    146 : "Create new service",
    147 : "Save current service",
    148 : "Add New Service",
    149 : "Hourly",
    150 : "Fixed",
    151 : "Price Unit",
    152 : "Documents",
    153 : "Home",
    154 : 'Earning',
    155 : 'Sales',
    156 : "Offers",
    157 : "Customers",
    158 : "Category",
    159 : "Service",
    160 : 'Total Orders',
    161 : "Chat",
    162 : "Message ...",
    163 : "CODE",
    164 : "Discount",
    165 : "Percentage",
    166 : "Discount type",
    167 : "Expire",
    168 : "Only selected",
    169 : "Create new offer",
    170 : "Save current offer",
    171 : "Add New offer",
    172 : "Booking Statuses",
    173 : "Settings | Booking Statuses",
    174 : "Add new",
    175 : "Booking",
    176 : "Coupon",
    177 : "Total",
    178 : "Provider",
    179 : "User",
    180 : "Comment",
    181 : "Booking list",
    182 : "Status",
    183 : "Booking At",
    184 : "Close",
    185 : "Data saved for language: ",
    186 : "Welcome. Please Login to continue",
    187 : "Email",
    188 : "Remember me",
    189 : "Sign In",
    190 : "Forgot password?",
    191 : "Username or password is incorrect",
    192 : "Reset password",
    193 : "Send new password",
    194 : "Reset password email sended. Please check your mail.",
    195 : "Please enter Stripe credentials",
    196 : "Please enter PayPal credentials",
    197 : "Please enter Razorpay credentials",
    198 : "Please enter OTP prefix",
    199 : "Please enter number of digits",
    200 : " You can use HTML tags (<p>, <br>, <h1> and other)",
    201 : "Can't initialize language data",
    202 : "Loading data ...",
    203 : "Loading settings ...",
    204 : "Loading languages ...",
    205 : "Installation languages ...",
    206 : "Read languages ...",
    207 : "Add new language",
    208 : "By default all words will be in english language. You must translate all words by himself.",
    209 : "Create",
    210 : "Language added",
    211 : "default image",
    212 : "Save words",
    213 : "Loading Service App theme ...",
    214 : "Logo",
    215 : "Image",
    216 : "Loader color",
    217 : "Language Screen",
    218 : "Loading Category ...",
    219 : "Image deleted",
    220 : "Service duration",
    221 : "Please select provider",
    222 : "Please enter Title",
    223 : "Please enter Message Text",
    224 : "Message send",
    225 : "Save current",
    226 : "Create new",
    227 : "Upload status images ...",
    228 : "Managed by Customer App",
    229 : "Managed by Provider App",
    230 : "Canceling",
    231 : "Current image",
    232 : "Category tree",
    233 : "Sample Data",
    234 : "Settings | Upload Sample Data",
    235 : "In this page you can upload sample data.",
    236 : "Enter text",
    237 : "Upload",
    238 : "All data in Categories, Services and Providers sections will be overwrite. All old data will be deleted. All images in Categories, Services and Provider sections will be deleted",
    239 : "Upload categories ...",
    240 : "Uploading Complete!",
    241 : "Delete categories ...",
    242 : "Delete providers ...",
    243 : "Delete services ...",
    244 : "Upload providers ...",
    245 : "Upload services",
    246 : "Providers Requests",
    247 : "Assign",
    248 : "Login Email",
    249 : "For assign new provider set needed fields. And press button Create new provider at the down of this page. Don't change Login Email, because the new provider will enter with this email. ",
    250 : "Permission denied",
    251 : "Starting upload ...",
    252 : "Chat message",
    253 : "Sort by",
    254 : "All",
    255 : "Customers list",
    256 : "Enabled",
    257 : "Disabled",
    258 : "Disable",
    259 : "Enable",
    260 : "Service Reviews",
    261 : "Service Reviews list",
    262 : "User name",
    263 : "Earnings",
    264 : "Bookings",
    265 : "Default Tax for provider (administration payment)",
    266 : "Tax for administration",
    268 : "Admin",
    269 : "To payout",
    270 : "Payout",
    271 : "Max payout",
    272 : "Providers Payouts",
    273 : "Time",
    274 : "Time Descend",
    275 : "Time Ascend",
    276 : "Total Descend",
    277 : "Total Ascend",
    278 : "Name Ascend",
    279 : "Name Descend",
    280 : "Any time",
    281 : "Customer",
    282 : "Service",
    283 : "Count",
    284 : "Payment Method",
    285 : "Parent Id",
    286 : "Rating",
    287 : "Review",
    288 : "Categories Screen",
    289 : "Booking Screen",
    290 : "Chat users Screen",
    291 : "Chat Screen",
    292 : "Notifications Screen",
    293 : "Account Screen",
    294 : "Profile Screen",
    295 : "Documents Screen",
    296 : "Booking Screen #1",
    297 : "Add Address Screen",
    298 : "Booking Screen #2",
    299 : "Booking Screen #3",
    300 : "Booking Screen #4",
    301 : "Booking Screen #5",
    302 : "'Gallery' Logo",
    303 : "'Reviews & Ratings' Logo",
    304 : "Star color",
    305 : "Category board color",
    306 : "'Not found' image",
    307 : "Send Button Image",
    308 : "CheckBox color",
    309 : "Enable Firebase OTP",
    310 : "User Name",
    311 : "User avatar",
    312 : "Settings | User Profile",
    313 : "Please enter PayStack credentials",
    314 : "Please enter FlutterWave credentials",
    315 : "Enable PayStack Payment",
    316 : "Enable Flutterwave Payment",
    317 : "Public key:",
    318 : "Encryption key:",
    319 : "Update  languages ...",
    320 : "Favorites",
    321 : "Count Ascend",
    322 : "Count Descend",
    323 : "Category Ascend",
    324 : "Category Descend",
    325 : "Provider Ascend",
    326 : "Provider Descend",
    327 : "This list includes services that users add to favorites in their applications. The count is how many users have added this service to their favorites.",
    328 : "Banners",
    329 : "Banner type",
    330 : "Open service",
    331 : "Open provider",
    332 : "Open category",
    333 : "Create new banner",
    334 : "Save current banner",
    335 : "Add New banner",
    336 : "hidden",
    337 : "List Service",
    338 : "Select services which will be always show in main screen in customer app (Top Services). ",
    339 : "Main Screen",
    340 : "Customer App Main Screen - Elements position",
    341 : "Please enter code",
    342 : "Please enter price",
    343 : "Please enter category",
    344 : "Coordinates (draw your zone area on the map)\nFor move map use right mouse button.",
    345 : "Delete current",
    346 : "min",
    347 : "Addons",
    348 : "Add addon",
    349 : "Select",
    350 : "Addon will be deleted from all services in current Provider. Do you want to delete this item? You will can't recover this item. ",
    351 : "Save addon",
    352 : "Blog",
    353 : "Date",
    354 : "Create new post",
    355 : "Save post",
    356 : "Your text here...",
    357 : "Please enter text",
    358 : "Default Admin Commission",
    359 : "Short description",
    360 : "Please enter short description",
    361 : "Please select preview image",
    362 : "Preview image (ratio 1:1)",
    363 : "Image saved",
    364 : "Details",
    365 : "Earnings details",
    366 : "Back to list",
    367 : "SMS OTP Verify",
    368 : "PayPal SandBox mode",
    369 : "You must settings Firebase OTP in Google Firebase Console",
    370 : "Enable Twilio SMS",
    371 : "Account SID",
    372 : "Auth token",
    373 : "Service Id",
    374 : "Please enter Account SID",
    375 : "Please enter Auth Token",
    376 : "Please enter Service Id",
    377 : "Enable Nexmo SMS",
    378 : "From",
    379 : "Api Key",
    380 : "Api secret",
    381 : "Enable SMS.to SMS",
    382 : "Please enter Nexmo From",
    383 : "Please enter Nexmo Text",
    384 : "Please enter Nexmo API key",
    385 : "Please enter Nexmo API Secret",
    386 : "Please enter SMS.to From",
    387 : "Please enter SMS.to Text",
    388 : "Your code is {code}",
    389 : "Web Site",
    390 : "Enable MercadoPago Payment",
    391 : "Access Token:",
    392 : "Enable PayMob Payment",
    393 : "API key:",
    394 : "Integration Id:",
    395 : "Frame Id:",
    396 : "Enable Instamojo Payment",
    397 : "Token:",
    398 : "Instamojo SandBox mode",
    399 : "Please enter MercadoPago credentials",
    400 : "Please enter PayMob credentials",
    401 : "Please enter Instamojo credentials",
    402 : "Enable PayU Payment",
    403 : "PayU SandBox mode",
    404 : "Merchant Id",
    405 : "Please enter PayU credentials",
    406 : "View",
    407 : "New Provider information",
    408 : "Provider Name",
    409 : "Work Area",
    410 : "Pricing",
    411 : "Quantity",
    412 : "Tax amount",
    413 : "Subtotal",
    414 : "Available only in Customer App (In Web Site unavailable)",
    415 : "Now status:",
    416 : "Booking status was changed",
    417 : "Provider App Settings",
    418 : "WebSite App Settings",
    419 : "Go back",
    420 : "Delete image",
    421 : "Restore settings",
    422 : "Admin Panel Settings",
    423 : "Products",
    424 : "Global (owner) item",
    425 : "Create new product",
    426 : "Add New Product",
    427 : "Save current product",
    428 : "Please upload image",
    429 : "Modify",
    430 : "Add image URL",
    431 : "URL",
    432 : "Add image",
    433 : "Variants",
    434 : "Add new group",
    435 : "Add group",
    436 : "Variant name",
    437 : "Add new variant",
    438 : "Group name",
    439 : "Add variant",
    440 : "Add image (optional)",
    441 : "Add image URL (optional)",
    442 : "or",
    443 : "influence on price +/-",
    444 : "influence must start with + or -",
    445 : "Save group",
    446 : "In Stock",
    447 : "pcs",
    448 : "Save variant",
    449 : "Please select variant",
    450 : "Last Time Modify",
    451 : "Please select stock",
    452 : "Unit",
    453 : "App version",
    454 : "Convert bookings ...",
    455 : "Invoice",
    456 : "Order ID",
    457 : "Count products",
    458 : "Bill to",
    459 : "Product name",
    460 : "Qty",
    461 : "Unit price",
    462 : "Sub Total",
    463 : "Total Tax",
    464 : "Coupon Discount",
    465 : "INVOICE",
    466 : "Order Date",
    467 : "Grand Total",
    468 : "Not provider. Administration",
    469 : "Loading Product cache ...",
    470 : "Administration Email",
    471 : "Administration Phone",
    472 : "Price can't be 0",
    473 : "Available",
    474 : "Maximum services count for this provider",
    475 : "Maximum addons count for each service",
    476 : "Maximum products count for this provider",
    477 : "Minimum order amount",
    478 : "Maximum order amount",
    479 : "Enable payment in cache for this provider",
    480 : "Please Enter Login Email",
    481 : "Please Enter Address",
    482 : "Please Enter Work Area",
    483 : "Please upload Logo image",
    484 : "Minimum purchase amount must be smaller then maximum purchase amount ",
    485 : "Minimum and maximum purchase amount must be different",
    486 : "Please select categories",
    487 : "Please enter minimum order amount",
    488 : "Please enter maximum order amount",
    489 : "Allow booking only if customer located in provider work area",

    490 : "Subscriptions",
    491 : "Create new subscription",
    492 : "Text",
    493 : "Days",
    494 : "Multiline text",
    495 : "Save current subscription",
    496 : "Please enter number of days",
    497 : "Enable subscriptions for all providers",
    498 : "Promotion text",
    499 : "Free Trial",
    500 : "You can't delete all subscriptions. For delete this, add new subscription before.",
    501 : "Expired",
    502 : 'If price is 0, it means that this period will be free, i.e. "Free trial"',
    503 : "Start Free Trial Now",
    504 : "Start",
    505 : "Not subscribed",
    506 : "Subscription expired at",
    507 : "Visible in app. (If uncheck: in app offer don't showing. Customer can only enter text code)",
    508 : "Use now",
    509 : "Valid until",
    510 : "Special offer",

  };

  setLang(String id, Map<String, dynamic> _def, BuildContext context, TextDirection _direction){
    locale = id;
    defaultLang = _def;
    direction = _direction;

    langCopyExportSearch = {
      "copy" : get(58),  // "Copy",
      "export_csv" : get(59), // "Export to CSV",
      "show" : get(89), // "Show",
      "entries" : get(90), // "entries",
      "search" : get(60), // "Search",
    };

    Provider.of<LanguageChangeNotifierProvider>(context,listen:false).changeLocale(locale);
  }

  Map<String, dynamic>? defaultLang;

  String get(int id){
    if (defaultLang == null) {
      var ret = langEng[id] == null ? "" : langEng[id]!;
      // dprint("lang id=$id ret=$ret");
      return ret;
    }else{
      if (defaultLang![id.toString()] != null)
        return defaultLang![id.toString()];
      return langEng[id] == null ? "" : langEng[id]!;
    }
  }

  Map<String, String> langCopyExportSearch = {};
}

