import 'package:flutter/material.dart';

Lang strings = Lang();

class Lang {

  var direction = TextDirection.ltr;

  Map<int, String> langEng = {
    0 : "HANDYMAN",
    1 : "SERVICE",
    2 : "SUBMIT",
    3 : "Language",
    4 : "Preferred Language",
    5 : "Select Preferred Language",
    6 : "Home",
    7 : "Chat",
    8 : "Booking",
    9 : "Account",
    10 : "Change Language",
    11 : "Set your Preferred language",
    12 : "Enable Dark Mode",
    13 : "Set you favorite mode",
    14 : "Privacy Policy",
    15 : "Known our Privacy Policy",
    16 : "View profile",
    17 : "Log Out",
    18 : "End the session",
    19 : "Notifications",
    20 : "Lots of important information",
    21 : "Name",
    22 : "Enter your name",
    23 : "Email",
    24 : "Enter your Email",
    25 : "Phone number",
    26 : "Enter your Phone number",
    27 : "Address",
    28 : "Enter address for customers",
    29 : "Description",
    30 : "Enter Short description about you",
    31 : "SAVE",
    32 : "Change password",
    33 : "New password",
    34 : "Enter Password",
    35 : "Confirm New password",
    36 : "Enter Password",
    37 : "CHANGE PASSWORD",
    38 : "My Profile",
    39 : "Everything about you",
    40 : "reviews",
    41 : "Read all",
    42 : "Average Ratings",
    43 : "Sign in now",
    44 : "Password",
    45 : "Enter your Password",
    46 : "CONTINUE",
    47 : "REGISTER",
    48 : "or continue with",
    49 : "Register",
    50 : "in less than a minute",
    51 : "Confirm Password",
    52 : "Verification",
    53 : "We'll sent verification code.",
    54 : "We've sent 6 digit verification code.",
    55 : "Enter code",
    56 : "Enter 6 digits code",
    57 : "Write your message ...",
    58 : "New",
    59 : "Accepted",
    60 : "In progress",
    61 : "Completed",
    62 : "Canceled",
    63 : "Booking",
    64 : "Call now",
    65 : "Message",
    66 : "Booking ID",
    67 : "New Request",
    68 : "Booking Accepted",
    69 : "Accepted on",
    70 : "Start a job",
    71 : "Scheduled on",
    72 : "Job Completed",
    73 : "Payment will appear here",
    74 : "Pricing",
    75 : "Quantity",
    76 : "Tax amount",
    77 : "Total",
    78 : "Requested on",
    79 : "Payment",
    80 : "Make payment",
    81 : "Cash payment",
    82 : "Confirm Payment",
    83 : "Review",
    84 : "Leave a Review",
    85 : "Chatting online",
    86 : "Write your review",
    87 : "Tell us something about this service",
    88 : "Click on the stars to rate this service",
    89 : "Submit Review",
    90 : "Add Images",
    91 : "From Gallery",
    92 : "From Camera",
    93 : "Home services",
    94 : "Find what you need",
    95 : "Search service",
    96 : "Notify",
    97 : "Duration",
    98 : "min",
    99 : "This service can take up to",
    100 : "Galleries",
    101 : "Reviews & Ratings",
    102 : "Book This Service",
    103 : "Your address",
    104 : "Add new",
    105 : "Hint",
    106 : "Is there anything else",
    107 : "Coupon Code",
    108 : "Apply",
    109 : "Any Time",
    110 : "Schedule an Order",
    111 : "Requested Service on",
    112 : "Select a Date & Time",
    113 : "CONFIRM & BOOKING NOW",
    114 : "OK",
    115 : "Your booking has been successfully submitted, you will receive a confirmation soon.",
    116 : "Thank you!",
    117 : "Add Address",
    118 : "My Home",
    119 : "Full address",
    120 : "Select address",
    121 : "Pick here",
    122 : "Search",
    123 : "Monday",
    124 : "Tuesday",
    125 : "Wednesday",
    126 : "Thursday",
    127 : "Friday",
    128 : "Saturday",
    129 : "Sunday",
    130 : "fixed",
    131 : "hourly",
    132 : "start from",
    133 : "Please enter address",
    134 : "Please select address",
    135 : "Please Enter Email",
    136 : "Please Enter Password",
    137 : "User not found",
    138 : "User don't create",
    139 : "Email are wrong",
    140 : "Passwords are not equal",
    141 : "Phone number must be ",
    142 : "symbols",
    143 : "Code sent. Please check your phone for the verification code.",
    144 : "Time Out",
    145 : "Today",
    146 : "About Us",
    147 : "Known About Us",
    148 : "Terms & Conditions",
    149 : "Known Terms & Conditions",
    150 : "Not found ...",
    151 : "Enter Confirm Password",
    152 : "Password changed",
    153 : "Please Enter name",
    154 : "Data saved",
    155 : "Provider",
    156 : "Chat message",
    157 : "New Booking was arrived",
    158 : "Now status:",
    159 : "Booking status was changed",
    160 : "From user:",
    161 : "Rate this service",
    162 : "Coupon not found",
    163 : "Coupon activated",
    164 : "Coupon not supported by this provider",
    165 : "Coupon not support this category",
    166 : "Coupon not support this service",
    167 : "Coupon",
    168 : "no",
    169 : "Coupon has expired",

    231 : "Time creation"
  };

  Map<String, dynamic>? defaultLang;

  setLang(Map<String, dynamic> _def){
    defaultLang = _def;
  }

  String get(int id){
    if (defaultLang == null) {
      return langEng[id] == null ? "" : langEng[id]!;
    }else{
      return defaultLang![id.toString()] != null ? defaultLang![id.toString()]! : langEng[id] != null ? langEng[id]! : "";
    }
  }
}

