name: ondemand_admin
description: On Demand Admin Panel Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  abg_utils: 8.0.2
  html_editor_enhanced: 2.4.0+1
  timeago: ^3.1.0
  maps_toolkit: ^2.0.0
  google_maps_flutter_web: 0.3.2+1
  google_maps_flutter: 2.1.1
  universal_html: 2.0.8
  soundpool: 2.2.0
  provider: 6.0.2
  image_picker: 0.8.4+7
  syncfusion_flutter_charts: 19.2.62


  flutter:
    sdk: flutter

  flutter_lints: ^1.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/dashboard2/
    - assets/fonts/
    - assets/ondemands/
    - assets/elements/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Harmattan # arabic
      fonts:
        - asset: assets/fonts/Harmattan-Regular.ttf
          weight: 400
        - asset: assets/fonts/Harmattan-Bold.ttf
          weight: 800
