Map<int, String> servicesEng = {
  0 : "HANDYMAN",
  1 : "SERVICE",
  2 : "SUBMIT",
  3 : "Language",
  4 : "Preferred Language",
  5 : "Select Preferred Language",
  6 : "Home",
  7 : "Chat",
  8 : "Booking",
  9 : "Account",
  10 : "Change Language",
  11 : "Set your Preferred language",
  12 : "Enable Dark Mode",
  13 : "Set you favorite mode",
  14 : "Privacy Policy",
  15 : "Known our Privacy Policy",
  16 : "View profile",
  17 : "Log Out",
  18 : "End the session",
  19 : "Notifications",
  20 : "Lots of important information",
  21 : "Name",
  22 : "Enter your name",
  23 : "Email",
  24 : "Enter your Email",
  25 : "Phone number",
  26 : "Enter your Phone number",
  27 : "Address",
  28 : "Enter address for customers",
  29 : "Description",
  30 : "Enter Short description about you",
  31 : "SAVE",
  32 : "Change password",
  33 : "New password",
  34 : "Enter Password",
  35 : "Confirm New password",
  36 : "Enter Password",
  37 : "CHANGE PASSWORD",
  38 : "My Profile",
  39 : "Everything about you",
  40 : "reviews",
  41 : "Read all",
  42 : "Average Ratings",
  43 : "Sign in now",
  44 : "Password",
  45 : "Enter your Password",
  46 : "CONTINUE",
  47 : "REGISTER",
  48 : "or continue with",
  49 : "Register",
  50 : "in less than a minute",
  51 : "Confirm Password",
  52 : "Verification",
  53 : "We'll sent verification code.",
  54 : "We've sent 6 digit verification code.",
  55 : "Enter code",
  56 : "Enter 6 digits code",
  57 : "Write your message ...",
  58 : "New",
  59 : "Accepted",
  60 : "In progress",
  61 : "Completed",
  62 : "Canceled",
  63 : "Booking",
  64 : "Call now",
  65 : "Message",
  66 : "Booking ID",
  67 : "New Request",
  68 : "Booking Accepted",
  69 : "Accepted on",
  70 : "Start a job",
  71 : "Scheduled on",
  72 : "Job Completed",
  73 : "Payment will appear here",
  74 : "Pricing",
  75 : "Quantity",
  76 : "Tax amount",
  77 : "Total",
  78 : "Requested on",
  79 : "Payment",
  80 : "Make payment",
  81 : "Cash payment",
  82 : "Confirm Payment",
  83 : "Review",
  84 : "Leave a Review",
  85 : "Chatting online",
  86 : "Write your review",
  87 : "Tell us something about this service",
  88 : "Click on the stars to rate this service",
  89 : "Submit Review",
  90 : "Add Images",
  91 : "From Gallery",
  92 : "From Camera",
  93 : "Home services",
  94 : "Find what you need",
  95 : "Search service",
  96 : "Notify",
  97 : "Duration",
  98 : "min",
  99 : "This service can take up to",
  100 : "Galleries",
  101 : "Reviews & Ratings",
  102 : "Book This Service",
  103 : "Your address",
  104 : "Add new",
  105 : "Hint",
  106 : "Is there anything else",
  107 : "Coupon Code",
  108 : "Apply",
  109 : "Any Time",
  110 : "Schedule an Order",
  111 : "Requested Service on",
  112 : "Select a Date & Time",
  113 : "CONFIRM & BOOKING NOW",
  114 : "OK",
  115 : "Your booking has been successfully submitted, you will receive a confirmation soon.",
  116 : "Thank you!",
  117 : "Add Address",
  118 : "My Home",
  119 : "Full address",
  120 : "Select address",
  121 : "Pick here",
  122 : "Search",
  123 : "Monday",
  124 : "Tuesday",
  125 : "Wednesday",
  126 : "Thursday",
  127 : "Friday",
  128 : "Saturday",
  129 : "Sunday",
  130 : "fixed",
  131 : "hourly",
  132 : "start from",
  133 : "Please enter address",
  134 : "Please select address",
  135 : "Please Enter Email",
  136 : "Please Enter Password",
  137 : "User not found",
  138 : "User don't create",
  139 : "Email are wrong",
  140 : "Passwords are not equal",
  141 : "Phone number must be ",
  142 : "symbols",
  143 : "Code sent. Please check your phone for the verification code.",
  144 : "Time Out",
  145 : "Today",
  146 : "About Us",
  147 : "Known About Us",
  148 : "Terms & Conditions",
  149 : "Known Terms & Conditions",
  150 : "Not found ...",
  151 : "Enter Confirm Password",
  152 : "Password changed",
  153 : "Please Enter name",
  154 : "Data saved",
  155 : "Provider",
  156 : "Chat message",
  157 : "New Booking was arrived",
  158 : "Now status:",
  159 : "Booking status was changed",
  160 : "From user:",
  161 : "Rate this service",
  162 : "Coupon not found",
  163 : "Coupon activated",
  164 : "Coupon not supported by this provider",
  165 : "Coupon not support this category",
  166 : "Coupon not support this service",
  167 : "Coupon",
  168 : "no",
  169 : "Coupon has expired",
  170 : "Your Favorites",
  171 : "View your favorite services",
  172 : "Top Services",
  173 : "User is disabled. Connect to Administrator for more information.",
  174 : "Blog",
  175 : "View all",
  176 : "Loading ...",
  177 : "Service",
  178 : "Are you sure you want to exit?",
  179 : "No",
  180 : "Exit",
  181 : "Filter",
  182 : "Sort by",
  183 : "Ascending (A-Z)",
  184 : "Descending (Z-A)",
  185 : "Price",
  186 : "Reset Filter",
  187 : "Apply Filter",
  188 : "My Address",
  189 : "Address not found",
  190 : "Home",
  191 : "Office",
  192 : "Other",
  193 : "Set Location",
  194 : "Find services near your",
  195 : "By allowing location access, you can search for services and providers near your.",
  196 : "Use currents location",
  197 : "Set from map",
  198 : "Add the location",
  199 : "Label as",
  200 : "Delivery Address",
  201 : "Enter Delivery Address",
  202 : "Contact name",
  203 : "Enter Contact name",
  204 : "Contact phone number",
  205 : "Enter Contact phone number",
  206 : "Save location",
  207 : "Latitude",
  208 : "Longitude",
  209 : "Please enter phone",
  210 : "by administrator",
  211 : "by provider",
  212 : "by customer",
  213 : "Enter address",
  214 : "Current address",
  215 : "Other addresses",
  216 : "Location",
  217 : "Your address is outside provider work area",
  218 : "See details",
  219 : "Special Requests",
  220 : "Provider Location",
  221 : "Addons",
  222 : "Nearby you",
  223 : "Far",
  224 : "Providers",
  225 : "Please enter valid code",
  226 : "Your phone number verified. You can't edit phone number",
  227 : "Forgot password?",
  228 : "Reset password",
  229 : "Send new password",
  230 : "Reset password email sent. Please check your mail.",
  231 : "Time creation",
  232 : "Booking ID",
  233 : "Please enter text",
  234 : "Please enter code",
  235 : "Subtotal",
  236 : "Discount",
  237 : "Subcategory",
  238 : "Share this app",
  239 : "Services nearby",
  240 : "Open Provider Page",
  241 : "Report ...",
  242 : "Block user",
  243 : "Block",
  244 : "They won't be able to message you. You won't be able to message them. They won't be notified that you blocked them. ",
  245 : "User",
  246 : "Cancel",
  247 : "blocked",
  248 : "Why are you reporting this user?",
  249 : "Your report is anonymous, except if you're reporting an intellectual property infringement. ",
  250 : "Thanks for letting us know",
  251 : "Your feedback is important in helping us keep the community safe. ",
  252 : "Unblock",
  253 : "They be able to message you. You be able to message them. They won't be notified that you unblocked them. ",
  254 : "unblocked",
  255 : "Your Favorite Providers",
  256 : "View your favorite providers",
  257 : "Favorite Providers",
  258 : "Enable Notify",
  259 : "Not available Now",
  260 : "Services",
  261 : "Provider products",
  262 : "Not available Now",
  263 : "Total amount",
  264 : "Add to cart",
  265 : "Please select variant",
  266 : "in stock",
  267 : "Product added to cart",
  268 : "Cart",
  269 : "My Cart",
  270 : "Proceed to checkout",
  271 : "Your cart is empty",
  272 : "Item price",
  273 : "This service already in the cart",
  274 : "This product already in the cart",
  275 : "Service added to cart",
  276 : "VAT/TAX",
  277 : "See more",
  278 : "Products",
  279 : "Search products",
  280 : "Sort by provider",
  281 : "Not select",
  282 : "Related products",
  283 : "Other products",
  284 : "Booking At",
  285 : "Minimum purchase amount for this provider: ",
  286 : "Maximum purchase amount for this provider: ",
  287 : "Pay with",
  288 : "Provider can't enter to customer app. Please use another credentials.",
  289 : "Add promo",
  290 : "Promo not found",
  291 : "My rewards",
  292 : "Enter code",
  293 : "Special offer",
  294 : "Use now",
  295 : "Valid until",
  296 : "Your promo code",
  297 : "Apply code",
  298 : "Coupon not support this product",
  299 : "Promo code",
  300 : "Remove",
};

Map<int, String> servicesDeu = {
  0 : "HANDYMAN",
  1 : "DIENSTLEISTUNG",
  2: "ABSENDEN",
  3: "Sprache",
  4: "Bevorzugte Sprache",
  5 : "Bevorzugte Sprache auswählen",
  6 : "Zuhause",
  7 : "Chat",
  8 : "Buchung",
  9 : "Konto",
  10 : "Sprache ändern",
  11 : "Stellen Sie Ihre bevorzugte Sprache ein",
  12 : "Dunkelmodus aktivieren",
  13 : "Stellen Sie Ihren Lieblingsmodus ein",
  14 : "Datenschutzerklärung",
  15 : "Unsere Datenschutzrichtlinie bekannt",
  16 : "Profil anzeigen",
  17 : "Abmelden",
  18 : "Sitzung beenden",
  19 : "Benachrichtigungen",
  20 : "Viele wichtige Informationen",
  21 : "Name",
  22 : "Geben Sie Ihren Namen ein",
  23 : "E-Mail",
  24 : "Geben Sie Ihre E-Mail ein",
  25 : "Telefonnummer",
  26 : "Geben Sie Ihre Telefonnummer ein",
  27 : "Adresse",
  28 : "Anschrift für Kunden eingeben",
  29 : "Beschreibung",
  30 : "Geben Sie eine kurze Beschreibung über Sie ein",
  31 : "SPEICHERN",
  32 : "Passwort ändern",
  33 : "Neues Passwort",
  34 : "Passwort eingeben",
  35 : "Neues Passwort bestätigen",
  36 : "Passwort eingeben",
  37 : "PASSWORT ÄNDERN",
  38 : "Mein Profil",
  39 : "Alles über dich",
  40 : "Bewertungen",
  41 : "Alles lesen",
  42 : "Durchschnittliche Bewertungen",
  43 : "Jetzt anmelden",
  44 : "Passwort",
  45 : "Geben Sie Ihr Passwort ein",
  46 : "WEITER",
  47 : "REGISTRIEREN",
  48 : "oder weiter mit",
  49 : "Registrieren",
  50 : "in weniger als einer Minute",
  51 : "Passwort bestätigen",
  52 : "Verifizierung",
  53 : "Wir senden den Bestätigungscode.",
  54 : "Wir haben einen 6-stelligen Bestätigungscode gesendet.",
  55 : "Code eingeben",
  56 : "Geben Sie den 6-stelligen Code ein",
  57 : "Schreiben Sie Ihre Nachricht ...",
  58 : "Neu",
  59 : "Akzeptiert",
  60 : "In Bearbeitung",
  61 : "Abgeschlossen",
  62 : "Abgesagt",
  63 : "Buchung",
  64 : "Jetzt anrufen",
  65 : "Nachricht",
  66 : "Buchungs-ID",
  67 : "Neue Anfrage",
  68 : "Buchung akzeptiert",
  69 : "Angenommen am",
  70 : "Job starten",
  71 : "Geplant am",
  72 : "Auftrag abgeschlossen",
  73 : "Die Zahlung wird hier angezeigt",
  74 : "Preise",
  75 : "Menge",
  76 : "Steuerbetrag",
  77 : "Gesamt",
  78 : "Angefordert am",
  79 : "Zahlung",
  80 : "Zahlung ausführen",
  81 : "Barzahlung",
  82 : "Zahlung bestätigen",
  83 : "Rückblick",
  84 : "Eine Bewertung hinterlassen",
  85 : "Online-Chat",
  86 : "Schreiben Sie Ihre Bewertung",
  87 : "Erzählen Sie uns etwas über diesen Service",
  88 : "Klicken Sie auf die Sterne, um diesen Service zu bewerten",
  89 : "Bewertung abgeben",
  90 : "Bilder hinzufügen",
  91 : "Aus der Galerie",
  92 : "Von der Kamera",
  93 : "Heimdienste",
  94 : "Finden Sie, was Sie brauchen",
  95 : "Suchdienst",
  96 : "Benachrichtigen",
  97 : "Dauer",
  98 : "min",
  99 : "Dieser Dienst kann bis zu dauern",
  100 : "Galerien",
  101 : "Rezensionen & Bewertungen",
  102 : "Diesen Service buchen",
  103 : "Ihre Adresse",
  104 : "Neu hinzufügen",
  105 : "Hinweis",
  106 : "Gibt es noch etwas",
  107 : "Gutscheincode",
  108 : "Bewerben",
  109 : "Jederzeit",
  110 : "Bestellung planen",
  111 : "Angeforderter Service ein",
  112 : "Wählen Sie ein Datum und eine Uhrzeit",
  113 : "JETZT BESTÄTIGEN & BUCHEN",
  114 : "OK",
  115 : "Ihre Buchung wurde erfolgreich übermittelt, Sie erhalten in Kürze eine Bestätigung.",
  116 : "Danke!",
  117 : "Adresse hinzufügen",
  118 : "Mein Zuhause",
  119 : "Vollständige Adresse",
  120 : "Adresse auswählen",
  121 : "Hier auswählen",
  122 : "Suche",
  123 : "Montag",
  124 : "Dienstag",
  125 : "Mittwoch",
  126 : "Donnerstag",
  127 : "Freitag",
  128 : "Samstag",
  129 : "Sonntag",
  130 : "fixiert",
  131 : "stündlich",
  132 : "beginnen mit",
  133 : "Bitte Adresse eingeben",
  134 : "Bitte Adresse auswählen",
  135 : "Bitte E-Mail eingeben",
  136 : "Bitte Passwort eingeben",
  137 : "Benutzer nicht gefunden",
  138 : "Benutzer erstellt nicht",
  139 : "E-Mail ist falsch",
  140 : "Passwörter sind nicht gleich",
  141 : "Telefonnummer muss sein",
  142 : "Symbole",
  143 : "Code gesendet. Bitte überprüfen Sie Ihr Telefon auf den Bestätigungscode.",
  144 : "Zeitüberschreitung",
  145 : "Heute",
  146 : "Über uns",
  147 : "Über uns bekannt",
  148 : "Allgemeine Geschäftsbedingungen",
  149 : "Bekannte Geschäftsbedingungen",
  150 : "Nicht gefunden ...",
  151 : "Passwort zur Bestätigung eingeben",
  152 : "Passwort geändert",
  153 : "Bitte Namen eingeben",
  154 : "Daten gespeichert",
  155 : "Anbieter",
  156 : "Chat-Nachricht",
  157 : "Neue Buchung ist eingetroffen",
  158 : "Jetzt Status:",
  159 : "Buchungsstatus wurde geändert",
  160 : "Von Benutzer:",
  161 : "Bewerten Sie diesen Service",
  162 : "Gutschein nicht gefunden",
  163 : "Gutschein aktiviert",
  164 : "Gutschein wird von diesem Anbieter nicht unterstützt",
  165 : "Gutschein unterstützt diese Kategorie nicht",
  166 : "Gutschein unterstützt diesen Dienst nicht",
  167 : "Gutschein",
  168 : "nein",
  169 : "Gutschein ist abgelaufen",
  170 : "Ihre Favoriten",
  171 : "Ihre Lieblingsdienste anzeigen",
  172 : "Top-Dienste",
  173 : "Benutzer ist deaktiviert. Verbinden Sie sich mit dem Administrator für weitere Informationen.",
  174 : "Blog",
  175 : "Alle anzeigen",
  176 : "Laden ...",
  177 : "Dienstleistung",
  178 : "Sind Sie sicher, dass Sie das Programm verlassen möchten?",
  179 : "Nein",
  180 : "Ausgang",
  181 : "Filter",
  182 : "Sortieren nach",
  183 : "Aufsteigend (A-Z)",
  184 : "Absteigend (Z-A)",
  185 : "Preis",
  186 : "Filter zurücksetzen",
  187 : "Filter anwenden",
  188 : "Meine Adresse",
  189 : "Adresse nicht gefunden",
  190 : "Heimat",
  191 : "Büro",
  192 : "Andere",
  193 : "Standort festlegen",
  194 : "Finden Sie Dienste in Ihrer Nähe",
  195 : "Indem Sie den Standortzugriff zulassen, können Sie nach Diensten und Anbietern in Ihrer Nähe suchen.",
  196 : "Stromstandort verwenden",
  197 : "Set von Karte",
  198 : "Ort hinzufügen",
  199 : "Label als",
  200 : "Lieferadresse",
  201 : "Lieferadresse eingeben",
  202 : "Kontaktname",
  203 : "Kontaktnamen eingeben",
  204 : "Telefonnummer kontaktieren",
  205 : "Telefonnummer des Kontakts eingeben",
  206 : "Standort speichern",
  207 : "Breitengrad",
  208 : "Längengrad",
  209 : "Bitte Telefon eingeben",
  210 : "vom Administrator",
  211 : "nach Anbieter",
  212 : "vom Kunden",
  213 : "Adresse eingeben",
  214 : "Aktuelle Adresse",
  215 : "Andere Adressen",
  216 : "Ort",
  217 : "Ihre Adresse liegt außerhalb des Arbeitsbereichs des Anbieters",
  218 : "Siehe Details",
  219 : "Sonderwünsche",
  220 : "Anbieterstandort",
  221 : "Add-ons",
  222 : "In deiner Nähe",
  223 : "Weit",
  224 : "Anbieter",
  225 : "Bitte gültigen Code eingeben",
  226 : "Ihre Telefonnummer verifiziert. Sie können die Telefonnummer nicht bearbeiten",
  227 : "Passwort vergessen?",
  228 : "Passwort zurücksetzen",
  229 : "Neues Passwort senden",
  230 : "E-Mail zum Zurücksetzen des Passworts gesendet. Bitte überprüfen Sie Ihre E-Mails.",
  231 : "Zeiterstellung",
  232 : "Buchungs-ID",
  233 : "Bitte Text eingeben",
  234 : "Bitte Code eingeben",
  235 : "Zwischensumme",
  236 : "Rabatt",
  237 : "Unterkategorie",
  238 : "Diese App teilen",
  239 : "Dienste in der Nähe",
  240 : "Anbieterseite öffnen",
  241 : "Bericht ...",
  242 : "Benutzer sperren",
  243 : "Blockieren",
  244 : "Sie können Ihnen keine Nachrichten senden. Sie können ihnen keine Nachrichten senden. Sie werden nicht benachrichtigt, dass Sie sie blockiert haben. ",
  245 : "Benutzer",
  246 : "Abbrechen",
  247 : "gesperrt",
  248 : "Warum melden Sie diesen Benutzer?",
  249 : "Ihre Meldung ist anonym, es sei denn, Sie melden eine Verletzung des geistigen Eigentums.",
  250 : "Danke für den Hinweis",
  251 : "Ihr Feedback ist wichtig, um die Sicherheit der Community zu gewährleisten. ",
  252 : "Entsperren",
  253 : "Sie können Ihnen eine Nachricht senden. Sie können ihnen eine Nachricht senden. Sie werden nicht benachrichtigt, dass Sie sie entsperrt haben. ",
  254 : "entsperrt",
  255 : "Ihre bevorzugten Anbieter",
  256 : "Ihre bevorzugten Anbieter anzeigen",
  257 : "Lieblingsanbieter",
  258 : "Benachrichtigung aktivieren",
  259 : "Jetzt nicht verfügbar",
  260 : "Dienste",
  261 : "Anbieterprodukte",
  262 : "Jetzt nicht verfügbar",
  263 : "Gesamtbetrag",
  264 : "In den Warenkorb",
  265 : "Bitte Variante auswählen",
  266 : "auf Lager",
  267 : "Produkt in den Warenkorb gelegt",
  268 : "Warenkorb",
  269 : "Mein Warenkorb",
  270 : "Zur Kasse gehen",
  271 : "Ihr Warenkorb ist leer",
  272 : "Artikelpreis",
  273 : "Dieser Service bereits im Warenkorb",
  274 : "Dieses Produkt befindet sich bereits im Warenkorb",
  275 : "Service zum Warenkorb hinzugefügt",
  276 : "Mehrwertsteuer/Steuer",
  277 : "Mehr sehen",
  278 : "Produkte",
  279 : "Produkte suchen",
  280 : "Nach Anbieter sortieren",
  281 : "Nicht auswählen",
  282 : "Verwandte Produkte",
  283 : "Andere Produkte",
  284 : "Buchung um",
  285 : "Mindestkaufbetrag für diesen Anbieter: ",
  286 : "Maximaler Einkaufsbetrag für diesen Anbieter: ",
  287 : "Bezahlen mit",
  288 : "Anbieter kann Kunden-App nicht betreten. Bitte verwenden Sie andere Zugangsdaten.",
  289 : "Angebot hinzufügen",
  290 : "Promo nicht gefunden",
  291 : "Meine Belohnungen",
  292 : "Code eingeben",
  293 : "Sonderangebot",
  294 : "Jetzt verwenden",
  295 : "Gültig bis",
  296 : "Ihr Promo-Code",
  297 : "Code anwenden",
  298 : "Gutschein unterstützt dieses Produkt nicht",
  299 : "Aktionscode",
  300 : "Entfernen",
};

Map<int, String> servicesEsp = {
  0 : "HANDYMAN",
  1: "SERVICIO",
  2: "ENVIAR",
  3: "Idioma",
  4: "Idioma preferido",
  5: "Seleccionar idioma preferido",
  6: "Inicio",
  7: "Chat",
  8: "Reserva",
  9: "Cuenta",
  10: "Cambiar idioma",
  11: "Configure su idioma preferido",
  12: "Habilitar el modo oscuro",
  13: "Configura tu modo favorito",
  14: "Política de privacidad",
  15: "Conoce nuestra Política de Privacidad",
  16: "Ver perfil",
  17: "Cerrar sesión",
  18: "Finalizar la sesión",
  19: "Notificaciones",
  20: "Mucha información importante",
  21: "Nombre",
  22: "Ingrese su nombre",
  23: "Correo electrónico",
  24: "Ingrese su correo electrónico",
  25: "Número de teléfono",
  26: "Ingrese su número de teléfono",
  27: "Dirección",
  28: "Introduzca la dirección de los clientes",
  29: "Descripción",
  30: "Introduzca una breve descripción sobre usted",
  31: "GUARDAR",
  32: "Cambiar contraseña",
  33: "Nueva contraseña",
  34: "Ingresar contraseña",
  35: "Confirmar nueva contraseña",
  36: "Ingresar contraseña",
  37: "CAMBIAR CONTRASEÑA",
  38: "Mi perfil",
  39: "Todo sobre ti",
  40: "opiniones",
  41: "Leer todo",
  42: "Calificaciones promedio",
  43: "Iniciar sesión ahora",
  44: "Contraseña",
  45: "Ingrese su contraseña",
  46: "CONTINUAR",
  47: "REGISTRAR",
  48: "o continuar con",
  49: "Registrarse",
  50: "en menos de un minuto",
  51: "Confirmar contraseña",
  52: "Verificación",
  53: "Enviaremos el código de verificación",
  54: "Hemos enviado un código de verificación de 6 dígitos",
  55: "Introducir código",
  56: "Introduzca código de 6 dígitos",
  57: "Escribe tu mensaje ...",
  58: "Nuevo",
  59: "Aceptado",
  60: "En curso",
  61: "Completado",
  62: "Cancelado",
  63: "Reserva",
  64: "Llamar ahora",
  65: "Mensaje",
  66: "ID de reserva",
  67: "Nueva solicitud",
  68: "Reserva aceptada",
  69: "Aceptado el",
  70: "Iniciar un trabajo",
  71: "Programado el",
  72: "Trabajo completado",
  73: "El pago aparecerá aquí",
  74: "Precios",
  75: "Cantidad",
  76: "Importe de impuestos",
  77: "Total",
  78: "Solicitado el",
  79: "Pago",
  80: "Realizar pago",
  81: "Pago en efectivo",
  82: "Confirmar pago",
  83: "Revisión",
  84: "Dejar una reseña",
  85: "Chatear en línea",
  86: "Escribe tu reseña",
  87: "Cuéntanos algo sobre este servicio",
  88: "Haga clic en las estrellas para calificar este servicio",
  89: "Enviar revisión",
  90: "Agregar imágenes",
  91: "De la galería",
  92: "Desde la cámara",
  93: "Servicios a domicilio",
  94: "Encuentra lo que necesitas",
  95: "Servicio de búsqueda",
  96: "Notificar",
  97: "Duración",
  98: "min",
  99: "Este servicio puede tardar hasta",
  100: "Galerías",
  101: "Reseñas y valoraciones",
  102: "Reservar este servicio",
  103: "Tu dirección",
  104: "Agregar nuevo",
  105: "Pista",
  106: "¿Hay algo más?",
  107: "Código de cupón",
  108: "Aplicar",
  109: "En cualquier momento",
  110: "Programar un pedido",
  111: "Servicio solicitado en",
  112: "Seleccionar fecha y hora",
  113: "CONFIRMAR Y RESERVAR AHORA",
  114: "OK",
  115: "Su reserva ha sido enviada con éxito, recibirá una confirmación pronto.",
  116: "¡Gracias!",
  117: "Agregar dirección",
  118: "Mi casa",
  119: "Dirección completa",
  120: "Seleccionar dirección",
  121: "Elija aquí",
  122: "Buscar",
  123: "Lunes",
  124: "martes",
  125: "miércoles",
  126: "jueves",
  127: "Viernes",
  128: "sábado",
  129: "Domingo",
  130: "fijo",
  131: "por hora",
  132: "empezar desde",
  133: "Introduzca la dirección",
  134: "Seleccione la dirección",
  135: "Ingrese correo electrónico",
  136: "Introduzca la contraseña",
  137: "Usuario no encontrado",
  138: "El usuario no crea",
  139: "El correo electrónico es incorrecto",
  140: "Las contraseñas no son iguales",
  141: "El número de teléfono debe ser",
  142: "símbolos",
  143: "Código enviado. Por favor revise su teléfono para el código de verificación.",
  144: "Tiempo de espera",
  145: "Hoy",
  146: "Acerca de nosotros",
  147: "Conocenos",
  148: "Términos y condiciones",
  149: "Términos y condiciones conocidos",
  150: "No encontrado ...",
  151: "Ingrese Confirmar contraseña",
  152: "Contraseña cambiada",
  153: "Introduzca el nombre",
  154: "Datos guardados",
  155: "Proveedor",
  156: "Mensaje de chat",
  157: "Se llegó una nueva reserva",
  158: "Ahora estado:",
  159: "Se cambió el estado de la reserva",
  160: "Del usuario:",
  161: "Valora este servicio",
  162: "Cupón no encontrado",
  163: "Cupón activado",
  164: "Cupón no admitido por este proveedor",
  165: "El cupón no es compatible con esta categoría",
  166: "El cupón no es compatible con este servicio",
  167: "Cupón",
  168: "no",
  169: "El cupón ha caducado",
  170: "Tus favoritos",
  171: "Ver sus servicios favoritos",
  172: "Servicios principales",
  173: "El usuario está deshabilitado. Conéctese con el administrador para obtener más información",
  174: "Blog",
  175: "Ver todo",
  176: "Cargando ...",
  177: "Servicio",
  178: "¿Seguro que quieres salir?",
  179: "No",
  180: "Salir",
  181: "Filtro",
  182: "Ordenar por",
  183: "Ascendente (A-Z)",
  184: "Descendente (Z-A)",
  185: "Precio",
  186: "Restablecer filtro",
  187: "Aplicar filtro",
  188: "Mi dirección",
  189: "Dirección no encontrada",
  190: "Inicio",
  191: "Oficina",
  192: "Otro",
  193: "Establecer ubicación",
  194: "Encuentra servicios cercanos a tu",
  195: "Al permitir el acceso a la ubicación, puede buscar servicios y proveedores cerca de su.",
  196: "Usar ubicación de corrientes",
  197: "Establecer desde mapa",
  198: "Agregar la ubicación",
  199: "Etiquetar como",
  200: "Dirección de entrega",
  201: "Introducir dirección de entrega",
  202: "Nombre de contacto",
  203: "Ingrese el nombre del contacto",
  204: "Número de teléfono de contacto",
  205: "Ingrese el número de teléfono de contacto",
  206: "Guardar ubicación",
  207: "Latitud",
  208: "Longitud",
  209: "Por favor ingrese el teléfono",
  210: "por administrador",
  211: "por proveedor",
  212: "por cliente",
  213: "Introducir dirección",
  214: "Dirección actual",
  215: "Otras direcciones",
  216: "Ubicación",
  217: "Su dirección está fuera del área de trabajo del proveedor",
  218: "Ver detalles",
  219: "Solicitudes especiales",
  220: "Ubicación del proveedor",
  221: "Complementos",
  222: "Cerca de usted",
  223: "Lejos",
  224: "Proveedores",
  225: "Introduzca un código válido",
  226: "Tu número de teléfono verificado. No puedes editar el número de teléfono",
  227: "¿Olvidaste tu contraseña?",
  228: "Restablecer contraseña",
  229: "Enviar nueva contraseña",
  230: "Se envió el correo electrónico para restablecer la contraseña. Revise su correo",
  231: "Creación de tiempo",
  232: "ID de reserva",
  233: "Por favor ingrese texto",
  234: "Introduzca el código",
  235: "Subtotal",
  236: "Descuento",
  237: "Subcategoría",
  238: "Compartir esta aplicación",
  239: "Servicios cercanos",
  240: "Abrir página de proveedor",
  241: "Informe ...",
  242: "Bloquear usuario",
  243: "Bloquear",
  244: "No podrán enviarte mensajes. No podrás enviarles mensajes. No se les notificará que los bloqueaste",
  245: "Usuario",
  246: "Cancelar",
  247: "bloqueado",
  248: "¿Por qué denuncias a este usuario?",
  249: "Su denuncia es anónima, excepto si está denunciando una infracción de propiedad intelectual",
  250: "Gracias por hacérnoslo saber",
  251: "Sus comentarios son importantes para ayudarnos a mantener segura la comunidad",
  252: "Desbloquear",
  253: "Podrán enviarte mensajes. Tú podrás enviarles mensajes. No se les notificará que los desbloqueaste",
  254: "desbloqueado",
  255: "Sus proveedores favoritos",
  256: "Ver sus proveedores favoritos",
  257: "Proveedores favoritos",
  258: "Habilitar notificación",
  259: "No disponible ahora",
  260: "Servicios",
  261: "Productos de proveedor",
  262: "No disponible ahora",
  263: "Importe total",
  264: "Agregar al carrito",
  265: "Seleccione la variante",
  266: "en stock",
  267: "Producto añadido al carrito",
  268: "Carrito",
  269: "Mi carrito",
  270: "Continuar con el pago",
  271: "Tu carrito está vacío",
  272: "Precio del artículo",
  273: "Este servicio ya está en el carrito",
  274: "Este producto ya está en el carrito",
  275: "Servicio agregado al carrito",
  276: "IVA / IMPUESTOS",
  277: "Ver más",
  278: "Productos",
  279: "Buscar productos",
  280: "Ordenar por proveedor",
  281: "No seleccionar",
  282: "Productos relacionados",
  283: "Otros productos",
  284: "Reservando en",
  285: "Monto mínimo de compra para este proveedor: ",
  286: "Monto máximo de compra para este proveedor: ",
287: "Pagar con",
288: "El proveedor no puede ingresar a la aplicación del cliente. Utilice otras credenciales",
289: "Añadir promoción",
290: "Promoción no encontrada",
291: "Mis recompensas",
292: "Ingresar código",
293: "Oferta especial",
294: "Usar ahora",
295: "Válido hasta",
296: "Tu código de promoción",
297: "Aplicar código",
298: "El cupón no es compatible con este producto",
299: "Código de promoción",
300: "Eliminar",
};

Map<int, String> servicesFrench = {
  0 : "HANDYMAN",
  1 : "SERVICE",
  2 : "ENVOYER",
  3 : "Langue",
  4 : "Langue préférée",
  5 : "Sélectionner la langue préférée",
  6 : "Maison",
  7 : "Chat",
  8 : "Réservation",
  9 : "Compte",
  10 : "Changer de langue",
  11 : "Définir votre langue préférée",
  12 : "Activer le mode sombre",
  13 : "Définir votre mode préféré",
  14 : "Politique de confidentialité",
  15 : "Connaître notre politique de confidentialité",
  16 : "Voir le profil",
  17 : "Déconnexion",
  18 : "Terminer la session",
  19 : "Notifications",
  20 : "Beaucoup d'informations importantes",
  21 : "Nom",
  22 : "Entrez votre nom",
  23 : "Courriel",
  24 : "Entrez votre Email",
  25 : "Numéro de téléphone",
  26 : "Entrez votre numéro de téléphone",
  27 : "Adresse",
  28 : "Saisir l'adresse des clients",
  29 : "Description",
  30: "Entrez une brève description de vous",
  31 : "ENREGISTRER",
  32 : "Changer le mot de passe",
  33 : "Nouveau mot de passe",
  34 : "Entrer le mot de passe",
  35 : "Confirmer le nouveau mot de passe",
  36 : "Entrer le mot de passe",
  37 : "CHANGER MOT DE PASSE",
  38 : "Mon profil",
  39 : "Tout de toi",
  40 : "avis",
  41 : "Tout lire",
  42:"Notes moyennes",
  43 : "Connectez-vous maintenant",
  44 : "Mot de passe",
  45 : "Entrez votre mot de passe",
  46 : "CONTINUER",
  47 : "INSCRIPTION",
  48 : "ou continuer avec",
  49 : "S'inscrire",
  50 : "en moins d'une minute",
  51 : "Confirmer le mot de passe",
  52 : "Vérification",
  53: "Nous vous enverrons le code de vérification.",
  54: "Nous avons envoyé un code de vérification à 6 chiffres.",
  55 : "Entrez le code",
  56 : "Entrez le code à 6 chiffres",
  57 : "Ecrivez votre message...",
  58 : "Nouveau",
  59 : "Accepté",
  60 : "En cours",
  61 : "Terminé",
  62 : "Annulé",
  63 : "Réservation",
  64 : "Appeler maintenant",
  65 : "Message",
  66:"Identifiant de réservation ",
  67 : "Nouvelle demande",
  68 : "Réservation Acceptée",
  69 : "Accepté le",
  70 : "Démarrer un travail",
  71 : "Prévu le",
  72 : "Travail terminé",
  73 : "Le paiement apparaîtra ici",
  74 : "Tarification",
  75 : "Quantité",
  76 : "Montant de la taxe",
  77 : "Total",
  78 : "Demandé le",
  79 : "Paiement",
  80 : "Effectuer le paiement",
  81 : "Paiement comptant",
  82 : "Confirmer le paiement",
  83 : "Révision",
  84 : "Laisser un avis",
  85 : "Tchat en ligne",
  86 : "Ecrivez votre avis",
  87 : "Parlez-nous de ce service",
  88 : "Cliquez sur les étoiles pour noter ce service",
  89 : "Soumettre un avis",
  90 : "Ajouter des images",
  91 : "De la Galerie",
  92: "Depuis la caméra",
  93 : "Services à domicile",
  94 : "Trouvez ce dont vous avez besoin",
  95 : "Service de recherche",
  96 : "Notifier",
  97 : "Durée",
  98: "min",
  99 : "Ce service peut prendre jusqu'à",
  100 : "Galeries",
  101 : "Avis & Notes",
  102 : "Réservez ce service",
  103 : "Votre adresse",
  104 : "Ajouter nouveau",
  105 : "Indice",
  106 : "Y a-t-il autre chose",
  107:" Code de réduction ",
  108 : "Appliquer",
  109: "À tout moment",
  110 : "Planifier une Commande",
  111 : "Service demandé le",
  112 : "Sélectionnez une date et une heure",
  113 : "CONFIRMER & RÉSERVER MAINTENANT",
  114 : "D'accord",
  115 : "Votre réservation a été soumise avec succès, vous recevrez bientôt une confirmation.",
  116 : "Merci !",
  117 : "Ajouter une adresse",
  118 : "Ma Maison",
  119 : "Adresse complète",
  120 : "Choisir l'adresse",
  121 : "Choisir ici",
  122 : "Rechercher",
  123 : "Lundi",
  124 : "mardi",
  125 : "mercredi",
  126 : "Jeudi",
  127 : "Vendredi",
  128 : "samedi",
  129 : "Dimanche",
  130 : "fixe",
  131 : "horaire",
  132 : "à partir de",
  133 : "Veuillez saisir l'adresse",
  134 : "Veuillez sélectionner l'adresse",
  135 : "Veuillez entrer l'e-mail",
  136 : "Veuillez entrer le mot de passe",
  137 : "Utilisateur non trouvé",
  138 : "L'utilisateur ne crée pas",
  139 : "Les e-mails sont erronés",
  140 : "Les mots de passe ne sont pas égaux",
  141 : "Le numéro de téléphone doit être ",
  142 : "symboles",
  143 : "Code envoyé. Veuillez vérifier votre téléphone pour le code de vérification.",
  144 : "Temps mort",
  145 : "Aujourd'hui",
  146 : "À propos de nous",
  147 : "Connu de nous",
  148 : "Conditions Générales",
  149 : "Conditions Générales Connues",
  150 : "Non trouvé...",
  151 : "Entrer Confirmer Mot de Passe",
  152 : "Mot de passe modifié",
  153 : "Veuillez entrer le nom",
  154 : "Données sauvegardées",
  155 : "Fournisseur",
  156 : "Message de discussion",
  157 : "Nouvelle réservation arrivée",
  158 : "Actuellement état : ",
  159 : "Le statut de la réservation a été modifié",
  160 : "De l'utilisateur :",
  161 : "Évaluez ce service",
  162 : "Coupon non trouvé",
  163 : "Coupon activé",
  164 : "Coupon non pris en charge par ce fournisseur",
  165 : "Le coupon ne supporte pas cette catégorie",
  166 : "Le coupon ne prend pas en charge ce service",
  167 : "Coupon",
  168 : "non",
  169 : "Le coupon a expiré",
  170 : "Vos Favoris",
  171 : "Afficher vos services favoris",
  172 : "Top Services",
  173 : "L'utilisateur est désactivé. Connectez-vous à l'administrateur pour plus d'informations.",
  174 : "Blog",
  175 : "Voir tout",
  176 : "Chargement...",
  177 : "Service",
  178 : "Êtes-vous sûr de vouloir quitter?",
  179 : "Non",
  180 : "Sortie",
  181 : "Filtre",
  182 : "Trier par",
  183 : "Croissant (A-Z)",
  184 : "Descendant (Z-A)",
  185 : "Prix",
  186 : "Réinitialiser le filtre",
  187 : "Appliquer le filtre",
  188 : "Mon Adresse",
  189 : "Adresse non trouvée",
  190 : "Maison",
  191 : "Bureau",
  192 : "Autre",
  193 : "Définir l'emplacement",
  194 : "Trouvez des services près de chez vous",
  195 : "En autorisant l'accès à la localisation, vous pouvez rechercher des services et des fournisseurs à proximité de chez vous.",
  196 : "Utiliser la localisation des courants",
  197 : "Définir à partir de la carte",
  198 : "Ajouter l'emplacement",
  199 : "Étiqueter comme",
  200 : "Adresse de livraison",
  201 : "Entrer l'adresse de livraison",
  202 : "Nom du contact",
  203 : "Entrez le nom du contact",
  204 : "Numéro de téléphone à contacter",
  205 : "Entrez le numéro de téléphone du contact",
  206 : "Sauvegarder l'emplacement",
  207 : "Latitude",
  208 : "Longitude",
  209 : "Veuillez entrer le téléphone",
  210 : "par administrateur",
  211 : "par fournisseur",
  212 : "par client",
  213 : "Entrer l'adresse",
  214 : "Adresse actuelle",
  215 : "Autres adresses",
  216 : "Emplacement",
  217 : "Votre adresse est en dehors de la zone de travail du fournisseur",
  218 : "Voir détails",
  219 : "Demandes spéciales",
  220 : "Emplacement du fournisseur",
  221 : "Ajouts",
  222 : "A proximité",
  223 : "Loin",
  224 : "Fournisseurs",
  225 : "Veuillez saisir un code valide",
  226 : "Votre numéro de téléphone vérifié. Vous ne pouvez pas modifier le numéro de téléphone",
  227 : "Mot de passe oublié ?",
  228 : "Réinitialiser le mot de passe",
  229 : "Envoyer nouveau mot de passe",
  230 : "E-mail de réinitialisation du mot de passe envoyé. Veuillez vérifier votre messagerie.",
  231 : "Création du temps",
  232 : "Identifiant de réservation",
  233 : "Veuillez saisir du texte",
  234 : "Veuillez saisir le code",
  235 : "Sous-total",
  236 : "Réduction",
  237 : "Sous-catégorie",
  238 : "Partager cette application",
  239 : "Services à proximité",
  240 : "Ouvrir la page du fournisseur",
  241 : "Rapport...",
  242 : "Bloquer l'utilisateur",
  243 : "Bloquer",
  244 : "Ils ne pourront pas vous envoyer de message. Vous ne pourrez pas leur envoyer de message. Ils ne seront pas avertis que vous les avez bloqués. ",
  245 : "Utilisateur",
  246 : "Annuler",
  247 : "bloqué",
  248 : "Pourquoi signalez-vous cet utilisateur ?",
  249 : "Votre signalement est anonyme, sauf si vous signalez une atteinte à la propriété intellectuelle. ",
  250 : "Merci de nous l'avoir signalé",
  251 : "Vos commentaires sont importants pour nous aider à assurer la sécurité de la communauté. ",
  252 : "Débloquer",
  253 : "Ils pourront vous envoyer un message. Vous pourrez leur envoyer un message. Ils ne seront pas avertis que vous les avez débloqués. ",
  254 : "débloqué",
  255 : "Vos fournisseurs favoris",
  256 : "Afficher vos fournisseurs préférés",
  257 : "Fournisseurs favoris",
  258 : "Activer la notification",
  259 : "Non disponible maintenant",
  260 : "Prestations",
  261 : "Produits fournisseurs",
  262 : "Non disponible maintenant",
  263 : "Montant total",
  264 : "Ajouter au panier",
  265 : "Veuillez sélectionner une variante",
  266 : "en stock",
  267 : "Produit ajouté au panier",
  268 : "Chariot",
  269 : "Mon panier",
  270 : "Passer à la caisse",
  271 : "Votre panier est vide",
  272 : "Prix de l'article",
  273 : "Ce service déjà dans le panier",
  274 : "Ce produit déjà dans le panier",
  275 : "Service ajouté au panier",
  276 : "TVA/TAXE",
  277 : "Voir plus",
  278 : "Produits",
  279 : "Rechercher des produits",
  280 : "Trier par fournisseur",
  281 : "Ne pas sélectionner",
  282 : "Produits associés",
  283 : "Autres produits",
  284 : "Réservation à",
  285 : "Montant minimum d'achat pour ce prestataire : ",
  286 : "Montant d'achat maximum pour ce fournisseur : ",
  287 : "Payer avec",
  288 : "Le fournisseur ne peut pas accéder à l'application client. Veuillez utiliser d'autres informations d'identification.",
  289 : "Ajouter une promotion",
  290 : "Promotion introuvable",
  291 : "Mes récompenses",
  292 : "Saisir le code",
  293 : "Offre spéciale",
  294 : "Utiliser maintenant",
  295 : "Valable jusqu'au",
  296 : "Votre code promo",
  297 : "Appliquer le code",
  298 : "Le coupon ne prend pas en charge ce produit",
  299 : "Code promotionnel",
  300 : "Supprimer",
};

Map<int, String> servicesArabic = {
  0 : "HANDYMAN",
  1: "الخدمة" ,
  2: "إرسال" ,
  3: "اللغة" ,
  4: "اللغة المفضلة" ,
  5: "حدد اللغة المفضلة" ,
  6: "الصفحة الرئيسية" ,
  7: "الدردشة" ,
  8: "الحجز" ,
  9: "الحساب" ,
  10: "تغيير اللغة" ,
  11: "تعيين لغتك المفضلة" ,
  12: "تمكين الوضع الداكن" ,
  13: "تعيين الوضع المفضل لك" ,
  14: "سياسة الخصوصية" ,
  15: "تعرف على سياسة الخصوصية الخاصة بنا" ,
  16: "عرض الملف الشخصي",
  17: "تسجيل الخروج" ,
  18: "إنهاء الجلسة" ,
  19: "الإخطارات" ,
  20: "الكثير من المعلومات المهمة" ,
  21: "الاسم" ,
  22: "أدخل اسمك" ,
  23: "البريد الإلكتروني" ,
  24: "أدخل بريدك الإلكتروني" ,
  25: "رقم الهاتف" ,
  26: "أدخل رقم هاتفك" ,
  27: "العنوان" ,
  28: "أدخل عنوان العملاء" ,
  29: "الوصف" ,
  30: "أدخل وصفًا موجزًا ​​عنك" ,
  31: "حفظ" ,
  32: "تغيير كلمة المرور" ,
  33: "كلمة المرور الجديدة" ,
  34: "أدخل كلمة المرور" ,
  35: "تأكيد كلمة المرور الجديدة" ,
  36: "أدخل كلمة المرور" ,
  37: "تغيير كلمة المرور" ,
  38: "ملفي الشخصي" ,
  39: "كل شيء عنك" ,
  40: "مراجعات" ,
  41: "اقرأ الكل" ,
  42: "متوسط ​​التقييمات" ,
  43: "تسجيل الدخول الآن" ,
  44: "كلمة المرور" ,
  45: "أدخل كلمة المرور الخاصة بك" ,
  46: "متابعة" ,
  47: "تسجيل" ,
  48: "أو متابعة" ,
  49: "تسجيل" ,
  50: "في أقل من دقيقة" ,
  51: "تأكيد كلمة المرور" ,
  52: "التحقق" ,
  53: "سنرسل رمز التحقق." ,
  54: "لقد أرسلنا رمز التحقق المكون من 6 أرقام." ,
  55: "أدخل الرمز" ,
  56: "أدخل الرمز المكون من 6 أرقام" ,
  57: "اكتب رسالتك ..." ,
  58: "جديد" ,
  59: "مقبولة" ,
  60: "قيد التقدم" ,
  61: "مكتمل" ,
  62: "ملغاة",
  63: "الحجز" ,
  64: "اتصل الآن" ,
  65: "رسالة" ,
  66: "معرف الحجز" ,
  67: "طلب جديد" ,
  68: "الحجز مقبول" ,
  69: "تم القبول في" ,
  70: "بدء عمل" ,
  71: "مجدول في" ,
  72: "اكتملت الوظيفة" ,
  73: "سيظهر الدفع هنا" ,
  74: "التسعير" ,
  75: "الكمية" ,
  76: "مبلغ الضريبة" ,
  77: "المجموع" ,
  78: "مطلوب في" ,
  79: "الدفع" ,
  80: "إجراء الدفع" ,
  81: "الدفع النقدي" ,
  82: "تأكيد الدفع" ,
  83: "مراجعة" ,
  84: "اترك مراجعة" ,
  85: "الدردشة عبر الإنترنت" ,
  86: "اكتب رأيك" ,
  87: "أخبرنا شيئًا عن هذه الخدمة" ,
  88: "اضغط على النجوم لتقييم هذه الخدمة" ,
  89: "إرسال مراجعة" ,
  90: "إضافة صور" ,
  91: "من المعرض" ,
  92: "من الكاميرا" ,
  93: "خدمات منزلية" ,
  94: "اعثر على ما تحتاجه" ,
  95: "خدمة البحث" ,
  96: "إعلام" ,
  97: "المدة" ,
  98: "دقيقة" ,
  99: "يمكن أن تستغرق هذه الخدمة ما يصل إلى" ,
  100: "المعارض" ,
  101: "التعليقات والتقييمات" ,
  102: "حجز هذه الخدمة" ,
  103: "عنوانك" ,
  104: "إضافة جديد" ,
  105: "تلميح" ,
  106: "هل هناك شيء آخر" ,
  107: "رمز القسيمة" ,
  108: "تطبيق" ,
  109: "في أي وقت" ,
  110: "جدولة طلب" ,
  111: "الخدمة المطلوبة في" ,
  112: "حدد التاريخ والوقت" ,
  113: "تأكيد وحجز الآن" ,
  114: "حسنًا" ,
  115: "تم تقديم حجزك بنجاح , ستتلقى تأكيدًا قريبًا.",
  116: "شكرا لك!" ,
  117: "إضافة عنوان" ,
  118: "بيتي" ,
  119: "العنوان الكامل" ,
  120: "حدد العنوان" ,
  121: "اختر هنا" ,
  122: "بحث" ,
  123: "الاثنين" ,
  124: "الثلاثاء" ,
  125: "الأربعاء" ,
  126: "الخميس" ,
  127: "الجمعة" ,
  128: "السبت" ,
  129: "الأحد" ,
  130: "ثابت" ,
  131: "كل ساعة" ,
  132: "البدء من",
  133: "الرجاء إدخال العنوان" ,
  134: "الرجاء تحديد العنوان" ,
  135: "الرجاء إدخال البريد الإلكتروني" ,
  136: "الرجاء إدخال كلمة المرور" ,
  137: "المستخدم غير موجود" ,
  138: "المستخدم لا ينشئ" ,
  139: "البريد الإلكتروني خاطئ" ,
  140: "كلمات المرور غير متساوية" ,
  141: "يجب أن يكون رقم الهاتف" ,
  142: "الرموز" ,
  143: "تم إرسال الرمز. يرجى التحقق من هاتفك بحثًا عن رمز التحقق." ,
  144: "انتهى الوقت" ,
  145: "اليوم" ,
  146: "نبذة عنا" ,
  147: "معروف عنا" ,
  148: "الشروط والأحكام" ,
  149: "الشروط والأحكام المعروفة" ,
  150: "غير موجود ..." ,
  151: "أدخل تأكيد كلمة المرور" ,
  152: "تم تغيير كلمة المرور" ,
  153: "الرجاء إدخال الاسم" ,
  154: "البيانات المحفوظة" ,
  155: "مقدم" ,
  156: "رسالة دردشة" ,
  157: "وصل حجز جديد" ,
  158: "الوضع الآن:" ,
  159: "تم تغيير حالة الحجز" ,
  160: "من المستخدم:" ,
  161: "قيم هذه الخدمة",
  162: "القسيمة غير موجودة",
  163: "القسيمة نشطة",
  164: "قسيمة غير مدعومة من قبل هذا الموفر" ,
  165: "قسيمة لا تدعم هذه الفئة" ,
  166: "قسيمة لا تدعم هذه الخدمة" ,
  167: "قسيمة" ,
  168: "لا" ,
  169: "القسيمة انتهت صلاحيتها" ,
  170: "مفضلاتك" ,
  171: "عرض خدماتك المفضلة" ,
  172: "أفضل الخدمات" ,
  173: "تم تعطيل المستخدم. اتصل بالمسؤول للحصول على مزيد من المعلومات.",
  174: "مدونة" ,
  175: "عرض الكل" ,
  176: "جارٍ التحميل ..." ,
  177: "الخدمة" ,
  178: "هل أنت متأكد أنك تريد الخروج؟" ,
  179: "لا" ,
  180: "خروج" ,
  181: "تصفية" ,
  182: "فرز حسب",
  183: "تصاعدي (أ-ي)" ,
  184: "تنازلي (ي - أ)" ,
  185: "السعر" ,
  186: "إعادة تعيين عامل التصفية" ,
  187: "تطبيق الفلتر" ,
  188: "عنواني" ,
  189: "لم يتم العثور على العنوان" ,
  190: "الصفحة الرئيسية" ,
  191: "مكتب" ,
  192: "أخرى" ,
  193: "تعيين الموقع" ,
  194: "البحث عن خدمات بالقرب منك" ,
  195: "بالسماح بالوصول إلى الموقع , يمكنك البحث عن الخدمات والموفرين بالقرب منك." ,
  196: "استخدام موقع التيارات" ,
  197: "تعيين من الخريطة" ,
  198: "أضف الموقع" ,
  199: "تصنيف كـ" ,
  200: "عنوان التسليم" ,
  201: "أدخل عنوان التسليم" ,
  202: "اسم جهة الاتصال" ,
  203: "أدخل اسم جهة الاتصال" ,
  204: "رقم هاتف الاتصال" ,
  205: "أدخل رقم هاتف جهة الاتصال" ,
  206: "حفظ الموقع" ,
  207: "Latitude" ,
  208: "خط الطول" ,
  209: "الرجاء إدخال الهاتف" ,
  210: "بواسطة المسؤول",
  211: "حسب المزود",
  212: "حسب الزبون",
  213: "أدخل العنوان" ,
  214: "العنوان الحالي" ,
  215: "عناوين أخرى" ,
  216: "الموقع" ,
  217: "عنوانك خارج منطقة عمل المزود" ,
  218: "انظر التفاصيل" ,
  219: "الطلبات الخاصة" ,
  220: "موقع المزود" ,
  221: "الإضافات" ,
  222: "بالقرب منك" ,
  223: "بعيد" ,
  224: "الموفرون" ,
  225: "الرجاء إدخال رمز صالح" ,
  226: "تم التحقق من رقم هاتفك. لا يمكنك تعديل رقم الهاتف" ,
  227: "هل نسيت كلمة المرور؟" ,
  228: "إعادة تعيين كلمة المرور" ,
  229: "إرسال كلمة مرور جديدة" ,
  230: "تم إرسال البريد الإلكتروني لإعادة تعيين كلمة المرور. يرجى التحقق من بريدك.",
  231: "إنشاء الوقت" ,
  232: "معرف الحجز" ,
  233: "الرجاء إدخال نص" ,
  234: "الرجاء إدخال الرمز" ,
  235: "المجموع الفرعي" ,
  236: "خصم" ,
  237: "فئة فرعية" ,
  238: "مشاركة هذا التطبيق" ,
  239: "خدمات قريبة" ,
  240: "فتح صفحة الموفر" ,
  241: "تقرير ..." ,
  242: "حظر المستخدم" ,
  243: "بلوك" ,
  244: "لن يتمكنوا من مراسلتك. لن تتمكن من مراسلتهم. لن يتم إخطارهم بأنك حظرتهم." ,
  245: "المستخدم" ,
  246: "إلغاء" ,
  247: "ممنوع",
  248: "لماذا تبلغ عن هذا المستخدم؟" ,
  249: "التقرير الخاص بك مجهول , إلا إذا كنت تقوم بالإبلاغ عن انتهاك للملكية الفكرية." ,
  250: "شكرًا لإعلامنا" ,
  251: "ملاحظاتك مهمة في مساعدتنا في الحفاظ على المجتمع آمنًا.",
  252: "إلغاء الحظر" ,
  253: "يمكنهم مراسلتك. يمكنك مراسلتهم. لن يتم إعلامهم بأنك قمت بإلغاء حظرهم." ,
  254: "غير محظور",
  255: "مزودو الخدمات المفضلون" ,
  256: "عرض مقدمي الخدمات المفضلة لديك" ,
  257: "المزودون المفضلون" ,
  258: "تمكين الإعلام" ,
  259: "غير متوفر الآن" ,
  260: "الخدمات" ,
  261: "منتجات الموفر" ,
  262: "غير متوفر الآن" ,
  263: "المبلغ الإجمالي" ,
  264: "إضافة إلى عربة التسوق" ,
  265: "الرجاء تحديد البديل" ,
  266: "متوفر",
  267: "تمت إضافة المنتج إلى سلة التسوق" ,
  268: "العربة" ,
  269: "عربتي" ,
  270: "تابع الدفع" ,
  271: "عربة التسوق الخاصة بك فارغة" ,
  272: "سعر السلعة" ,
  273: "هذه الخدمة موجودة بالفعل في عربة التسوق" ,
  274: "هذا المنتج موجود بالفعل في سلة التسوق" ,
  275: "تمت إضافة الخدمة إلى سلة التسوق" ,
  276: "ضريبة القيمة المضافة / الضرائب" ,
  277: "مشاهدة المزيد" ,
  278: "المنتجات" ,
  279: "البحث عن المنتجات" ,
  280: "فرز حسب الموفر",
  281: "لم تحدد" ,
  282: "منتجات ذات صلة" ,
  283: "منتجات أخرى" ,
  284: "الحجز في" ,
  285: "الحد الأدنى لمبلغ الشراء لهذا الموفر:" ,
  286: "الحد الأقصى لمبلغ الشراء لهذا الموفر:" ,
  287: "الدفع باستخدام" ,
  288: "لا يمكن للموفر الدخول إلى تطبيق العميل. الرجاء استخدام بيانات اعتماد أخرى.",
  289: "إضافة عرض ترويجي",
  290: "لم يتم العثور على العرض الترويجي" ,
  291: "مكافآتي" ,
  292: "أدخل الرمز" ,
  293: "عرض خاص" ,
  294: "استخدم الآن" ,
  295: "صالح حتى" ,
  296: "رمزك الترويجي" ,
  297: "تطبيق الرمز" ,
  298: "قسيمة لا تدعم هذا المنتج" ,
  299: "الرمز الترويجي" ,
  300: "إزالة" ,
};

Map<int, String> servicesPort = {
  0 : "HANDYMAN",
  1: "SERVIÇO",
  2: "ENVIAR",
  3: "Idioma",
  4: "Idioma preferido",
  5: "Selecione o idioma preferido",
  6: "Casa",
  7: "Bate-papo",
  8: "Reserva",
  9: "Conta",
  10: "Alterar idioma",
  11: "Defina seu idioma preferido",
  12: "Ativar modo escuro",
  13: "Definir seu modo favorito",
  14: "Política de Privacidade",
  15: "Conhecemos nossa Política de Privacidade",
  16: "Ver perfil",
  17: "Sair",
  18: "Encerrar a sessão",
  19: "Notificações",
  20: "Muitas informações importantes",
  21: "Nome",
  22: "Digite seu nome",
  23: "Email",
  24: "Digite seu e-mail",
  25: "Número de telefone",
  26: "Digite o seu número de telefone",
  27: "Endereço",
  28: "Insira o endereço dos clientes",
  29: "Descrição",
  30: "Insira uma breve descrição sobre você",
  31: "SALVAR",
  32: "Alterar senha",
  33: "Nova senha",
  34: "Digite a senha",
  35: "Confirme a nova senha",
  36: "Digite a senha",
  37: "ALTERAR SENHA",
  38: "Meu Perfil",
  39: "Tudo sobre você",
  40: "resenhas",
  41: "Ler tudo",
  42: "Avaliações médias",
  43: "Faça login agora",
  44: "Senha",
  45: "Digite sua senha",
  46: "CONTINUAR",
  47: "CADASTRE-SE",
  48: "ou continue com",
  49: "Registre-se",
  50: "em menos de um minuto",
  51: "Confirmar senha",
  52: "Verificação",
  53: "Enviaremos o código de verificação.",
  54: "Enviamos um código de verificação de 6 dígitos.",
  55: "Insira o código",
  56: "Insira o código de 6 dígitos",
  57: "Escreva sua mensagem ...",
  58: "Novo",
  59: "Aceito",
  60: "Em andamento",
  61: "Concluído",
  62: "Cancelado",
  63: "Reserva",
  64: "Ligue agora",
  65: "Mensagem",
  66: "ID de reserva",
  67: "Novo Pedido",
  68: "Reserva aceita",
  69: "Aceito em",
  70: "Começar um trabalho",
  71: "Programado em",
  72: "Trabalho concluído",
  73: "O pagamento aparecerá aqui",
  74: "Preços",
  75: "Quantidade",
  76: "Valor do imposto",
  77: "Total",
  78: "Solicitado em",
  79: "Pagamento",
  80: "Efetue o pagamento",
  81: "Pagamento em dinheiro",
  82: "Confirmar Pagamento",
  83: "Revisão",
  84: "Deixe um comentário",
  85: "Conversando online",
  86: "Escreva seu comentário",
  87: "Conte-nos algo sobre este serviço",
  88: "Clique nas estrelas para avaliar este serviço",
  89: "Enviar avaliação",
  90: "Adicionar Imagens",
  91: "Da Galeria",
  92: "Da câmera",
  93: "Serviços domésticos",
  94: "Encontre o que você precisa",
  95: "Serviço de pesquisa",
  96: "Notificar",
  97: "Duração",
  98: "min",
  99: "Este serviço pode levar até",
  100: "Galerias",
  101: "Críticas e avaliações",
  102: "Reservar este serviço",
  103: "Seu endereço",
  104: "Adicionar novo",
  105: "Dica",
  106: "Há mais alguma coisa",
  107: "Código do cupom",
  108: "Aplicar",
  109: "Qualquer hora",
  110: "Agendar um pedido",
  111: "Serviço Solicitado em",
  112: "Selecione uma data e hora",
  113: "CONFIRMAR E RESERVAR AGORA",
  114: "OK",
  115: "Sua reserva foi enviada com sucesso, você receberá uma confirmação em breve.",
  116: "Obrigado!",
  117: "Adicionar Endereço",
  118: "Minha Casa",
  119: "Endereço completo",
  120: "Selecionar endereço",
  121: "Escolha aqui",
  122: "Pesquisar",
  123: "segunda-feira",
  124: "terça-feira",
  125: "quarta-feira",
  126: "quinta-feira",
  127: "sexta-feira",
  128: "sábado",
  129: "domingo",
  130: "fixo",
  131: "de hora em hora",
  132: "começar de",
  133: "Por favor, insira o endereço",
  134: "Selecione o endereço",
  135: "Digite o e-mail",
  136: "Digite a senha",
  137: "Usuário não encontrado",
  138: "O usuário não cria",
  139: "Email está errado",
  140: "As senhas não são iguais",
  141: "O número do telefone deve ser",
  142: "símbolos",
  143: "Código enviado. Verifique o código de verificação em seu telefone.",
  144: "Tempo Limite",
  145: "Hoje",
  146: "Sobre nós",
  147: "Conhecidos sobre nós",
  148: "Termos e Condições",
  149: "Termos e Condições Conhecidos",
  150: "Não encontrado ...",
  151: "Digite a senha de confirmação",
  152: "Senha alterada",
  153: "Digite o nome",
  154: "Dados salvos",
  155: "Provedor",
  156: "Mensagem de bate-papo",
  157: "Nova reserva foi recebida",
  158: "Status agora:",
  159: "O status da reserva foi alterado",
  160: "Do usuário:",
  161: "Avalie este serviço",
  162: "Cupom não encontrado",
  163: "Cupom ativado",
  164: "Cupom não suportado por este provedor",
  165: "O cupom não é compatível com esta categoria",
  166: "O cupom não é compatível com este serviço",
  167: "Cupom",
  168: "não",
  169: "O cupom expirou",
  170: "Seus favoritos",
  171: "Ver seus serviços favoritos",
  172: "Principais serviços",
  173: "O usuário está desabilitado. Conecte-se ao Administrador para obter mais informações.",
  174: "Blog",
  175: "Ver todos",
  176: "Carregando ...",
  177: "Serviço",
  178: "Tem certeza que deseja sair?",
  179: "Não",
  180: "Sair",
  181: "Filtro",
  182: "Classificar por",
  183: "Ascendente (A-Z)",
  184: "Descendente (Z-A)",
  185: "Preço",
  186: "Reiniciar Filtro",
  187: "Aplicar filtro",
  188: "Meu endereço",
  189: "Endereço não encontrado",
  190: "Casa",
  191: "Escritório",
  192: "Outro",
  193: "Definir localização",
  194: "Encontre serviços perto de",
  195: "Ao permitir o acesso à localização, você pode pesquisar serviços e provedores próximos ao seu.",
  196: "Usar localização de correntes",
  197: "Definir do mapa",
  198: "Adicionar o local",
  199: "Marcar como",
  200: "Endereço de entrega",
  201: "Insira o endereço de entrega",
  202: "Nome do contato",
  203: "Insira o nome do contato",
  204: "Número de telefone do contato",
  205: "Insira o número de telefone do contato",
  206: "Salvar local",
  207: "Latitude",
  208: "Longitude",
  209: "Por favor, insira o telefone",
  210: "pelo administrador",
  211: "por provedor",
  212: "por cliente",
  213: "Insira o endereço",
  214: "Endereço atual",
  215: "Outros endereços",
  216: "Localização",
  217: "Seu endereço está fora da área de trabalho do provedor",
  218: "Ver detalhes",
  219: "Pedidos Especiais",
  220: "Local do Provedor",
  221: "Complementos",
  222: "Perto de você",
  223: "Longe",
  224: "Provedores",
  225: "Por favor, insira um código válido",
  226: "Seu número de telefone verificado. Você não pode editar o número de telefone",
  227: "Esqueceu a senha?",
  228: "Redefinir senha",
  229: "Enviar nova senha",
  230: "Email de redefinição de senha enviado. Verifique seu e-mail.",
  231: "Criação de hora",
  232: "ID de reserva",
  233: "Por favor, insira o texto",
  234: "Por favor, insira o código",
  235: "Subtotal",
  236: "Desconto",
  237: "Subcategoria",
  238: "Compartilhe este aplicativo",
  239: "Serviços próximos",
  240: "Abrir página do provedor",
  241: "Relatório ...",
  242: "Bloquear usuário",
  243: "Bloquear",
  244: "Eles não poderão enviar mensagens para você. Você não poderá enviá-los. Eles não serão notificados de que você os bloqueou.",
  245: "Usuário",
  246: "Cancelar",
  247: "bloqueado",
  248: "Por que você está denunciando este usuário?",
  249: "Sua denúncia é anônima, exceto se você estiver denunciando uma violação de propriedade intelectual.",
  250: "Obrigado por nos informar",
  251: "Seu feedback é importante para nos ajudar a manter a comunidade segura.",
  252: "Desbloquear",
  253: "Eles poderão enviar mensagens para você. Você poderá enviar mensagens para eles. Eles não serão notificados de que você os desbloqueou.",
  254: "desbloqueado",
  255: "Seus provedores favoritos",
  256: "Ver seus provedores favoritos",
  257: "Provedores favoritos",
  258: "Habilitar Notificar",
  259: "Não disponível agora",
  260: "Serviços",
  261: "Produtos do fornecedor",
  262: "Não disponível agora",
  263: "Montante total",
  264: "Adicionar ao carrinho",
  265: "Selecione a variante",
  266: "em estoque",
  267: "Produto adicionado ao carrinho",
  268: "Carrinho",
  269: "Meu carrinho",
  270: "Prossiga para a finalização da compra",
  271: "Seu carrinho está vazio",
  272: "Preço do item",
  273: "Este serviço já está no carrinho",
  274: "Este produto já está no carrinho",
  275: "Serviço adicionado ao carrinho",
  276: "VAT / TAX",
  277: "Ver mais",
  278: "Produtos",
  279: "Pesquisar produtos",
  280: "Classificar por provedor",
  281: "Não selecionar",
  282: "Produtos relacionados",
  283: "Outros produtos",
  284: "Reserva em",
  285 : "Valor mínimo de compra para este provedor: ",
  286 : "Valor máximo de compra para este provedor: ",
  287 : "Pagar com",
  288 : "O provedor não pode entrar no aplicativo do cliente. Use outras credenciais.",
  289 : "Adicionar promoção",
  290 : "Promoção não encontrada",
  291 : "Minhas recompensas",
  292 : "Digite o código",
  293 : "Oferta especial",
  294 : "Usar agora",
  295 : "Válido até",
  296 : "Seu código promocional",
  297 : "Aplicar código",
  298 : "Cupom não compatível com este produto",
  299 : "Código promocional",
  300 : "Remover",
};

Map<int, String> servicesRus = {
  0 : "HANDYMAN",
  1: "СЕРВИС",
  2: "ОТПРАВИТЬ",
  3: "Язык",
  4: "Предпочитаемый язык",
  5: "Выберите предпочтительный язык",
  6: "Дом",
  7: "Чат",
  8: "Бронирование",
  9: "Учетная запись",
  10: "Сменить язык",
  11: "Установите предпочитаемый язык",
  12: "Включить темный режим",
  13: "Установите любимый режим",
  14: "Политика конфиденциальности",
  15: "Известная наша Политика конфиденциальности",
  16: "Просмотреть профиль",
  17: "Выйти",
  18: "Завершить сеанс",
  19: "Уведомления",
  20: "Много важной информации",
  21: "Имя",
  22: "Введите свое имя",
  23: "Электронная почта",
  24: "Введите свой адрес электронной почты",
  25: "Номер телефона",
  26: "Введите свой номер телефона",
  27: "Адрес",
  28: "Введите адрес для клиентов",
  29: "Описание",
  30: "Введите краткое описание о себе",
  31: "СОХРАНИТЬ",
  32: "Сменить пароль",
  33: "Новый пароль",
  34: "Введите пароль",
  35: "Подтвердите новый пароль",
  36: "Введите пароль",
  37: "ИЗМЕНИТЬ ПАРОЛЬ",
  38: "Мой профиль",
  39: "Все о тебе",
  40: "отзывы",
  41: "Читать все",
  42: "Средний рейтинг",
  43: "Войти сейчас",
  44: "Пароль",
  45: "Введите пароль",
  46: "ПРОДОЛЖИТЬ",
  47: "РЕГИСТРАЦИЯ",
  48: "или продолжить с",
  49: "Регистр",
  50: "менее чем за минуту",
  51: "Подтвердите пароль",
  52: "Проверка",
  53: "Мы отправим проверочный код.",
  54: "Мы отправили шестизначный проверочный код.",
  55: "Введите код",
  56: "Введите шестизначный код",
  57: "Напишите свое сообщение ...",
  58: "Новый",
  59: "Принято",
  60: "В процессе",
  61: "Завершено",
  62: "Отменено",
  63: "Бронирование",
  64: "Звоните сейчас",
  65: "Сообщение",
  66: "Идентификатор бронирования",
  67: "Новый запрос",
  68: "Бронирование принято",
  69: "Принято",
  70: "Начать работу",
  71: "По расписанию",
  72: "Работа завершена",
  73: "Платеж появится здесь",
  74: "Цены",
  75: "Количество",
  76: "Сумма налога",
  77: "Итого",
  78: "Запрошено",
  79: "Оплата",
  80: "Произвести оплату",
  81: "Наличный расчет",
  82: "Подтвердить платеж",
  83: "Обзор",
  84: "Оставить отзыв",
  85: "Общение в чате",
  86: "Напишите свой отзыв",
  87: "Расскажите что-нибудь об этой услуге",
  88: "Нажмите на звездочки, чтобы оценить эту услугу",
  89: "Отправить обзор",
  90: "Добавить изображения",
  91: "Из галереи",
  92: "С камеры",
  93: "Бытовые услуги",
  94: "Найди то, что тебе нужно",
  95: "Служба поиска",
  96: "Уведомить",
  97: "Продолжительность",
  98: "мин",
  99: "Эта услуга может занять до",
  100: "Галереи",
  101: "Обзоры и оценки",
  102: "Забронировать эту услугу",
  103: "Ваш адрес",
  104: "Добавить",
  105: "Подсказка",
  106: "Есть что-нибудь еще",
  107: "Код купона",
  108: "Применить",
  109: "В любое время",
  110: "Запланировать заказ",
  111: "Запрошенная услуга включена",
  112: "Выберите дату и время",
  113: "ПОДТВЕРДИТЬ И БРОНИРОВАТЬ СЕЙЧАС",
  114: "ОК",
  115: "Ваше бронирование было успешно отправлено, вскоре вы получите подтверждение.",
  116: "Спасибо!",
  117: "Добавить адрес",
  118: "Мой дом",
  119: "Полный адрес",
  120: "Выбрать адрес",
  121: "Выберите здесь",
  122: "Поиск",
123: "Понедельник",
124: "Вторник",
125: "Среда",
126: "Четверг",
127: "Пятница",
128: "Суббота",
129: "Воскресенье",
130: "фиксированный",
131: "ежечасно",
132: "начать с",
133: "Пожалуйста, введите адрес",
134: "Пожалуйста, выберите адрес",
135: "Пожалуйста, введите адрес электронной почты",
136: "Пожалуйста, введите пароль",
137: "Пользователь не найден",
138: "Пользователь не создает",
139: "Неправильный адрес электронной почты",
140: "Пароли не равны",
141: "Номер телефона должен быть",
142: "символы",
143: "Код отправлен. Проверьте свой телефон на наличие кода подтверждения.",
144: "Тайм-аут",
145: "Сегодня",
146: "О нас",
147: "О нас известно",
148: "Положения и условия",
149: "Известные положения и условия",
150: "Не найдено ...",
151: "Введите пароль для подтверждения",
152: "Пароль изменен",
153: "Пожалуйста, введите имя",
154: "Данные сохранены",
155: "Провайдер",
156: "Сообщение чата",
157: "Прибыло новое бронирование",
158: "Сейчас статус:",
159: "Статус бронирования изменен",
160: "От пользователя:",
161: "Оцените эту услугу",
162: "Купон не найден",
163: "Купон активирован",
164: "Купон не поддерживается этим поставщиком",
165: "Купон не поддерживает эту категорию",
166: "Купон не поддерживает эту услугу",
167: "Купон",
168: "нет",
169: "Срок действия купона истек",
  170: "Ваши фавориты",
  171: "Посмотреть любимые сервисы",
  172: "Лучшие услуги",
173: "Пользователь отключен. Для получения дополнительной информации обратитесь к администратору.",
174: "Блог",
175: "Посмотреть все",
176: "Загрузка ...",
177: "Сервис",
178: "Вы уверены, что хотите выйти?",
179: "Нет",
180: "Выход",
181: "Фильтр",
182: "Сортировать по",
183: "По возрастанию (A – Z)",
184: "По убыванию (Z-A)",
185: "Цена",
186: "Сбросить фильтр",
187: "Применить фильтр",
188: "Мой адрес",
189: "Адрес не найден",
190: "Дом",
191: "Офис",
192: "Другое",
193: "Установить местоположение",
194: "Найдите услуги рядом с вашим",
195: "Разрешив доступ к местоположению, вы можете искать услуги и поставщиков рядом с вашим.",
196: "Использование токов локации",
197: "Установить по карте",
198: "Добавить местоположение",
199: "Отметить как",
200: "Адрес доставки",
201: "Введите адрес доставки",
202: "Контактное лицо",
203: "Введите имя контакта",
204: "Контактный телефон",
205: "Введите номер контактного телефона",
206: "Сохранить местоположение",
207: "Широта",
208: "Долгота",
209: "Пожалуйста, введите телефон",
210: "администратором",
211: "по провайдеру",
212: "по заказчику",
213: "Введите адрес",
214: "Текущий адрес",
215: "Другие адреса",
216: "Местоположение",
217: "Ваш адрес находится за пределами рабочей зоны провайдера",
218: "Подробнее",
219: "Особые запросы",
220: "Местоположение поставщика",
221: "Дополнения",
222: "Рядом с вами",
223: "Далеко",
224: "Провайдеры",
225: "Пожалуйста, введите действительный код",
226: "Ваш номер телефона подтвержден. Вы не можете редактировать номер телефона",
227: "Забыли пароль?",
228: "Сбросить пароль",
229: "Отправить новый пароль",
230: "Письмо для сброса пароля отправлено. Проверьте почту.",
  231: "Время творения",
  232: "Идентификатор бронирования",
  233: "Пожалуйста, введите текст",
234: "Пожалуйста, введите код",
235: "Итого",
236: "Скидка",
  237: "Подкатегория",
  238: "Поделиться этим приложением",
  239: "Услуги рядом",
  240: "Открыть страницу поставщика",
241: "Сообщить ...",
242: "Заблокировать пользователя",
243: "Блок",
244: "Они не смогут отправлять вам сообщения. Вы не сможете отправлять им сообщения. Они не будут уведомлены о том, что вы их заблокировали.",
245: "Пользователь",
246: "Отменить",
247: "заблокировано",
248: "Почему вы жалуетесь на этого пользователя?",
249: "Ваше сообщение является анонимным, кроме случаев, когда вы сообщаете о нарушении прав интеллектуальной собственности",
250: "Спасибо, что сообщили нам",
251: "Ваш отзыв важен для того, чтобы помочь нам сохранить безопасность сообщества",
252: "Разблокировать",
253: "Они смогут отправлять вам сообщения. Вы можете отправлять им сообщения. Они не будут уведомлены о том, что вы их разблокировали.",
254: "разблокировано",
  255: "Ваши любимые провайдеры",
  256: "Посмотреть любимых провайдеров",
  257: "Любимые провайдеры",
  258: "Включить уведомление",
  259: "Сейчас недоступно",
  260: "Услуги",
261: "Продукты поставщика",
262: "Сейчас недоступно",
263: "Общая сумма",
264: "В корзину",
265: "Выберите вариант",
266: "в наличии",
267: "Товар добавлен в корзину",
268: "Тележка",
269: "Моя корзина",
270: "Перейти к оформлению заказа",
271: "Ваша корзина пуста",
272: "Цена товара",
273: "Эта услуга уже в корзине",
274: "Этот товар уже в корзине",
275: "Услуга добавлена в корзину",
276: "НДС / НАЛОГ",
277: "Узнать больше",
278: "Продукты",
279: "Искать продукты",
280: "Сортировать по провайдеру",
281: "Не выбрать",
282: "Сопутствующие товары",
283: "Прочие товары",
284: "Бронирование в",
  285 : "Минимальная сумма покупки для этого провайдера: ",
  286 : "Максимальная сумма покупки для этого провайдера: ",
  287 : "Оплатить",
  288 : "Поставщик не может войти в клиентское приложение. Пожалуйста, используйте другие учетные данные.",
  289 : "Добавить промо",
  290 : "Промо не найдено",
  291: "Мои награды",
  292 : "Введите код",
  293 : "Специальное предложение",
  294: "Использовать сейчас",
  295 : "Действителен до",
  296 : "Ваш промокод",
  297 : "Применить код",
  298 : "Купон не поддерживает этот продукт",
  299 : "Промокод",
  300 : "Удалить",
};

Map<int, String> servicesHindi = {
  0 : "HANDYMAN",
  1: "सेवा",
  2: "सबमिट करें",
  3: "भाषा",
  4: "पसंदीदा भाषा",
  5: "पसंदीदा भाषा चुनें",
  6: "होम",
  7: "चैट",
  8: "बुकिंग",
  9: "खाता",
  10: "भाषा बदलें",
  11: "अपनी पसंदीदा भाषा सेट करें",
  12: "डार्क मोड सक्षम करें",
  13: "आप पसंदीदा मोड सेट करें",
  14: "गोपनीयता नीति",
  15: "हमारी गोपनीयता नीति को जानें",
  16: "प्रोफाइल देखें",
  17: "लॉग आउट",
  18: "सत्र समाप्त करें",
  19: "सूचनाएं",
  20: "बहुत सारी महत्वपूर्ण जानकारी",
  21: "नाम",
  22: "अपना नाम दर्ज करें",
  23: "ईमेल",
  24: "अपना ईमेल दर्ज करें",
  25: "फोन नंबर",
  26: "अपना फोन नंबर दर्ज करें",
  27: "पता",
  28: "ग्राहकों के लिए पता दर्ज करें",
  29: "विवरण",
  30: "अपने बारे में संक्षिप्त विवरण दर्ज करें",
  31: "बचाओ",
  32: "पासवर्ड बदलें",
  33: "नया पासवर्ड",
  34: "पासवर्ड दर्ज करें",
  35 : "नए पासवर्ड की पुष्टि करें",
  36: "पासवर्ड दर्ज करें",
  37: "पासवर्ड बदलें",
  38: "माई प्रोफाइल",
  39: "आपके बारे में सब कुछ",
  40: "समीक्षाएं",
  41: "सभी पढ़ें",
  42: "औसत रेटिंग",
  43 : "अभी साइन इन करें",
  44: "पासवर्ड",
  45: "अपना पासवर्ड दर्ज करें",
  46: "जारी रखें",
  47: "रजिस्टर",
  48: "या जारी रखें",
  49: "रजिस्टर",
  50: "एक मिनट से भी कम समय में",
  51: "पासवर्ड की पुष्टि करें",
  52: "सत्यापन",
  53 : "हम सत्यापन कोड भेजेंगे।",
  54 : "हमने ६ अंकों का सत्यापन कोड भेजा है।",
  55: "कोड दर्ज करें",
  56: "6 अंकों का कोड दर्ज करें",
  57: "अपना संदेश लिखें ...",
  58: "नया",
  59: "स्वीकृत",
  60: "प्रगति में",
  61: "पूर्ण",
  62: "रद्द",
  63: "बुकिंग",
  64: "अभी कॉल करें",
  65: "संदेश",
  66: "बुकिंग आईडी",
  67: "नया अनुरोध",
  68: "बुकिंग स्वीकृत",
  69: "पर स्वीकार किया",
  70: "नौकरी शुरू करें",
  71: "अनुसूचित",
  72: "काम पूरा हुआ",
  73 : "भुगतान यहां दिखाई देगा",
  74 : "मूल्य निर्धारण",
  75: "मात्रा",
  76: "कर राशि",
  77: "कुल",
  78: "अनुरोध किया गया",
  79: "भुगतान",
  80: "भुगतान करें",
  81: "नकद भुगतान",
  82: "भुगतान की पुष्टि करें",
  83: "समीक्षा",
  84 : "एक समीक्षा छोड़ें",
  85 : "ऑनलाइन चैटिंग",
  86 : "अपनी समीक्षा लिखें",
  87 : "हमें इस सेवा के बारे में कुछ बताएं",
  88 : "इस सेवा को रेट करने के लिए सितारों पर क्लिक करें",
  89: "समीक्षा सबमिट करें",
  90: "छवियां जोड़ें",
  91 : "गैलरी से",
  92: "कैमरा से",
  93 : "घरेलू सेवाएं",
  94 : "आपको जो चाहिए वो ढूंढें",
  95: "खोज सेवा",
  96: "सूचित करें",
  97: "अवधि",
  98: "मिनट",
  99 : "इस सेवा में अधिक समय लग सकता है",
  100: "दीर्घाएँ",
  101 : "समीक्षा और रेटिंग",
  102 : "यह सेवा बुक करें",
  103: "आपका पता",
  104: "नया जोड़ें",
  105: "संकेत",
  106: "क्या कुछ और है",
  107 : "कूपन कोड",
  108: "लागू करें",
  109: "किसी भी समय",
  110: "एक आदेश निर्धारित करें",
  111 : "अनुरोधित सेवा चालू",
  112: "एक तिथि और समय चुनें",
  113 : "अभी पुष्टि करें और बुकिंग करें",
  114: "ठीक है",
  115 : "आपकी बुकिंग सफलतापूर्वक सबमिट कर दी गई है, आपको जल्द ही एक पुष्टिकरण प्राप्त होगा।",
  116: "धन्यवाद!",
  117: "पता जोड़ें",
  118: "माई होम",
  119: "पूरा पता",
  120: "पता चुनें",
  121 : "यहाँ उठाओ",
  122: "खोज",
123: "सोमवार",
124 : "मंगलवार",
125: "बुधवार",
126: "गुरुवार",
127: "शुक्रवार",
128: "शनिवार",
129: "रविवार",
130: "निश्चित",
131 : "प्रति घंटा",
132: "से शुरू करें",
133: "कृपया पता दर्ज करें",
134: "कृपया पता चुनें",
135 : "कृपया ईमेल दर्ज करें",
136: "कृपया पासवर्ड दर्ज करें",
137: "उपयोगकर्ता नहीं मिला",
138: "उपयोगकर्ता नहीं बनाते",
139: "ईमेल गलत हैं",
140: "पासवर्ड समान नहीं हैं",
141 : "फ़ोन नंबर होना चाहिए",
142: "प्रतीक",
143 : "कोड भेजा गया। कृपया सत्यापन कोड के लिए अपने फोन की जांच करें।",
144: "टाइम आउट",
145: "आज",
146: "हमारे बारे में",
147 : "हमारे बारे में जाना जाता है",
148: "नियम और शर्तें",
149 : "ज्ञात नियम और शर्तें",
150: "नहीं मिला ...",
151: "पासवर्ड की पुष्टि दर्ज करें",
152: "पासवर्ड बदल गया",
153: "कृपया नाम दर्ज करें",
154: "डेटा सहेजा गया",
155: "प्रदाता",
156: "चैट संदेश",
157 : "नई बुकिंग आ गई",
158: "अब स्थिति:",
159 : "बुकिंग की स्थिति बदली गई",
160: "उपयोगकर्ता से:",
161 : "इस सेवा को रेट करें",
162 : "कूपन नहीं मिला",
163 : "कूपन सक्रिय",
164 : "कूपन इस प्रदाता द्वारा समर्थित नहीं है",
165 : "कूपन इस श्रेणी का समर्थन नहीं करता",
166 : "कूपन इस सेवा का समर्थन नहीं करता",
167: "कूपन",
168: "नहीं",
169: "कूपन समाप्त हो गया है",
170: "आपका पसंदीदा",
171 : "अपनी पसंदीदा सेवाएं देखें",
172 : "सर्वोच्च सेवाएं",
173 : "उपयोगकर्ता अक्षम है। अधिक जानकारी के लिए व्यवस्थापक से कनेक्ट करें।",
174 : "ब्लॉग",
175: "सभी देखें",
176: "लोड हो रहा है ...",
177: "सेवा",
178 : "क्या आप वाकई बाहर निकलना चाहते हैं?",
179: "नहीं",
180: "बाहर निकलें",
181 : "फ़िल्टर",
182: "क्रमबद्ध करें",
183: "आरोही (ए-जेड)",
184 : "अवरोही (जेड-ए)",
185 : "कीमत",
186: "फ़िल्टर रीसेट करें",
187: "फ़िल्टर लागू करें",
188: "मेरा पता",
189 : "पता नहीं मिला",
190: "होम",
191: "कार्यालय",
192: "अन्य",
193: "स्थान निर्धारित करें",
194 : "अपने आस-पास की सेवाओं का पता लगाएं",
195: "लोकेशन एक्सेस की अनुमति देकर, आप अपने आस-पास की सेवाओं और प्रदाताओं की खोज कर सकते हैं।",
196: "करंट लोकेशन का उपयोग करें",
197: "मानचित्र से सेट करें",
198: "स्थान जोड़ें",
199: "लेबल के रूप में",
200: "वितरण पता",
201 : "डिलीवरी का पता दर्ज करें",
202: "संपर्क नाम",
203: "संपर्क नाम दर्ज करें",
204: "फोन नंबर से संपर्क करें",
205 : "संपर्क फोन नंबर दर्ज करें",
206: "स्थान सहेजें",
207: "अक्षांश",
208: "देशांतर",
209: "कृपया फोन दर्ज करें",
210 : "व्यवस्थापक द्वारा",
211: "प्रदाता द्वारा",
212: "ग्राहक द्वारा",
213: "पता दर्ज करें",
214 : "वर्तमान पता",
215: "अन्य पते",
216: "स्थान",
217: "आपका पता प्रदाता के कार्य क्षेत्र के बाहर है",
218: "विवरण देखें",
219: "विशेष अनुरोध",
220: "प्रदाता स्थान",
221 : "एडॉन्स",
222: "आपके आस-पास",
223: "दूर",
224: "प्रदाता",
  225 : "कृपया वैध कोड दर्ज करें",
  226 : "आपका फ़ोन नंबर सत्यापित है। आप फ़ोन नंबर संपादित नहीं कर सकते",
  227: "पासवर्ड भूल गए?",
  228: "पासवर्ड रीसेट करें",
  229: "नया पासवर्ड भेजें",
  230 : "रीसेट पासवर्ड ईमेल भेजा गया। कृपया अपना मेल जांचें।",
  231: "समय निर्माण",
  232 : "बुकिंग आईडी",
  233 : "कृपया टेक्स्ट दर्ज करें",
  234: "कृपया कोड दर्ज करें",
  235 : "सबटोटल",
  236 : "छूट",
  237: "उपश्रेणी",
  238: "इस ऐप को साझा करें",
  239 : "आस-पास की सेवाएं",
  240 : "ओपन प्रोवाइडर पेज",
  241 : "रिपोर्ट ...",
  242: "ब्लॉक यूजर",
  243: "ब्लॉक",
  244 : "वे आपको मैसेज नहीं कर पाएंगे। आप उन्हें मैसेज नहीं कर पाएंगे। उन्हें सूचित नहीं किया जाएगा कि आपने उन्हें ब्लॉक कर दिया है।",
  245: "उपयोगकर्ता",
  246: "रद्द करें",
  247: "अवरुद्ध",
  248 : "आप इस उपयोगकर्ता की रिपोर्ट क्यों कर रहे हैं?",
  249 : "आपकी रिपोर्ट गुमनाम है, सिवाय इसके कि आप किसी बौद्धिक संपदा उल्लंघन की रिपोर्ट कर रहे हैं।",
  250 : "हमें बताने के लिए धन्यवाद",
  251 : "समुदाय को सुरक्षित रखने में हमारी मदद करने के लिए आपकी प्रतिक्रिया महत्वपूर्ण है।",
  252: "अनब्लॉक करें",
  253: "वे आपको संदेश भेज सकेंगे। आप उन्हें संदेश भेज सकेंगे। उन्हें सूचित नहीं किया जाएगा कि आपने उन्हें अनब्लॉक कर दिया है।",
  254: "अनब्लॉक",
  255 : "आपके पसंदीदा प्रदाता",
  256 : "अपने पसंदीदा प्रदाताओं को देखें",
  257 : "पसंदीदा प्रदाता",
  258: "सूचना सक्षम करें",
  259 : "अभी उपलब्ध नहीं है",
  260: "सेवाएं",
  261 : "प्रदाता उत्पाद",
  262 : "अभी उपलब्ध नहीं है",
  263 : "कुल राशि",
  264: "कार्ट में जोड़ें",
  265 : "कृपया प्रकार चुनें",
  266: "स्टॉक में",
  267: "कार्ट में जोड़ा गया उत्पाद",
  268: "गाड़ी",
  269: "माई कार्ट",
  270 : "चेकआउट के लिए आगे बढ़ें",
  271 : "आपकी गाड़ी खाली है",
  272 : "आइटम की कीमत",
  273 : "यह सेवा पहले से ही कार्ट में है",
  274 : "यह उत्पाद पहले से ही कार्ट में है",
  275 : "सेवा कार्ट में जोड़ी गई",
  276 : "वैट/टैक्स",
  277: "और देखें",
  278: "उत्पाद",
  279 : "उत्पाद खोजें",
  280: "प्रदाता द्वारा क्रमबद्ध करें",
  281 : "नहीं चुनें",
  282 : "संबंधित उत्पाद",
  283 : "अन्य उत्पाद",
  284 : "बुकिंग एट",
  285 : "इस प्रदाता के लिए न्यूनतम खरीद राशि:",
  286 : "इस प्रदाता के लिए अधिकतम खरीद राशि:",
  287: "के साथ भुगतान करें",
  288 : "प्रदाता ग्राहक ऐप में प्रवेश नहीं कर सकता। कृपया अन्य क्रेडेंशियल का उपयोग करें।",
  289 : "प्रोमो जोड़ें",
  290: "प्रोमो नहीं मिला",
  291: "मेरे पुरस्कार",
  292: "कोड दर्ज करें",
  293 : "विशेष पेशकश",
  294 : "अभी उपयोग करें",
  295 : "तक मान्य",
  296 : "आपका प्रोमो कोड",
  297: "कोड लागू करें",
  298 : "कूपन इस उत्पाद का समर्थन नहीं करता",
  299: "प्रोमो कोड",
  300: "निकालें",
};
