Map<int, String> providerEng = {
  0 : "HANDYMAN",
  1 : "PROVIDER",
  2 : "SUBMIT",
  3 : "Language",
  4 : "Preferred Language",
  5 : "Select Preferred Language",
  6 : "Sign in now",
  7 : "Email",
  8 : "Enter your Email",
  9 : "Password",
  10 : "Enter your Password",
  11 : "CONTINUE",
  12 : "REGISTER",
  13 : "or continue with",
  14 : "Register",
  15 : "in less than a minute",
  16 : "Name",
  17 : "Enter Name",
  18 : "Confirm Password",
  19 : "Verification",
  20 : "Phone number",
  21 : "Enter your Phone number",
  22 : "We'll sent verification code.",
  23 : "We've sent 6 digit verification code.",
  24 : "Enter code",
  25 : "Enter 6 digits code",
  26 : "Chat",
  27 : "Booking",
  28 : "Account",
  29 : "Write your message ...",
  30 : "Any Time",
  31 : "Upcoming",
  32 : "Completed",
  33 : "Canceled",
  34 : "New",
  35 : "Canceled",
  36 : "Completed",
  37 : "Accepted",
  38 : "Call now",
  39 : "Message",
  40 : "Accept",
  41 : "Start a job",
  42 : "Job complete",
  43 : "Waiting for Confirmation from Customer",
  44 : "Booking ID",
  45 : "Request Received",
  46 : "Requested on",
  47 : "Booking Confirmed",
  48 : "Confirmed on",
  49 : "Start a job",
  50 : "Scheduled on",
  51 : "Job Completed",
  52 : "Payment will appear here",
  53 : "Pricing",
  54 : "Quantity",
  55 : "Tax amount",
  56 : "Total",
  57 : "View profile",
  58 : "reviews",
  59 : "Read all",
  60 : "Change Language",
  61 : "Set your Preferred language",
  62 : "Enter your Email",
  63 : "Address",
  64 : "Enter address for customers",
  65 : "Description",
  66 : "Enter Short description about you",
  67 : "SAVE",
  68 : "Change password",
  69 : "New password",
  70 : "Enter Password",
  71 : "Confirm New password",
  72 : "CHANGE PASSWORD",
  73 : "My Profile",
  74 : "Everything about you",
  75 : "Average Ratings",
  76 : "Enable Dark Mode",
  77 : "Set you favorite mode",
  78 : "Wallet",
  79 : "Know your earnings",
  80 : "My Portfolio",
  81 : "Upload your best works",
  82 : "Privacy Policy",
  83 : "Known our Privacy Policy",
  84 : "From Gallery",
  85 : "From Camera",
  86 : "Delete",
  87 : "Set invisible",
  88 : "Available Balance",
  89 : "Notifications",
  90 : "Lots of important information",
  91 : "Log Out",
  92 : "End the session",
  93 : "Please Enter Email",
  94 : "Please Enter Password",
  95 : "User not found",
  96 : "User is disabled. Connect to Administrator for more information.",
  97 : "Passwords are not equal",
  98 : "Email are wrong",
  99 : "User don't create",
  100 : "You account created. After moderation your account will be activated. We will inform you.",
  101 : "Chatting online",
  102 : "Search",
  103 : "Chat message",
  104 : "Notifications",
  105 : "Lots of important information",
  106 : "Today",
  107 : "Not found ...",
  108 : "About Us",
  109 : "Known About Us",
  110 : "Terms & Conditions",
  111 : "Known Terms & Conditions",
  112 : "Enter your name",
  113 : "Enter Confirm Password",
  114 : "Password changed",
  115 : "Please Enter name",
  116 : "Data saved",
  117 : "Booking status was changed",
  118 : "Now status:",
  119 : "by customer",
  120 : "by provider",
  121 : "by administrator",
  122 : "Money transfer",
  123 : "My page",
  124 : "Edit Provider information",
  125 : "Monday",
  126 : "Tuesday",
  127 : "Wednesday",
  128 : "Thursday",
  129 : "Friday",
  130 : "Saturday",
  131 : "Sunday",
  132 : "Galleries",
  133 : "Edit",
  134 : "Save",
  135 : "Enter your Phone",
  136 : "Enter your Web Page address",
  137 : "Enter your Instagram address",
  138 : "Enter your Telegram address",
  139 : "Change",
  140 : "Add from galley",
  141 : "Add from camera",
  142 : "My Services",
  143 : "Edit Service information",
  144 : "Search service",
  145 : "Do you want to delete this item? You will can't recover this item.",
  146 : "No",
  147 : "This is Demo Mode. You can't modify this section",
  148 : "Edit Service",
  149 : "Visible",
  150 : "Select Language",
  151 : "Tax",
  152 : "Description Title",
  153 : "Price",
  154 : "Discount price",
  155 : "Price Unit",
  156 : "Hourly",
  157 : "Fixed",
  158 : "Select image",
  159 : "Addons",
  160 : "Add addon",
  161 : "Gallery",
  162 : "Image deleted",
  163 : "Add image to gallery",
  164 : "Service duration",
  165 : "min",
  166 : "Only selected",
  167 : "Categories",
  168 : "Providers",
  169 : "Save current service",
  170 : "Please enter price",
  171 : "Please select provider",
  172 : "Please enter category",
  173 : "Save addon",
  174 : "Close",
  175 : "Select",
  176 : "Addon will be deleted from all services in current Provider. Do you want to delete this item? You will can't recover this item. ",
  177 : "Data deleted",
  178 : "Create new service",
  179 : "My Work Area",
  180 : "Edit your work area",
  181 : "Delete current",
  182 : "Forgot password?",
  183 : "Reset password",
  184 : "Send new password",
  185 : "Reset password email sent. Please check your mail.",
  186 : "Time creation",
  187 : "Please Enter phone",
  188 : "Please leave information for us to make it easier for us to work with you.",
  189 : "Provider Name",
  190 : "Home service",
  191 : "Login",
  192 : "Phone",
  193 : "Set my Work Area",
  194 : "Set Provider Logo",
  195 : "Please Enter Provider Name",
  196 : "Please Enter description",
  197 : "Please Enter address",
  198 : "Please upload Provider Logo",
  199 : "Please select work area",
  200 : "Please select Category where you will work",
  201 : "Please Enter Login",
  202 : "Payment method",
  203 : "Subtotal",
  204 : "Discount",
  205 : "User must be Provider",
  206 : "Provider Information not found",
  207 : "Are you sure you want to exit?",
  208 : "Exit",
  209 : "On map",
  210 : "Customer location",
  211 : "Customer address",
  212 : "Enable Notify",
  213 : "Provider Available/Unavailable",
  214 : "Temporary disable your account",
  215 : "VAT/TAX",
  216 : "Total amount",
  217 : "Booking At",
  218 : "Customer name",
  219 : "To Admin",
  220 : "To Provider",
  221 : "TAX/VAT",
  222 : "Payouts",
  223 : "Balance",
  224 : "Orders",
  225 : "My Products",
  226 : "Edit Products information",
  227 : "Search in this list",
  228 : "Create new product",
  229 : "Not available Now",
  230 : "Add image URL",
  231 : "Description:",
  232 : "You can use HTML tags (<p>, <br>, <h1> and other)",
  233 : "Variants",
  234 : "Add new group",
  235 : "Add new variant",
  236 : "Save current product",
  237 : "Add New Product",
  238 : "Unit",
  239 : "In Stock",
  240 : "pcs",
  241 : "Please select variant",
  242 : "Save group",
  243 : "Add group",
  244 : "Group name",
  245 : "Preview",
  246 : "URL",
  247 : "Add image",
  248 : "Variant name",
  249 : "Add image from gallery (optional)",
  250 : "or",
  251 : "Add image URL (optional)",
  252 : "influence on price +/-",
  253 : "Save variant",
  254 : "Add variant",
  255 : "Please select stock",
  256 : "influence must start with + or -",
  257 : "Close",
  258 : "Add image from camera",
  259 : "Add image from camera (optional)",
  260 : "Please upload image",
  261 : "Cancel",
  262 : "You have exceeded the limit on the number of services. Contact support for more information.",
  263 : "Category tree",
  264 : "Price can't be 0",
  265 : "You have exceeded the limit on the number of addons on one service. Contact support for more information.",
  266 : "You have exceeded the limit on the number of products. Contact support for more information.",
  267 : "Minimum order amount",
  268 : "Maximum order amount",
  269 : "Settings",
  270 : "Set minimum amd maximum order amounts",
  271 : "Please enter minimum order amount",
  272 : "Please enter maximum order amount",
  273 : "Allow booking only if customer located in provider work area",
  274 : "Subscription Status",
  275 : "Expire date",
  276 : "Subscribed",
  277 : "Not Subscribed",
  278 : "Subscribe now",
  279 : "Extend your subscription",
  280 : "",
  281 : "Start Free Trial Now",
  282 : "Start",
  283 : "Pay with",
  284 : "You subscriptions expired",
  285 : "Expired",
  286 : "Confirm Subscription. Do you want to subscribe for Two month for",
  287 : "Free Trial",

};

Map<int, String> providerDeu = {
  0 : "HANDYMAN",
  1: "ANBIETER",
  2: "ABSENDEN",
  3: "Sprache",
  4: "Bevorzugte Sprache",
  5 : "Bevorzugte Sprache auswählen",
  6 : "Jetzt anmelden",
  7 : "E-Mail",
  8 : "Geben Sie Ihre E-Mail-Adresse ein",
  9 : "Passwort",
  10 : "Geben Sie Ihr Passwort ein",
  11 : "WEITER",
  12 : "REGISTRIEREN",
  13 : "oder weiter mit",
  14 : "Registrieren",
  15 : "in weniger als einer Minute",
  16 : "Name",
  17 : "Namen eingeben",
  18 : "Passwort bestätigen",
  19 : "Verifizierung",
  20 : "Telefonnummer",
  21 : "Geben Sie Ihre Telefonnummer ein",
  22 : "Wir senden den Bestätigungscode.",
  23 : "Wir haben einen 6-stelligen Bestätigungscode gesendet.",
  24 : "Code eingeben",
  25 : "Geben Sie den 6-stelligen Code ein",
  26 : "Chat",
  27 : "Buchung",
  28 : "Konto",
  29 : "Schreiben Sie Ihre Nachricht ...",
  30 : "Buchung",
  31 : "Bevorstehend",
  32 : "Abgeschlossen",
  33 : "Abgesagt",
  34 : "Neu",
  35 : "Abgesagt",
  36 : "Abgeschlossen",
  37 : "Akzeptiert",
  38 : "Jetzt anrufen",
  39 : "Nachricht",
  40 : "Akzeptieren",
  41 : "Job starten",
  42 : "Auftrag abgeschlossen",
  43 : "Warten auf Bestätigung vom Kunden",
  44 : "Buchungs-ID",
  45 : "Anfrage erhalten",
  46 : "Angefordert am",
  47 : "Buchung bestätigt",
  48 : "Bestätigt am",
  49 : "Job starten",
  50 : "Geplant am",
  51 : "Auftrag abgeschlossen",
  52 : "Die Zahlung wird hier angezeigt",
  53 : "Preise",
  54 : "Menge",
  55 : "Steuerbetrag",
  56 : "Gesamt",
  57 : "Profil anzeigen",
  58: "Rezensionen",
  59 : "Alles lesen",
  60 : "Sprache ändern",
  61 : "Stellen Sie Ihre bevorzugte Sprache ein",
  62 : "Geben Sie Ihre E-Mail ein",
  63 : "Adresse",
  64 : "Anschrift für Kunden eingeben",
  65 : "Beschreibung",
  66 : "Geben Sie eine kurze Beschreibung über Sie ein",
  67 : "SPEICHERN",
  68 : "Passwort ändern",
  69 : "Neues Passwort",
  70 : "Passwort eingeben",
  71 : "Neues Passwort bestätigen",
  72 : "PASSWORT ÄNDERN",
  73 : "Mein Profil",
  74 : "Alles über dich",
  75 : "Durchschnittliche Bewertungen",
  76 : "Dunkelmodus aktivieren",
  77 : "Stellen Sie Ihren Lieblingsmodus ein",
  78 : "Geldbörse",
  79 : "Kennen Sie Ihr Einkommen",
  80 : "Mein Portfolio",
  81 : "Laden Sie Ihre besten Werke hoch",
  82 : "Datenschutzerklärung",
  83 : "Unsere Datenschutzrichtlinie bekannt",
  84 : "Aus der Galerie",
  85 : "Von der Kamera",
  86 : "Löschen",
  87 : "Unsichtbar setzen",
  88 : "Verfügbares Guthaben",
  89 : "Benachrichtigungen",
  90 : "Viele wichtige Informationen",
  91 : "Abmelden",
  92 : "Sitzung beenden",
  93 : "Bitte E-Mail eingeben",
  94 : "Bitte Passwort eingeben",
  95 : "Benutzer nicht gefunden",
  96 : "Benutzer ist deaktiviert. Verbinden Sie sich mit dem Administrator für weitere Informationen.",
  97 : "Passwörter sind nicht gleich",
  98 : "E-Mail ist falsch",
  99 : "Benutzer erstellt nicht",
  100 : "Ihr Konto wurde erstellt. Nach der Moderation wird Ihr Konto freigeschaltet. Wir werden Sie informieren.",
  101 : "Online-Chat",
  102 : "Suche",
  103 : "Chat-Nachricht",
  104 : "Benachrichtigungen",
  105 : "Viele wichtige Informationen",
  106 : "Heute",
  107 : "Nicht gefunden ...",
  108 : "Über uns",
  109 : "Über uns bekannt",
  110 : "Allgemeine Geschäftsbedingungen",
  111 : "Bekannte Geschäftsbedingungen",
  112 : "Geben Sie Ihren Namen ein",
  113 : "Passwort zur Bestätigung eingeben",
  114 : "Passwort geändert",
  115 : "Bitte Namen eingeben",
  116 : "Daten gespeichert",
  117 : "Buchungsstatus wurde geändert",
  118 : "Jetzt Status:",
  119 : "vom Kunden",
  120 : "nach Anbieter",
  121 : "vom Administrator",
  122 : "Geldtransfer",
  123 : "Meine Seite",
  124 : "Anbieterinformationen bearbeiten",
  125 : "Montag",
  126 : "Dienstag",
  127 : "Mittwoch",
  128 : "Donnerstag",
  129 : "Freitag",
  130 : "Samstag",
  131 : "Sonntag",
  132 : "Galerien",
  133 : "Bearbeiten",
  134 : "Speichern",
  135 : "Geben Sie Ihr Telefon ein",
  136 : "Geben Sie Ihre Webseitenadresse ein",
  137 : "Geben Sie Ihre Instagram-Adresse ein",
  138 : "Geben Sie Ihre Telegrammadresse ein",
  139 : "Änderung",
  140 : "Aus der Kombüse hinzufügen",
  141 : "Von Kamera hinzufügen",
  142 : "Meine Dienste",
  143 : "Serviceinformationen bearbeiten",
  144 : "Suchdienst",
  145 : "Möchten Sie dieses Element löschen? Sie können dieses Element nicht wiederherstellen.",
  146 : "Nein",
  147 : "Dies ist der Demo-Modus. Sie können diesen Abschnitt nicht ändern",
  148 : "Dienst bearbeiten",
  149 : "Sichtbar",
  150 : "Sprache auswählen",
  151 : "Steuer",
  152 : "Beschreibungstitel",
  153 : "Preis",
  154 : "Rabattpreis",
  155 : "Preiseinheit",
  156 : "Stündlich",
  157 : "Behoben",
  158 : "Bild auswählen",
  159 : "Add-ons",
  160 : "Add-On hinzufügen",
  161 : "Galerie",
  162 : "Bild gelöscht",
  163 : "Bild zur Galerie hinzufügen",
  164 : "Dienstdauer",
  165 : "min",
  166 : "Nur ausgewählt",
  167 : "Kategorien",
  168 : "Anbieter",
  169 : "Aktuellen Dienst speichern",
  170 : "Bitte Preis eingeben",
  171 : "Bitte Anbieter auswählen",
  172 : "Bitte Kategorie eingeben",
  173 : "Addon speichern",
  174 : "Schließen",
  175 : "Auswählen",
  176 : "Addon wird aus allen Diensten des aktuellen Anbieters gelöscht. Möchten Sie dieses Element löschen? Sie können dieses Element nicht wiederherstellen. ",
  177 : "Daten gelöscht",
  178 : "Neuen Dienst erstellen",
  179 : "Mein Arbeitsbereich",
  180 : "Bearbeiten Sie Ihren Arbeitsbereich",
  181 : "Aktuell löschen",
  182 : "Passwort vergessen?",
  183 : "Passwort zurücksetzen",
  184 : "Neues Passwort senden",
  185 : "E-Mail zum Zurücksetzen des Passworts gesendet. Bitte überprüfen Sie Ihre E-Mails.",
  186 : "Zeiterstellung",
  187 : "Bitte Telefon eingeben",
  188 : "Bitte hinterlassen Sie uns Informationen, um uns die Zusammenarbeit mit Ihnen zu erleichtern.",
  189 : "Anbietername",
  190 : "Heimdienst",
  191 : "Anmelden",
  192 : "Telefon",
  193 : "Meinen Arbeitsbereich festlegen",
  194 : "Anbieterlogo setzen",
  195 : "Bitte Anbieternamen eingeben",
  196 : "Bitte Beschreibung eingeben",
  197 : "Bitte Adresse eingeben",
  198 : "Bitte Anbieterlogo hochladen",
  199 : "Bitte Arbeitsbereich auswählen",
  200 : "Bitte wählen Sie die Kategorie, in der Sie arbeiten werden",
  201 : "Bitte Login eingeben",
  202 : "Zahlungsmethode",
  203 : "Zwischensumme",
  204 : "Rabatt",
  205 : "Benutzer muss Anbieter sein",
  206 : "Anbieterinformationen nicht gefunden",
  207 : "Sind Sie sicher, dass Sie das Programm verlassen möchten?",
  208 : "Ausgang",
  209 : "Auf der Karte",
  210 : "Kundenstandort",
  211 : "Kundenadresse",
  212 : "Benachrichtigung aktivieren",
  213 : "Anbieter verfügbar/nicht verfügbar",
  214 : "Ihr Konto vorübergehend deaktivieren",
  215 : "Mehrwertsteuer/Steuer",
  216 : "Gesamtbetrag",
  217 : "Buchung um",
  218 : "Kundenname",
  219 : "An den Administrator",
  220 : "An Anbieter",
  221 : "STEUER/MWST",
  222 : "Auszahlungen",
  223 : "Gleichgewicht",
  224 : "Bestellungen",
  225 : "Meine Produkte",
  226 : "Produktinformationen bearbeiten",
  227 : "In dieser Liste suchen",
  228 : "Neues Produkt erstellen",
  229 : "Jetzt nicht verfügbar",
  230 : "Bild-URL hinzufügen",
  231 : "Beschreibung:",
  232 : "Sie können HTML-Tags verwenden (<p>, <br>, <h1> und andere)",
  233 : "Varianten",
  234 : "Neue Gruppe hinzufügen",
  235 : "Neue Variante hinzufügen",
  236 : "Aktuelles Produkt speichern",
  237 : "Neues Produkt hinzufügen",
  238 : "Einheit",
  239 : "Auf Lager",
  240 : "Stk",
  241 : "Bitte Variante auswählen",
  242 : "Gruppe speichern",
  243 : "Gruppe hinzufügen",
  244 : "Gruppenname",
  245 : "Vorschau",
  246 : "URL",
  247 : "Bild hinzufügen",
  248 : "Variantenname",
  249 : "Bild aus Galerie hinzufügen (optional)",
  250 : "oder",
  251 : "Bild-URL hinzufügen (optional)",
  252 : "Einfluss auf den Preis +/-",
  253 : "Variante speichern",
  254 : "Variante hinzufügen",
  255 : "Bitte Lager auswählen",
  256 : "Einfluss muss mit + oder - beginnen",
  257 : "Schließen",
  258 : "Bild von Kamera hinzufügen",
  259 : "Bild von Kamera hinzufügen (optional)",
  260 : "Bitte Bild hochladen",
  261 : "Abbrechen",
  262 : "Sie haben das Limit für die Anzahl der Dienste überschritten. Kontaktieren Sie den Support für weitere Informationen.",
  263 : "Kategoriebaum",
  264 : "Preis darf nicht 0 sein",
  265 : "Sie haben das Limit für die Anzahl der Addons für einen Dienst überschritten. Wenden Sie sich an den Support, um weitere Informationen zu erhalten.",
  266 : "Sie haben das Limit für die Anzahl der Produkte überschritten. Wenden Sie sich an den Support, um weitere Informationen zu erhalten.",
  267 : "Mindestbestellmenge",
  268 : "Höchstbestellmenge",
  269 : "Einstellungen",
  270 : "Mindest- und Höchstbestellmengen festlegen",
  271 : "Bitte Mindestbestellmenge eingeben",
  272 : "Bitte maximale Bestellmenge eingeben",
  273 : "Buchung nur zulassen, wenn sich Kunde im Arbeitsbereich des Anbieters befindet",
  274 : "Abonnementstatus",
  275 : "Ablaufdatum",
  276 : "Abonniert",
  277 : "Nicht angemeldet",
  278 : "Jetzt abonnieren",
  279 : "Verlängern Sie Ihr Abonnement",
  280 : "",
  281 : "Kostenlose Testversion jetzt starten",
  282 : "Starten",
  283 : "Bezahlen mit",
  284 : "Ihre Abonnements sind abgelaufen",
  285 : "Abgelaufen",
  286 : "Abo bestätigen. Möchten Sie zwei Monate abonnieren für",
  287 : "Kostenlos testen",
};

Map<int, String> providerEsp = {
  0 : "HANDYMAN",
  1: "PROVEEDOR",
  2: "ENVIAR",
  3: "Idioma",
  4: "Idioma preferido",
  5: "Seleccionar idioma preferido",
  6: "Iniciar sesión ahora",
  7: "Correo electrónico",
  8: "Ingrese su correo electrónico",
  9: "Contraseña",
  10: "Ingrese su contraseña",
  11: "CONTINUAR",
  12: "REGISTRARSE",
  13: "o continuar con",
  14: "Registrarse",
  15: "en menos de un minuto",
  16: "Nombre",
  17: "Ingresar nombre",
  18: "Confirmar contraseña",
  19: "Verificación",
  20: "Número de teléfono",
  21: "Ingrese su número de teléfono",
  22: "Enviaremos el código de verificación",
  23: "Hemos enviado un código de verificación de 6 dígitos",
  24: "Introducir código",
  25: "Introduzca código de 6 dígitos",
  26: "Chat",
  27: "Reserva",
  28: "Cuenta",
  29: "Escribe tu mensaje ...",
  30: "Reserva",
  31: "Próximamente",
  32: "Completado",
  33: "Cancelado",
  34: "Nuevo",
  35: "Cancelado",
  36: "Completado",
  37: "Aceptado",
  38: "Llamar ahora",
  39: "Mensaje",
  40: "Aceptar",
  41: "Iniciar un trabajo",
  42: "Trabajo completado",
  43: "Esperando confirmación del cliente",
  44: "ID de reserva",
  45: "Solicitud recibida",
  46: "Solicitado el",
  47: "Reserva confirmada",
  48: "Confirmado el",
  49: "Iniciar un trabajo",
  50: "Programado el",
  51: "Trabajo completado",
  52: "El pago aparecerá aquí",
  53: "Precios",
  54: "Cantidad",
  55: "Importe de impuestos",
  56: "Total",
  57: "Ver perfil",
  58: "opiniones",
  59: "Leer todo",
  60: "Cambiar idioma",
  61: "Configure su idioma preferido",
  62: "Ingrese su correo electrónico",
  63: "Dirección",
  64: "Introduzca la dirección de los clientes",
  65: "Descripción",
  66: "Introduzca una breve descripción sobre usted",
  67: "GUARDAR",
  68: "Cambiar contraseña",
  69: "Nueva contraseña",
  70: "Ingresar contraseña",
  71: "Confirmar nueva contraseña",
  72: "CAMBIAR CONTRASEÑA",
  73: "Mi perfil",
  74: "Todo sobre ti",
  75: "Calificaciones promedio",
  76: "Habilitar el modo oscuro",
  77: "Configura tu modo favorito",
  78: "Billetera",
  79: "Conozca sus ganancias",
  80: "Mi cartera",
  81: "Sube tus mejores trabajos",
  82: "Política de privacidad",
  83: "Conoce nuestra Política de privacidad",
  84: "De la galería",
  85: "Desde la cámara",
  86: "Eliminar",
  87: "Establecer invisible",
  88: "Saldo disponible",
  89: "Notificaciones",
  90: "Mucha información importante",
  91: "Cerrar sesión",
  92: "Finalizar la sesión",
  93: "Ingrese correo electrónico",
  94: "Introduzca la contraseña",
  95: "Usuario no encontrado",
  96: "El usuario está deshabilitado. Conéctese con el administrador para obtener más información",
  97: "Las contraseñas no son iguales",
  98: "El correo electrónico es incorrecto",
  99: "El usuario no crea",
  100: "Tu cuenta creada. Después de la moderación, tu cuenta se activará. Te informaremos.",
  101: "Chatear en línea",
  102: "Buscar",
  103: "Mensaje de chat",
  104: "Notificaciones",
  105: "Mucha información importante",
  106: "Hoy",
  107: "No encontrado ...",
  108: "Acerca de nosotros",
  109: "Conocenos",
  110: "Términos y condiciones",
  111: "Términos y condiciones conocidos",
  112: "Ingrese su nombre",
  113: "Ingrese Confirmar contraseña",
  114: "Contraseña cambiada",
  115: "Introduzca el nombre",
  116: "Datos guardados",
  117: "Se cambió el estado de la reserva",
  118: "Ahora estado:",
  119: "por cliente",
  120: "por proveedor",
  121: "por administrador",
  122: "Transferencia de dinero",
  123: "Mi página",
  124: "Editar información del proveedor",
  125: "Lunes",
  126: "martes",
  127: "miércoles",
  128: "jueves",
  129: "Viernes",
  130: "Sábado",
  131: "Domingo",
  132: "Galerías",
  133: "Editar",
  134: "Guardar",
  135: "Ingresa tu teléfono",
  136: "Ingrese la dirección de su página web",
  137: "Ingresa tu dirección de Instagram",
  138: "Ingrese su dirección de Telegram",
  139: "Cambiar",
  140: "Agregar desde la cocina",
  141: "Agregar desde la cámara",
  142: "Mis servicios",
  143: "Editar información de servicio",
  144: "Servicio de búsqueda",
  145: "¿Quieres eliminar este elemento? No podrás recuperarlo",
  146: "No",
  147: "Este es el modo de demostración. No puede modificar esta sección",
  148: "Editar servicio",
  149: "Visible",
  150: "Seleccionar idioma",
  151: "Impuestos",
  152: "Título de la descripción",
  153: "Precio",
  154: "Precio de descuento",
  155: "Unidad de precio",
  156: "Cada hora",
  157: "Fijo",
  158: "Seleccionar imagen",
  159: "Complementos",
  160: "Agregar complemento",
  161: "Galería",
  162: "Imagen eliminada",
  163: "Agregar imagen a la galería",
  164: "Duración del servicio",
  165: "min",
  166: "Solo seleccionados",
  167: "Categorías",
  168: "Proveedores",
  169: "Guardar servicio actual",
  170: "Introduzca el precio",
  171: "Seleccione el proveedor",
  172: "Por favor ingrese la categoría",
  173: "Guardar complemento",
  174: "Cerrar",
  175: "Seleccionar",
  176: "El complemento se eliminará de todos los servicios del proveedor actual. ¿Quieres eliminar este elemento? No podrás recuperarlo",
  177: "Datos eliminados",
  178: "Crear nuevo servicio",
  179: "Mi área de trabajo",
  180: "Edita tu área de trabajo",
  181: "Eliminar actual",
  182: "¿Olvidaste tu contraseña?",
  183: "Restablecer contraseña",
  184: "Enviar nueva contraseña",
  185: "Se envió el correo electrónico para restablecer la contraseña. Revise su correo",
  186: "Creación de tiempo",
  187: "Ingrese el teléfono",
  188: "Por favor, déjenos información para que nos sea más fácil trabajar con usted",
  189: "Nombre del proveedor",
  190: "Servicio a domicilio",
  191: "Iniciar sesión",
  192: "Teléfono",
  193: "Establecer mi área de trabajo",
  194: "Establecer logotipo del proveedor",
  195: "Introduzca el nombre del proveedor",
  196: "Introduzca una descripción",
  197: "Introduzca la dirección",
  198: "Cargue el logotipo del proveedor",
  199: "Seleccione el área de trabajo",
  200: "Seleccione la categoría donde trabajará",
  201: "Ingrese el inicio de sesión",
  202: "Método de pago",
  203: "Subtotal",
  204: "Descuento",
  205 : "Benutzer muss Anbieter sein",
  206: "Información del proveedor no encontrada",
  207: "¿Seguro que quieres salir?",
  208: "Salir",
  209: "En el mapa",
  210: "Ubicación del cliente",
  211: "Dirección del cliente",
  212: "Activar notificación",
  213: "Proveedor disponible / no disponible",
  214: "Deshabilitar temporalmente su cuenta",
  215: "IVA / IMPUESTOS",
  216: "Importe total",
  217: "Reservando en",
  218: "Nombre del cliente",
  219: "Para administrador",
  220: "Al proveedor",
  221: "IMPUESTO / IVA",
  222: "Pagos",
  223: "Equilibrio",
  224: "Pedidos",
  225: "Mis productos",
  226: "Editar información de productos",
  227: "Buscar en esta lista",
  228: "Crear nuevo producto",
  229: "No disponible ahora",
  230: "Agregar URL de imagen",
  231: "Descripción:",
  232: "Puede utilizar etiquetas HTML (<p>, <br>, <h1> y otras)",
  233: "Variantes",
  234: "Agregar nuevo grupo",
  235: "Agregar nueva variante",
  236: "Guardar producto actual",
  237: "Agregar nuevo producto",
  238: "Unidad",
  239: "En stock",
  240: "pcs",
  241: "Seleccione la variante",
  242: "Guardar grupo",
  243: "Agregar grupo",
  244: "Nombre del grupo",
  245: "Vista previa",
  246: "URL",
  247: "Agregar imagen",
  248: "Nombre de la variante",
  249: "Agregar imagen de la galería (opcional)",
  250: "o",
  251: "Agregar URL de imagen (opcional)",
  252: "influencia en el precio +/-",
  253: "Guardar variante",
  254: "Agregar variante",
  255: "Seleccione stock",
  256: "la influencia debe comenzar con + o -",
  257: "Cerrar",
  258: "Agregar imagen de la cámara",
  259: "Agregar imagen de la cámara (opcional)",
  260: "Cargue la imagen",
261: "Cancelar",
262: "Ha excedido el límite en la cantidad de servicios. Póngase en contacto con el soporte para obtener más información",
263: "Árbol de categorías",
264: "El precio no puede ser 0",
265: "Ha excedido el límite en la cantidad de complementos en un servicio. Comuníquese con soporte para obtener más información",
266: "Ha excedido el límite en la cantidad de productos. Póngase en contacto con el soporte para obtener más información",
267: "Cantidad mínima de pedido",
268: "Cantidad máxima de pedido",
269: "Configuración",
270: "Establecer cantidades mínimas y máximas de pedido",
271: "Ingrese el monto mínimo del pedido",
272: "Ingrese el monto máximo del pedido",
273: "Permitir reserva solo si el cliente se encuentra en el área de trabajo del proveedor",
  274: "Estado de suscripción",
  275: "Fecha de caducidad",
  276: "Suscrito",
  277: "No suscrito",
  278: "Suscríbete ahora",
  279: "Extender su suscripción",
  280: "",
  281: "Iniciar prueba gratuita ahora",
  282: "Inicio",
  283: "Pagar con",
  284: "Tus suscripciones expiraron",
  285: "Caducado",
  286: "Confirmar suscripción. ¿Desea suscribirse por dos meses para",
  287: "Prueba gratuita",
};

Map<int, String> providerFrench = {
  0 : "HANDYMAN",
  1 : "POURNISSEUR",
  2 : "ENVOYER",
  3 : "Langue",
  4 : "Langue préférée",
  5 : "Sélectionner la langue préférée",
  6 : "Connectez-vous maintenant",
  7 : "Courriel",
  8 : "Entrez votre Email",
  9 : "Mot de passe",
  10 : "Entrez votre mot de passe",
  11 : "CONTINUER",
  12 : "INSCRIPTION",
  13 : "ou continuer avec",
  14 : "S'inscrire",
  15 : "en moins d'une minute",
  16 : "Nom",
  17 : "Entrez le nom",
  18 : "Confirmer le mot de passe",
  19 : "Vérification",
  20 : "Numéro de téléphone",
  21 : "Entrez votre numéro de téléphone",
  22 : "Nous vous enverrons le code de vérification.",
  23 : "Nous avons envoyé un code de vérification à 6 chiffres.",
  24 : "Entrez le code",
  25 : "Entrez le code à 6 chiffres",
  26 : "Chat",
  27 : "Réservation",
  28 : "Compte",
  29 : "Ecrivez votre message...",
  30 : "Réservation",
  31 : "À venir",
  32 : "Terminé",
  33 : "Annulé",
  34 : "Nouveau",
  35 : "Annulé",
  36 : "Terminé",
  37 : "Accepté",
  38 : "Appeler maintenant",
  39 : "Message",
  40 : "Accepter",
  41 : "Démarrer un travail",
  42 : "Tâche terminée",
  43 : "En attente de la confirmation du client",
  44 : "Identifiant de réservation",
  45 : "Demande reçue",
  46 : "Demandé le",
  47 : "Réservation confirmée",
  48 : "Confirmé le",
  49 : "Démarrer un travail",
  50 : "Prévu le",
  51 : "Tâche terminée",
  52 : "Le paiement apparaîtra ici",
  53 : "Tarification",
  54 : "Quantité",
  55 : "Montant de la taxe",
  56 : "Total",
  57 : "Voir le profil",
  58 : "avis",
  59 : "Tout lire",
  60 : "Changer de langue",
  61 : "Définir votre langue préférée",
  62 : "Entrez votre Email",
  63 : "Adresse",
  64 : "Saisir l'adresse des clients",
  65 : "Description",
  66 : "Entrez une brève description de vous",
  67 : "ENREGISTRER",
  68 : "Changer le mot de passe",
  69 : "Nouveau mot de passe",
  70 : "Entrer le mot de passe",
  71 : "Confirmer le nouveau mot de passe",
  72 : "CHANGER MOT DE PASSE",
  73 : "Mon profil",
  74 : "Tout de toi",
  75 : "Notes moyennes",
  76 : "Activer le mode sombre",
  77 : "Définir votre mode préféré",
  78 : "Portefeuille",
  79 : "Connaître vos gains",
  80 : "Mon Portefeuille",
  81 : "Téléchargez vos meilleures oeuvres",
  82: "Politique de confidentialité",
  83:" Connaître notre politique de confidentialité ",
  84 : "De la Galerie",
  85: "Depuis la caméra",
  86 : "Supprimer",
  87 : "Définir invisible",
  88 : "Solde disponible",
  89 : "Notifications",
  90 : "Beaucoup d'informations importantes",
  91 : "Déconnexion",
  92 : "Terminer la session",
  93 : "Veuillez entrer votre e-mail",
  94 : "Veuillez entrer le mot de passe",
  95 : "Utilisateur non trouvé",
  96 : "L'utilisateur est désactivé. Connectez-vous à l'administrateur pour plus d'informations.",
  97 : "Les mots de passe ne sont pas égaux",
  98 : "Les e-mails sont erronés",
  99 : "L'utilisateur ne crée pas",
  100 : "Votre compte créé. Après modération votre compte sera activé. Nous vous informerons.",
  101 : "Tchatter en ligne",
  102 : "Rechercher",
  103 : "Message de discussion",
  104 : "Notifications",
  105 : "Beaucoup d'informations importantes",
  106 : "Aujourd'hui",
  107 : "Non trouvé...",
  108 : "À propos de nous",
  109 : "Connu de nous",
  110 : "Conditions Générales",
  111 : "Conditions Générales Connues",
  112 : "Entrez votre nom",
  113 : "Entrer Confirmer Mot de Passe",
  114 : "Mot de passe modifié",
  115 : "Veuillez entrer le nom",
  116 : "Données sauvegardées",
  117 : "Le statut de la réservation a été modifié",
  118 : "État actuel :",
  119 : "par client",
  120 : "par fournisseur",
  121 : "par administrateur",
  122 : "Transfert d'argent",
  123 : "Ma page",
  124 : "Modifier les informations du fournisseur",
  125 : "Lundi",
  126 : "mardi",
  127 : "mercredi",
  128 : "Jeudi",
  129 : "Vendredi",
  130 : "samedi",
  131 : "Dimanche",
  132 : "Galeries",
  133 : "Modifier",
  134 : "Sauvegarder",
  135 : "Entrez votre téléphone",
  136 : "Entrez l'adresse de votre Page Web",
  137 : "Entrez votre adresse Instagram",
  138 : "Entrez votre adresse Télégramme",
  139 : "Modifier",
  140 : "Ajouter depuis la galère",
  141 : "Ajouter depuis la caméra",
  142 : "Mes Prestations",
  143 : "Modifier les informations de service",
  144 : "Service de recherche",
  145 : "Voulez-vous supprimer cet élément ? Vous ne pourrez pas récupérer cet élément.",
  146 : "Non",
  147 : "C'est le Mode Démo. Vous ne pouvez pas modifier cette section",
  148 : "Modifier le service",
  149 : "Visible",
  150 : "Choisir la langue",
  151 : "Taxe",
  152 : "Description Titre",
  153 : "Prix",
  154 : "Prix réduit",
  155 : "Prix Unitaire",
  156 : "Horaire",
  157 : "Fixe",
  158 : "Sélectionner image",
  159 : "Ajouts",
  160 : "Ajouter un module complémentaire",
  161 : "Galerie",
  162 : "Image supprimée",
  163 : "Ajouter une image à la galerie",
  164 : "Durée de la prestation",
  165 : "min",
  166 : "Sélectionné uniquement",
  167 : "Catégories",
  168 : "Fournisseurs",
  169 : "Sauvegarder le service en cours",
  170 : "Veuillez saisir le prix",
  171 : "Veuillez sélectionner le fournisseur",
  172 : "Veuillez entrer une catégorie",
  173 : "Enregistrer l'extension",
  174 : "Fermer",
  175 : "Sélectionner",
  176 : "L'extension sera supprimée de tous les services du fournisseur actuel. Voulez-vous supprimer cet élément? Vous ne pourrez pas récupérer cet élément.",
  177 : "Données supprimées",
  178 : "Créer un nouveau service",
  179 : "Mon Espace de Travail",
  180 : "Modifier votre espace de travail",
  181 : "Supprimer courant",
  182 : "Mot de passe oublié ?",
  183 : "Réinitialiser le mot de passe",
  184 : "Envoyer nouveau mot de passe",
  185 : "E-mail de réinitialisation du mot de passe envoyé. Veuillez vérifier votre messagerie.",
  186 : "Création du temps",
  187 : "Veuillez entrer le téléphone",
  188 : "Veuillez nous laisser des informations pour nous permettre de travailler plus facilement avec vous.",
  189 : "Nom du fournisseur",
  190 : "Service à domicile",
  191 : "Connexion",
  192 : "Téléphone",
  193 : "Définir ma zone de travail",
  194 : "Définir le logo du fournisseur",
  195 : "Veuillez entrer le nom du fournisseur",
  196 : "Veuillez saisir une description",
  197 : "Veuillez entrer l'adresse",
  198 : "Veuillez télécharger le logo du fournisseur",
  199 : "Veuillez sélectionner la zone de travail",
  200 : "Veuillez sélectionner la catégorie dans laquelle vous travaillerez",
  201 : "Veuillez entrer votre connexion",
  202 : "Mode de paiement",
  203 : "Sous-total",
  204 : "Remise",
  205 : "L'utilisateur doit être fournisseur",
  206 : "Informations sur le fournisseur non trouvées",
  207 : "Êtes-vous sûr de vouloir quitter ?",
  208 : "Sortie",
  209 : "Sur carte",
  210 : "Localisation client",
  211 : "Adresse client",
  212 : "Activer la notification",
  213 : "Fournisseur Disponible/Indisponible",
  214 : "Désactiver temporairement votre compte",
  215 : "TVA/TAXE",
  216 : "Montant total",
  217 : "Réservation à",
  218 : "Nom du client",
  219 : "À l'administrateur",
  220 : "Au fournisseur",
  221 : "TAXES/TVA",
  222 : "Paiements",
  223 : "Solde",
  224 : "Commandes",
  225 : "Mes Produits",
  226 : "Modifier les informations sur les produits",
  227 : "Rechercher dans cette liste",
  228 : "Créer un nouveau produit",
  229 : "Non disponible maintenant",
  230 : "Ajouter l'URL de l'image",
  231 : "Description:",
  232 : "Vous pouvez utiliser des balises HTML (<p>, <br>, <h1> et autres)",
  233 : "Variantes",
  234 : "Ajouter un nouveau groupe",
  235 : "Ajouter une nouvelle variante",
  236 : "Sauvegarder le produit actuel",
  237 : "Ajouter un nouveau produit",
  238 : "Unité",
  239 : "En Stock",
  240 : "pièces",
  241 : "Veuillez sélectionner une variante",
  242 : "Sauvegarder le groupe",
  243 : "Ajouter un groupe",
  244 : "Nom du groupe",
  245 : "Aperçu",
  246 : "URL",
  247 : "Ajouter une image",
  248 : "Nom de la variante",
  249 : "Ajouter une image de la galerie (facultatif)",
  250 : "ou",
  251 : "Ajouter l'URL de l'image (facultatif)",
  252 : "influence sur le prix +/-",
  253 : "Enregistrer la variante",
  254 : "Ajouter une variante",
  255 : "Veuillez sélectionner le stock",
  256 : "l'influence doit commencer par + ou -",
  257 : "Fermer",
  258 : "Ajouter une image depuis la caméra",
  259 : "Ajouter une image de la caméra (facultatif)",
  260 : "Veuillez télécharger l'image",
  261 : "Annuler",
  262 : "Vous avez dépassé la limite du nombre de services. Contactez le support pour plus d'informations.",
  263 : "Arbre de catégorie",
  264 : "Le prix ne peut pas être 0",
  265 : "Vous avez dépassé la limite du nombre d'addons sur un service. Contactez le support pour plus d'informations.",
  266 : "Vous avez dépassé la limite du nombre de produits. Contactez le support pour plus d'informations.",
  267 : "Montant minimum de la commande",
  268 : "Montant maximum de la commande",
  269 : "Paramètres",
  270 : "Définir les montants de commande minimum et maximum",
  271 : "Veuillez saisir le montant minimum de commande",
  272 : "Veuillez saisir le montant maximum de la commande",
  273 : "Autoriser la réservation uniquement si le client se trouve dans la zone de travail du fournisseur",
  274 : "Statut de l'abonnement",
  275 : "Date d'expiration",
  276 : "Souscrit",
  277 : "Non abonné",
  278 : "S'abonner maintenant",
  279 : "Prolongez votre abonnement",
  280 : "",
  281 : "Démarrer l'essai gratuit maintenant",
  282 : "Démarrer",
  283 : "Payer avec",
  284 : "Vos abonnements ont expiré",
  285 : "Expiré",
  286 : "Confirm Subscription. Voulez-vous vous abonner pour deux mois pour",
  287 : "Essai gratuit",
};

Map<int, String> providerArabic = {
  0 : "HANDYMAN",
  1: "الموفر" ,
  2: "إرسال" ,
  3: "اللغة" ,
  4: "اللغة المفضلة" ,
  5: "حدد اللغة المفضلة" ,
  6: "تسجيل الدخول الآن" ,
  7: "البريد الإلكتروني" ,
  8: "أدخل بريدك الإلكتروني" ,
  9: "كلمة المرور" ,
  10: "أدخل كلمة المرور الخاصة بك" ,
  11: "متابعة" ,
  12: "تسجيل" ,
  13: "أو متابعة" ,
  14: "تسجيل" ,
  15: "في أقل من دقيقة" ,
  16: "الاسم" ,
  17: "أدخل الاسم" ,
  18: "تأكيد كلمة المرور" ,
  19: "التحقق" ,
  20: "رقم الهاتف" ,
  21: "أدخل رقم هاتفك" ,
  22: "سنرسل رمز التحقق." ,
  23: "لقد أرسلنا رمز التحقق المكون من 6 أرقام." ,
  24: "أدخل الرمز" ,
  25: "أدخل الرمز المكون من 6 أرقام" ,
  26: "دردشة" ,
  27: "الحجز" ,
  28: "الحساب" ,
  29: "اكتب رسالتك ..." ,
  30: "الحجز" ,
  31: "القادمة" ,
  32: "مكتمل",
  33: "ملغاة",
  34: "جديد" ,
  35: "ملغاة",
  36: "مكتمل" ,
  37: "مقبولة" ,
  38: "اتصل الآن" ,
  39: "رسالة" ,
  40: "قبول" ,
  41: "بدء عمل" ,
  42: "اكتمل العمل" ,
  43: "انتظار التأكيد من العميل" ,
  44: "معرف الحجز" ,
  45: "تم استلام الطلب" ,
  46: "مطلوب في" ,
  47: "تم تأكيد الحجز" ,
  48: "تم التأكيد في",
  49: "بدء عمل" ,
  50: "مجدول في" ,
  51: "اكتملت الوظيفة" ,
  52: "سيظهر الدفع هنا" ,
  53: "التسعير" ,
  54: "الكمية" ,
  55: "مبلغ الضريبة" ,
  56: "المجموع" ,
  57: "عرض الملف الشخصي" ,
  58: "مراجعات",
  59: "اقرأ الكل" ,
  60: "تغيير اللغة" ,
  61: "تعيين لغتك المفضلة" ,
  62: "أدخل بريدك الإلكتروني" ,
  63: "العنوان" ,
  64: "أدخل عنوان العملاء" ,
  65: "الوصف" ,
  66: "أدخل وصفًا موجزًا ​​عنك" ,
  67: "حفظ" ,
  68: "تغيير كلمة المرور" ,
  69: "كلمة المرور الجديدة" ,
  70: "أدخل كلمة المرور" ,
  71: "تأكيد كلمة المرور الجديدة" ,
  72: "تغيير كلمة المرور" ,
  73: "ملفي الشخصي" ,
  74: "كل شيء عنك" ,
  75: "متوسط ​​التقييمات" ,
  76: "تمكين الوضع الداكن" ,
  77: "تعيين الوضع المفضل لك" ,
  78: "المحفظة" ,
  79: "اعرف أرباحك" ,
  80: "محفظتي" ,
  81: "حمل أفضل أعمالك" ,
  82: "سياسة الخصوصية" ,
  83: "تعرف على سياسة الخصوصية الخاصة بنا" ,
  84: "من المعرض",
  85: "من الكاميرا" ,
  86: "تحذف" ,
  87: "ضع غير مرئي" ,
  88: "الرصيد المتاح" ,
  89: "الإخطارات" ,
  90: "الكثير من المعلومات المهمة" ,
  91: "تسجيل الخروج" ,
  92: "إنهاء الجلسة" ,
  93: "الرجاء إدخال البريد الإلكتروني" ,
  94: "الرجاء إدخال كلمة المرور" ,
  95: "المستخدم غير موجود" ,
  96: "تم تعطيل المستخدم. اتصل بالمسؤول للحصول على مزيد من المعلومات." ,
  97: "كلمات المرور غير متساوية" ,
  98: "البريد الإلكتروني خاطئ" ,
  99: "المستخدم لا ينشئ" ,
  100: "لقد تم إنشاء حسابك. بعد الإشراف , سيتم تنشيط حسابك. وسنبلغك بذلك." ,
  101: "الدردشة عبر الإنترنت" ,
  102: "بحث" ,
  103: "رسالة دردشة" ,
  104: "الإخطارات" ,
  105: "الكثير من المعلومات المهمة" ,
  106: "اليوم" ,
  107: "غير موجود ..." ,
  108: "نبذة عنا" ,
  109: "تعرف علينا" ,
  110: "الشروط والأحكام" ,
  111: "الشروط والأحكام المعروفة" ,
  112: "أدخل اسمك" ,
  113: "أدخل تأكيد كلمة المرور" ,
  114: "تم تغيير كلمة المرور" ,
  115: "الرجاء إدخال الاسم" ,
  116: "البيانات المحفوظة" ,
  117: "تم تغيير حالة الحجز" ,
  118: "الآن الحالة:" ,
  119: "حسب الزبون" ,
  120: "حسب المزود" ,
  121: "بواسطة المسؤول",
  122: "تحويل الأموال" ,
  123: "صفحتي" ,
  124: "تحرير معلومات الموفر" ,
  125: "الاثنين" ,
  126: "الثلاثاء" ,
  127: "الأربعاء" ,
  128: "الخميس" ,
  129: "الجمعة" ,
  130: "السبت" ,
  131: "الأحد" ,
  132: "المعارض" ,
  133: "تحرير" ,
  134: "حفظ" ,
  135: "أدخل هاتفك" ,
  136: "أدخل عنوان صفحة الويب الخاصة بك" ,
  137: "أدخل عنوان Instagram الخاص بك" ,
  138: "أدخل عنوان Telegram الخاص بك" ,
  139: "تغيير" ,
  140: "إضافة من لوح المطبخ" ,
  141: "إضافة من الكاميرا" ,
  142: "خدماتي" ,
  143: "تحرير معلومات الخدمة" ,
  144: "خدمة البحث" ,
  145: "هل تريد حذف هذا العنصر؟ لا يمكنك استرداد هذا العنصر." ,
  146: "لا" ,
  147: "هذا هو الوضع التجريبي. لا يمكنك تعديل هذا القسم" ,
  148: "تحرير الخدمة" ,
  149: "مرئي" ,
  150: "تحديد اللغة" ,
  151: "الضرائب" ,
  152: "عنوان الوصف" ,
  153: "السعر" ,
  154: "سعر الخصم" ,
  155: "وحدة السعر" ,
  156: "كل ساعة" ,
  157: "ثابت" ,
  158: "حدد صورة" ,
  159: "الإضافات" ,
  160: "إضافة" ,
  161: "المعرض" ,
  162: "تم حذف الصورة" ,
  163: "إضافة صورة إلى المعرض" ,
  164: "مدة الخدمة" ,
  165: "دقيقة" ,
  166: "مختارة فقط" ,
  167: "الفئات" ,
  168: "الموفرون" ,
  169: "حفظ الخدمة الحالية" ,
  170: "الرجاء إدخال السعر" ,
  171: "الرجاء تحديد المزود" ,
  172: "الرجاء إدخال الفئة" ,
  173: "حفظ الملحق",
  174: "إغلاق" ,
  175: "تحديد" ,
  176: "سيتم حذف الملحق من كافة الخدمات في الموفر الحالي. هل تريد حذف هذا العنصر؟ لن تتمكن من استرداد هذا العنصر." ,
  177: "حذف البيانات" ,
  178: "إنشاء خدمة جديدة" ,
  179: "منطقة عملي" ,
  180: "تحرير منطقة عملك" ,
  181: "حذف الحالي" ,
  182: "هل نسيت كلمة المرور؟" ,
  183: "إعادة تعيين كلمة المرور" ,
  184: "إرسال كلمة مرور جديدة" ,
  185: "تم إرسال البريد الإلكتروني لإعادة تعيين كلمة المرور. يرجى التحقق من بريدك.",
  186: "خلق الوقت" ,
  187: "الرجاء إدخال الهاتف" ,
  188: "يرجى ترك معلومات لنا لتسهيل العمل معك." ,
  189: "اسم المزود" ,
  190: "خدمة منزلية" ,
  191: "تسجيل الدخول" ,
  192: "الهاتف" ,
  193: "تعيين منطقة العمل الخاصة بي" ,
  194: "تعيين شعار الموفر" ,
  195: "الرجاء إدخال اسم المزود" ,
  196: "الرجاء إدخال الوصف" ,
  197: "الرجاء إدخال العنوان" ,
  198: "الرجاء تحميل شعار الموفر" ,
  199: "الرجاء تحديد منطقة العمل" ,
  200: "الرجاء تحديد الفئة التي ستعمل بها" ,
  201: "الرجاء إدخال تسجيل الدخول" ,
  202: "طريقة الدفع" ,
  203: "المجموع الفرعي" ,
  204: "خصم" ,
  205: "يجب أن يكون المستخدم مزودًا" ,
  206: "لم يتم العثور على معلومات الموفر" ,
  207: "هل أنت متأكد أنك تريد الخروج؟",
  208: "خروج" ,
  209: "على الخريطة" ,
  210: "موقع العميل" ,
  211: "عنوان العميل" ,
  212: "تمكين الإعلام" ,
  213: "الموفر متوفر / غير متوفر" ,
  214: "تعطيل مؤقت لحسابك" ,
  215: "ضريبة القيمة المضافة / الضرائب" ,
  216: "المبلغ الإجمالي" ,
  217: "الحجز في" ,
  218: "اسم العميل" ,
  219: "إلى المسؤول",
  220: "إلى المزود" ,
  221: "ضريبة / ضريبة القيمة المضافة" ,
  222: "العوائد" ,
  223: "التوازن" ,
  224: "أوامر" ,
  225: "منتجاتي" ,
  226: "تحرير معلومات المنتجات" ,
  227: "بحث في هذه القائمة" ,
  228: "إنشاء منتج جديد" ,
  229: "غير متوفر الآن" ,
  230: "إضافة عنوان URL للصورة" ,
  231: "الوصف:" ,
  232: "يمكنك استخدام علامات HTML (<p> , <br> , <h1> وغيرها)" ,
  233: "المتغيرات" ,
  234: "إضافة مجموعة جديدة" ,
  235: "إضافة متغير جديد" ,
  236: "حفظ المنتج الحالي" ,
  237: "إضافة منتج جديد" ,
  238: "الوحدة" ,
  239: "متوفر",
  240: "قطعة" ,
  241: "الرجاء تحديد البديل" ,
  242: "حفظ المجموعة" ,
  243: "إضافة مجموعة" ,
  244: "اسم المجموعة" ,
  245: "معاينة" ,
  246: "URL" ,
  247: "إضافة صورة" ,
  248: "الاسم المتغير" ,
  249: "إضافة صورة من المعرض (اختياري)" ,
  250: "أو" ,
  251: "إضافة عنوان URL للصورة (اختياري)" ,
  252: "التأثير على السعر +/-" ,
  253: "حفظ المتغير" ,
  254: "إضافة متغير" ,
  255: "الرجاء تحديد المخزون" ,
  256: "يجب أن يبدأ التأثير بـ + أو -" ,
  257: "إغلاق" ,
  258: "إضافة صورة من الكاميرا" ,
  259: "إضافة صورة من الكاميرا (اختياري)" ,
  260: "الرجاء تحميل الصورة" ,
  261: "إلغاء" ,
  262: "لقد تجاوزت الحد الأقصى لعدد الخدمات. لمزيد من المعلومات اتصل بالدعم." ,
  263: "شجرة الفئات" ,
  264: "لا يمكن أن يكون السعر 0" ,
  265: "لقد تجاوزت الحد الأقصى لعدد الوظائف الإضافية في خدمة واحدة. اتصل بالدعم لمزيد من المعلومات." ,
  266: "لقد تجاوزت الحد الأقصى لعدد المنتجات. اتصل بالدعم لمزيد من المعلومات." ,
  267: "الحد الأدنى لمبلغ الطلب" ,
  268: "الحد الأقصى لمبلغ الطلب" ,
  269: "إعدادات" ,
  270: "تعيين الحد الأدنى لمبالغ الأمر amd" ,
  271: "الرجاء إدخال الحد الأدنى لمبلغ الطلب" ,
  272: "الرجاء إدخال الحد الأقصى لمبلغ الطلب" ,
  273: "السماح بالحجز فقط إذا كان العميل موجودًا في منطقة عمل المزود" ,
  274: "حالة الاشتراك" ,
  275: "تاريخ انتهاء الصلاحية" ,
  276: "مشترك" ,
  277: "غير مشترك" ,
  278: "اشترك الآن" ,
  279: "تمديد اشتراكك" ,
  280: "" ,
  281: "ابدأ الإصدار التجريبي المجاني الآن" ,
  282: "ابدأ" ,
  283: "الدفع" ,
  284: "اشتراكاتك انتهت" ,
  285: "منتهية الصلاحية" ,
  286: "تأكيد الاشتراك. هل تريد الاشتراك لمدة شهرين بـ",
  287: "تجربة مجانية" ,
};

Map<int, String> providerPort = {
  0 : "HANDYMAN",
  1: "FORNECEDOR",
  2: "ENVIAR",
  3: "Idioma",
  4: "Idioma preferido",
  5: "Selecione o idioma preferido",
  6: "Faça login agora",
  7: "Email",
  8: "Digite seu e-mail",
  9: "Senha",
  10: "Digite sua senha",
  11: "CONTINUAR",
  12: "CADASTRE-SE",
  13: "ou continue com",
  14: "Registre-se",
  15: "em menos de um minuto",
  16: "Nome",
  17: "Digite o nome",
  18: "Confirme a senha",
  19: "Verificação",
  20: "Número de telefone",
  21: "Digite o seu número de telefone",
  22: "Enviaremos o código de verificação.",
  23: "Enviamos um código de verificação de 6 dígitos.",
  24: "Insira o código",
  25: "Insira o código de 6 dígitos",
  26: "Bate-papo",
  27: "Reserva",
  28: "Conta",
  29: "Escreva sua mensagem ...",
  30: "Reserva",
  31: "Próximos",
  32: "Concluído",
  33: "Cancelado",
  34: "Novo",
  35: "Cancelado",
  36: "Concluído",
  37: "Aceito",
  38: "Ligue agora",
  39: "Mensagem",
  40: "Aceitar",
  41: "Começar um trabalho",
  42: "Trabalho concluído",
  43: "Aguardando confirmação do cliente",
  44: "ID de reserva",
  45: "Solicitação recebida",
  46: "Solicitado em",
  47: "Reserva confirmada",
  48: "Confirmado em",
  49: "Começar um trabalho",
  50: "Programado em",
  51: "Trabalho concluído",
  52: "O pagamento aparecerá aqui",
  53: "Preços",
  54: "Quantidade",
  55: "Valor do imposto",
  56: "Total",
  57: "Ver perfil",
  58: "comentários",
  59: "Ler tudo",
  60: "Alterar idioma",
  61: "Definir seu idioma preferido",
  62: "Digite seu e-mail",
  63: "Endereço",
  64: "Insira o endereço dos clientes",
  65: "Descrição",
  66: "Insira uma breve descrição sobre você",
  67: "SALVAR",
  68: "Alterar senha",
  69: "Nova senha",
  70: "Digite a senha",
  71: "Confirme a nova senha",
  72: "ALTERAR SENHA",
  73: "Meu Perfil",
  74: "Tudo sobre você",
  75: "Avaliações médias",
  76: "Habilitar Modo Escuro",
  77: "Definir seu modo favorito",
  78: "Carteira",
  79: "Conheça seus ganhos",
  80: "Meu portfólio",
  81: "Envie seus melhores trabalhos",
  82: "Política de privacidade",
  83: "Conhecemos nossa Política de Privacidade",
  84: "Da Galeria",
  85: "Da câmera",
  86: "Excluir",
  87: "Definir invisível",
  88: "Saldo Disponível",
  89: "Notificações",
  90: "Muitas informações importantes",
  91: "Sair",
  92: "Terminar a sessão",
  93: "Digite o e-mail",
  94: "Digite a senha",
  95: "Usuário não encontrado",
  96: "O usuário está desativado. Conecte-se ao administrador para obter mais informações.",
  97: "As senhas não são iguais",
  98: "Email está errado",
  99: "O usuário não cria",
  100: "Sua conta foi criada. Após moderação sua conta será ativada. Nós o informaremos.",
  101: "Conversando online",
  102: "Pesquisar",
  103: "Mensagem de bate-papo",
  104: "Notificações",
  105: "Muitas informações importantes",
  106: "Hoje",
  107: "Não encontrado ...",
  108: "Sobre nós",
  109: "Conhecidos sobre nós",
  110: "Termos e Condições",
  111: "Termos e Condições Conhecidos",
  112: "Digite seu nome",
  113: "Digite a senha de confirmação",
  114: "Senha alterada",
  115: "Insira o nome",
  116: "Dados salvos",
  117: "O status da reserva foi alterado",
  118: "Status agora:",
  119: "por cliente",
  120: "por provedor",
  121: "pelo administrador",
  122: "Transferência de dinheiro",
  123: "Minha página",
  124: "Editar informações do provedor",
  125: "segunda-feira",
  126: "terça-feira",
  127: "quarta-feira",
  128: "quinta-feira",
  129: "sexta-feira",
  130: "sábado",
  131: "domingo",
  132: "Galerias",
  133: "Editar",
  134: "Salvar",
  135: "Digite seu telefone",
  136: "Digite o endereço da sua página da web",
  137: "Digite seu endereço do Instagram",
  138: "Digite seu endereço de telegrama",
  139: "Mudar",
  140: "Adicionar da cozinha",
  141: "Adicionar da câmera",
  142: "Meus serviços",
  143: "Editar informações do serviço",
  144: "Serviço de pesquisa",
  145: "Deseja excluir este item? Você não poderá recuperar este item.",
  146: "Não",
  147: "Este é o modo de demonstração. Você não pode modificar esta seção",
  148: "Editar Serviço",
  149: "Visível",
  150: "Selecione o idioma",
  151: "Imposto",
  152: "Título da descrição",
  153: "Preço",
  154: "Preço com desconto",
  155: "Unidade de preço",
  156: "De hora em hora",
  157: "Fixo",
  158: "Selecionar imagem",
  159: "Complementos",
  160: "Adicionar addon",
  161: "Galeria",
  162: "Imagem excluída",
  163: "Adicionar imagem à galeria",
  164: "Duração do serviço",
  165: "min",
  166: "Apenas selecionado",
  167: "Categorias",
  168: "Provedores",
  169: "Salvar serviço atual",
  170: "Insira o preço",
  171: "Selecione o provedor",
  172: "Por favor, insira a categoria",
  173: "Salvar addon",
  174: "Fechar",
  175: "Selecionar",
  176: "O complemento será excluído de todos os serviços do provedor atual. Deseja excluir este item? Não será possível recuperar este item.",
  177: "Dados excluídos",
  178: "Criar novo serviço",
  179: "Minha Área de Trabalho",
  180: "Edite sua área de trabalho",
  181: "Excluir atual",
  182: "Esqueceu a senha?",
  183: "Redefinir senha",
  184: "Enviar nova senha",
  185: "E-mail de redefinição de senha enviado. Verifique seu e-mail.",
  186: "Criação de tempo",
  187: "Digite o telefone",
  188: "Por favor, deixe informações para que seja mais fácil trabalharmos com você.",
  189: "Nome do Provedor",
  190: "Serviço doméstico",
  191: "Login",
  192: "Telefone",
  193: "Definir minha área de trabalho",
  194: "Definir logotipo do provedor",
  195: "Digite o nome do provedor",
  196: "Por favor, digite a descrição",
  197: "Digite o endereço",
  198: "Faça upload do logotipo do provedor",
  199: "Selecione a área de trabalho",
  200: "Selecione a categoria em que você trabalhará",
  201: "Por favor, digite o login",
  202: "Método de pagamento",
  203: "Subtotal",
  204: "Desconto",
  205: "O usuário deve ser o provedor",
  206: "Informações do provedor não encontradas",
  207: "Tem certeza que deseja sair?",
  208: "Sair",
  209: "No mapa",
  210: "Localização do cliente",
  211: "Endereço do cliente",
  212: "Habilitar Notificar",
  213: "Provedor disponível / indisponível",
  214: "Desativar temporariamente sua conta",
  215: "VAT / TAX",
  216: "Montante total",
  217: "Reserva em",
  218: "Nome do cliente",
  219: "Para Admin",
  220: "Para o Provedor",
  221: "TAX / VAT",
  222: "Pagamentos",
  223: "Equilíbrio",
  224: "Pedidos",
  225: "Meus produtos",
  226: "Editar informações de produtos",
  227: "Pesquisar nesta lista",
  228: "Criar novo produto",
  229: "Não disponível agora",
  230: "Adicionar URL de imagem",
  231: "Descrição:",
  232: "Você pode usar tags HTML (<p>, <br>, <h1> e outras)",
  233: "Variantes",
  234: "Adicionar novo grupo",
  235: "Adicionar nova variante",
  236: "Salvar produto atual",
  237: "Adicionar Novo Produto",
  238: "Unidade",
  239: "Em estoque",
  240: "pcs",
  241: "Selecione a variante",
  242: "Salvar grupo",
  243: "Adicionar grupo",
  244: "Nome do grupo",
  245: "Pré-visualizar",
  246: "URL",
  247: "Adicionar imagem",
  248: "Nome da variante",
  249: "Adicionar imagem da galeria (opcional)",
  250: "ou",
  251: "Adicionar URL de imagem (opcional)",
  252: "influência no preço +/-",
  253: "Salvar variante",
  254: "Adicionar variante",
  255: "Selecione o estoque",
  256: "a influência deve começar com + ou -",
  257: "Fechar",
  258: "Adicionar imagem da câmera",
  259: "Adicionar imagem da câmera (opcional)",
  260: "Faça upload da imagem",
  261 : "Cancelar",
  262 : "Você excedeu o limite no número de serviços. Entre em contato com o suporte para obter mais informações.",
  263 : "Árvore de categorias",
  264 : "O preço não pode ser 0",
  265 : "Você excedeu o limite no número de complementos em um serviço. Entre em contato com o suporte para obter mais informações.",
  266 : "Você excedeu o limite no número de produtos. Entre em contato com o suporte para obter mais informações.",
  267 : "Valor mínimo do pedido",
  268 : "Valor máximo do pedido",
  269 : "Configurações",
  270 : "Definir valores mínimos e máximos de pedidos",
  271 : "Por favor, insira o valor mínimo do pedido",
  272 : "Por favor, insira o valor máximo do pedido",
  273 : "Permitir reserva somente se o cliente estiver localizado na área de trabalho do provedor",
  274: "Status da Assinatura",
  275 : "Data de expiração",
  276: "Assinado",
  277: "Não Assinado",
  278 : "Assine agora",
  279 : "Estender sua assinatura",
  280: "",
  281: "Iniciar teste gratuito agora",
  282 : "Iniciar",
  283 : "Pagar com",
  284 : "Suas assinaturas expiraram",
  285 : "Expirado",
  286 : "Confirmar Assinatura. Deseja assinar Dois meses para",
  287 : "Teste Gratuito",
};

Map<int, String> providerRus = {
  0 : "HANDYMAN",
  1: "ПРОВАЙДЕР",
  2: "ОТПРАВИТЬ",
  3: "Язык",
  4: "Предпочитаемый язык",
  5: "Выберите предпочтительный язык",
  6: "Войти сейчас",
  7: "Электронная почта",
  8: "Введите свой адрес электронной почты",
  9: "Пароль",
  10: "Введите пароль",
  11: "ПРОДОЛЖИТЬ",
  12: "РЕГИСТРАЦИЯ",
  13: "или продолжить с",
  14: "Регистр",
  15: "менее чем за минуту",
  16: "Имя",
  17: "Введите имя",
  18: "Подтвердите пароль",
  19: "Проверка",
  20: "Номер телефона",
  21: "Введите свой номер телефона",
  22: "Мы отправим проверочный код.",
  23: "Мы отправили шестизначный проверочный код.",
  24: "Введите код",
  25: "Введите шестизначный код",
  26: "Чат",
  27: "Бронирование",
  28: "Учетная запись",
  29: "Напишите свое сообщение ...",
  30: "Бронирование",
  31: "Предстоящие",
  32: "Завершено",
  33: "Отменено",
  34: "Новый",
  35: "Отменено",
  36: "Завершено",
  37: "Принято",
  38: "Звоните сейчас",
  39: "Сообщение",
  40: "Принять",
  41: "Начать работу",
  42: "Работа завершена",
  43: "Ожидание подтверждения от клиента",
  44: "Идентификатор бронирования",
  45: "Запрос получен",
  46: "Запрошено",
  47: "Бронирование подтверждено",
  48: "Подтверждено",
  49: "Начать работу",
  50: "По расписанию",
  51: "Работа завершена",
  52: "Платеж появится здесь",
  53: "Цены",
  54: "Количество",
  55: "Сумма налога",
  56: "Итого",
  57: "Посмотреть профиль",
  58: "отзывы",
  59: "Прочитать все",
  60: "Сменить язык",
  61: "Установите предпочитаемый язык",
  62: "Введите свой адрес электронной почты",
  63: "Адрес",
  64: "Введите адрес для клиентов",
  65: "Описание",
  66: "Введите краткое описание о себе",
  67: "СОХРАНИТЬ",
  68: "Сменить пароль",
  69: "Новый пароль",
  70: "Введите пароль",
  71: "Подтвердите новый пароль",
  72: "ИЗМЕНИТЬ ПАРОЛЬ",
  73: "Мой профиль",
  74: "Все о тебе",
  75: "Средний рейтинг",
  76: "Включить темный режим",
  77: "Установите любимый режим",
  78: "Кошелек",
  79: "Знай свой заработок",
  80: "Мое портфолио",
  81: "Загрузите свои лучшие работы",
  82: "Политика конфиденциальности",
  83: "Известная наша Политика конфиденциальности",
  84: "Из галереи",
  85: "С камеры",
  86: "Удалить",
  87: "Сделать невидимым",
  88: "Доступный остаток",
  89: "Уведомления",
  90: "Много важной информации",
  91: "Выйти",
  92: "Завершить сеанс",
93: "Пожалуйста, введите адрес электронной почты",
94: "Пожалуйста, введите пароль",
95: "Пользователь не найден",
96: "Пользователь отключен. Для получения дополнительной информации обратитесь к администратору.",
97: "Пароли не равны",
98: "Неправильный адрес электронной почты",
99: "Пользователь не создает",
100: "Вы создали аккаунт. После модерации ваш аккаунт будет активирован. Мы сообщим вам.",
101: "Общение в чате",
102: "Поиск",
103: "Сообщение чата",
104: "Уведомления",
105: "Много важной информации",
106: "Сегодня",
107: "Не найдено ...",
108: "О нас",
109: "О нас известно",
110: "Положения и условия",
111: "Известные положения и условия",
112: "Введите свое имя",
113: "Введите пароль для подтверждения",
114: "Пароль изменен",
115: "Пожалуйста, введите имя",
116: "Данные сохранены",
117: "Статус бронирования изменен",
118: "Сейчас статус:",
119: "по заказчику",
120: "по провайдеру",
121: "администратором",
122: "Денежный перевод",
123: "Моя страница",
124: "Изменить информацию о поставщике",
125: "Понедельник",
126: "Вторник",
127: "Среда",
128: "Четверг",
129: "Пятница",
130: "Суббота",
131: "Воскресенье",
132: "Галереи",
133: "Редактировать",
134: "Сохранить",
135: "Введите свой телефон",
136: "Введите адрес своей веб-страницы",
137: "Введите свой адрес в Instagram",
138: "Введите свой Telegram-адрес",
139: "Изменить",
140: "Добавить с камбуза",
141: "Добавить с камеры",
142: "Мои услуги",
143: "Редактировать служебную информацию",
144: "Служба поиска",
145: "Удалить этот элемент? Восстановить его не удастся.",
146: "Нет",
147: "Это демонстрационный режим. Вы не можете изменять этот раздел",
148: "Редактировать службу",
149: "Видимый",
150: "Выбрать язык",
151: "Налог",
152: "Заголовок описания",
153: "Цена",
154: "Цена со скидкой",
155: "Единица цены",
156: "Ежечасно",
157: "Фиксированный",
158: "Выбрать изображение",
159: "Дополнения",
160: "Добавить аддон",
161: "Галерея",
162: "Изображение удалено",
163: "Добавить изображение в галерею",
164: "Срок службы",
165: "мин",
166: "Только выбрано",
167: "Категории",
168: "Провайдеры",
169: "Сохранить текущую услугу",
170: "Пожалуйста, введите цену",
171: "Выберите провайдера",
172: "Укажите категорию",
173: "Сохранить аддон",
174: "Закрыть",
175: "Выбрать",
176: "Дополнение будет удалено из всех сервисов текущего провайдера. Вы хотите удалить этот элемент? Вы не сможете восстановить этот элемент.",
177: "Данные удалены",
178: "Создать новую услугу",
179: "Моя рабочая зона",
180: "Редактировать рабочую область",
181: "Удалить текущий",
182: "Забыли пароль?",
183: "Сбросить пароль",
184: "Отправить новый пароль",
185: "Сообщение для сброса пароля отправлено. Пожалуйста, проверьте свою почту",
  186: "Время создания",
187: "Пожалуйста, введите телефон",
188: "Пожалуйста, оставьте нам информацию, чтобы нам было проще работать с вами",
189: "Название провайдера",
190: "Обслуживание на дому",
191: "Вход",
192: "Телефон",
193: "Установить мою рабочую область",
194: "Установить логотип поставщика",
195: "Пожалуйста, введите имя провайдера",
196: "Введите описание",
197: "Пожалуйста, введите адрес",
198: "Загрузите логотип поставщика",
199: "Выберите рабочую область",
200: "Выберите категорию, в которой вы будете работать",
201: "Пожалуйста, введите логин",
202: "Способ оплаты",
203: "Итого",
204: "Скидка",
  205: "Пользователь должен быть Провайдером",
206: "Информация о поставщике не найдена",
207: "Вы уверены, что хотите выйти?",
208: "Выход",
209: "На карте",
210: "Местоположение клиента",
211: "Адрес клиента",
212: "Включить уведомление",
213: "Поставщик доступен / недоступен",
214: "Временное отключение учетной записи",
215: "НДС / НАЛОГ",
216: "Общая сумма",
217: "Бронирование в",
218: "Имя клиента",
219: "Администратору",
220: "Провайдеру",
221: "НАЛОГ / НДС",
222: "Выплаты",
223: "Равновесие",
224: "Заказы",
225: "Мои товары",
226: "Редактировать информацию о товарах",
227: "Искать в этом списке",
228: "Создать новый продукт",
229: "Сейчас недоступно",
230: "Добавить URL изображения",
231: "Описание:",
232: "Вы можете использовать HTML-теги (<p>, <br>, <h1> и другие)",
233: "Варианты",
234: "Добавить новую группу",
235: "Добавить новый вариант",
236: "Сохранить текущий продукт",
237: "Добавить новый продукт",
238: "Единица",
239: "В наличии",
240: "шт",
241: "Выберите вариант",
242: "Сохранить группу",
243: "Добавить группу",
244: "Название группы",
245: "Предварительный просмотр",
246: "URL",
247: "Добавить изображение",
248: "Название варианта",
249: "Добавить изображение из галереи (необязательно)",
250: "или",
251: "Добавить URL изображения (необязательно)",
252: "влияние на цену +/-",
253: "Сохранить вариант",
254: "Добавить вариант",
255: "Пожалуйста, выберите сток",
256: "влияние должно начинаться с + или -",
257: "Закрыть",
258: "Добавить изображение с камеры",
259: "Добавить изображение с камеры (необязательно)",
260: "Загрузите изображение",
261 : "Отмена",
262 : "Вы превысили лимит на количество сервисов. Свяжитесь со службой поддержки для получения дополнительной информации.",
263: "Дерево категорий",
264 : "Цена не может быть 0",
265 : "Вы превысили ограничение на количество надстроек в одном сервисе. Свяжитесь со службой поддержки для получения дополнительной информации.",
266 : "Вы превысили лимит на количество продуктов. Свяжитесь со службой поддержки для получения дополнительной информации.",
267 : "Минимальная сумма заказа",
268 : "Максимальная сумма заказа",
269 : "Настройки",
270 : "Установить минимальную и максимальную суммы заказа",
271 : "Пожалуйста, введите минимальную сумму заказа",
272 : "Пожалуйста, введите максимальную сумму заказа",
273 : "Разрешить бронирование, только если клиент находится в рабочей зоне провайдера",
  274 : "Статус подписки",
  275 : "Срок годности",
  276 : "Подписан",
  277 : "Не подписан",
  278 : "Подпишитесь сейчас",
  279 : "Продлить подписку",
  280 : "",
  281 : "Начать бесплатную пробную версию сейчас",
  282 : "Старт",
  283 : "Оплатить",
  284 : "Срок действия вашей подписки истек",
  285 : "Просрочено",
  286 : "Подтвердить подписку. Вы хотите подписаться на два месяца для",
  287: "Бесплатная пробная версия",
};

Map<int, String> providerHindi = {
  0 : "HANDYMAN",
  1: "प्रदाता",
  2: "सबमिट करें",
  3: "भाषा",
  4: "पसंदीदा भाषा",
  5: "पसंदीदा भाषा चुनें",
  6: "अभी साइन इन करें",
  7: "ईमेल",
  8: "अपना ईमेल दर्ज करें",
  9: "पासवर्ड",
  10: "अपना पासवर्ड दर्ज करें",
  11: "जारी रखें",
  12: "रजिस्टर",
  13: "या जारी रखें",
  14: "रजिस्टर",
  15: "एक मिनट से भी कम समय में",
  16: "नाम",
  17: "नाम दर्ज करें",
  18: "पासवर्ड की पुष्टि करें",
  19: "सत्यापन",
  20: "फोन नंबर",
  21: "अपना फोन नंबर दर्ज करें",
  22 : "हम सत्यापन कोड भेजेंगे।",
  23 : "हमने 6 अंकों का सत्यापन कोड भेजा है।",
  24: "कोड दर्ज करें",
  25: "6 अंकों का कोड दर्ज करें",
  26: "चैट",
  27: "बुकिंग",
  28: "खाता",
  29: "अपना संदेश लिखें ...",
  30: "बुकिंग",
  31: "आगामी",
  32: "पूर्ण",
  33: "रद्द",
  34: "नया",
  35 : "रद्द किया गया",
  36: "पूर्ण",
  37: "स्वीकृत",
  38: "अभी कॉल करें",
  39: "संदेश",
  40: "स्वीकार करें",
  41: "नौकरी शुरू करें",
  42: "काम पूरा",
  43 : "ग्राहक से पुष्टि की प्रतीक्षा में",
  44: "बुकिंग आईडी",
  45: "अनुरोध प्राप्त हुआ",
  46: "अनुरोध किया गया",
  47 : "बुकिंग कन्फर्म",
  48: "पुष्टि की गई",
  49: "नौकरी शुरू करें",
  50: "अनुसूचित",
  51: "काम पूरा हुआ",
  52: "भुगतान यहां दिखाई देगा",
  53: "मूल्य निर्धारण",
  54: "मात्रा",
  55: "कर राशि",
  56: "कुल",
  57: "प्रोफाइल देखें",
  58: "समीक्षाएं",
  59: "सभी पढ़ें",
  60: "भाषा बदलें",
  61: "अपनी पसंदीदा भाषा सेट करें",
  62: "अपना ईमेल दर्ज करें",
  63: "पता",
  64: "ग्राहकों के लिए पता दर्ज करें",
  65: "विवरण",
  66: "अपने बारे में संक्षिप्त विवरण दर्ज करें",
  67: "बचाओ",
  68: "पासवर्ड बदलें",
  69: "नया पासवर्ड",
  70: "पासवर्ड दर्ज करें",
  71: "नए पासवर्ड की पुष्टि करें",
  72: "पासवर्ड बदलें",
  73 : "माई प्रोफाइल",
  74: "आपके बारे में सब कुछ",
  75: "औसत रेटिंग",
  76: "डार्क मोड सक्षम करें",
  77: "आप पसंदीदा मोड सेट करें",
  78: "वॉलेट",
  79 : "अपनी कमाई जानो",
  80: "मेरा पोर्टफोलियो",
  81 : "अपना सर्वश्रेष्ठ कार्य अपलोड करें",
  82: "गोपनीयता नीति",
  83: "हमारी गोपनीयता नीति को जानें",
  84 : "गैलरी से",
  85: "कैमरा से",
  86: "हटाएं",
  87: "अदृश्य सेट करें",
  88: "उपलब्ध शेष",
  89: "सूचनाएं",
  90: "बहुत सारी महत्वपूर्ण जानकारी",
  91 : "लॉग आउट",
  92: "सत्र समाप्त करें",
93 : "कृपया ईमेल दर्ज करें",
94: "कृपया पासवर्ड दर्ज करें",
95: "उपयोगकर्ता नहीं मिला",
96: "उपयोगकर्ता अक्षम है। अधिक जानकारी के लिए व्यवस्थापक से कनेक्ट करें।",
97: "पासवर्ड समान नहीं हैं",
98: "ईमेल गलत हैं",
99: "उपयोगकर्ता नहीं बनाते",
100 : "आपने खाता बना लिया। मॉडरेशन के बाद आपका खाता सक्रिय हो जाएगा। हम आपको सूचित करेंगे।",
101 : "ऑनलाइन चैटिंग",
102: "खोज",
103: "चैट संदेश",
104: "सूचनाएं",
105: "बहुत सारी महत्वपूर्ण जानकारी",
106: "आज",
107: "नहीं मिला ...",
108: "हमारे बारे में",
109 : "हमारे बारे में जाना जाता है",
110: "नियम और शर्तें",
111 : "ज्ञात नियम और शर्तें",
112: "अपना नाम दर्ज करें",
113: "पासवर्ड की पुष्टि करें दर्ज करें",
114: "पासवर्ड बदल गया",
115: "कृपया नाम दर्ज करें",
116: "डेटा सहेजा गया",
117 : "बुकिंग की स्थिति बदली गई",
118: "अब स्थिति:",
119: "ग्राहक द्वारा",
120: "प्रदाता द्वारा",
121: "व्यवस्थापक द्वारा",
122 : "मनी ट्रांसफर",
123: "मेरा पेज",
124 : "प्रदाता जानकारी संपादित करें",
125: "सोमवार",
126: "मंगलवार",
127: "बुधवार",
128: "गुरुवार",
129: "शुक्रवार",
130: "शनिवार",
131 : "रविवार",
132 : "दीर्घाएँ",
133: "संपादित करें",
134: "सहेजें",
135 : "अपना फोन दर्ज करें",
136 : "अपना वेब पेज पता दर्ज करें",
137: "अपना इंस्टाग्राम पता दर्ज करें",
138: "अपना टेलीग्राम पता दर्ज करें",
139: "बदलें",
140: "गैली से जोड़ें",
141 : "कैमरा से जोड़ें",
142: "मेरी सेवाएं",
143 : "सेवा जानकारी संपादित करें",
144: "खोज सेवा",
145 : "क्या आप इस आइटम को हटाना चाहते हैं? आप इस आइटम को पुनर्प्राप्त नहीं कर सकते।",
146: "नहीं",
147: "यह डेमो मोड है। आप इस अनुभाग को संशोधित नहीं कर सकते",
148: "सेवा संपादित करें",
149: "दृश्यमान",
150: "भाषा चुनें",
151 : "टैक्स",
152: "विवरण शीर्षक",
153 : "कीमत",
154 : "डिस्काउंट प्राइस",
155 : "मूल्य इकाई",
156: "प्रति घंटा",
157: "फिक्स्ड",
158: "छवि का चयन करें",
159 : "एडॉन्स",
160 : "एडऑन जोड़ें",
161 : "गैलरी",
162: "छवि हटाई गई",
163: "गैलरी में छवि जोड़ें",
164 : "सेवा अवधि",
165: "मिनट",
166 : "केवल चयनित",
167: "श्रेणियाँ",
168: "प्रदाता",
169: "वर्तमान सेवा सहेजें",
170: "कृपया कीमत दर्ज करें",
171: "कृपया प्रदाता का चयन करें",
172: "कृपया श्रेणी दर्ज करें",
173 : "सहेजें ऐडऑन",
174: "बंद करें",
175: "चुनें",
176 : "Addon वर्तमान प्रदाता में सभी सेवाओं से हटा दिया जाएगा। क्या आप इस आइटम को हटाना चाहते हैं? आप इस आइटम को पुनर्प्राप्त नहीं कर पाएंगे।",
177: "डेटा हटा दिया गया",
178: "नई सेवा बनाएं",
179: "मेरा कार्य क्षेत्र",
180: "अपना कार्य क्षेत्र संपादित करें",
181: "वर्तमान हटाएं",
  182: "पासवर्ड भूल गए?",
  183: "पासवर्ड रीसेट करें",
  184 : "नया पासवर्ड भेजें",
  185 : "रीसेट पासवर्ड ईमेल भेजा गया। कृपया अपना मेल जांचें।",
  186: "समय निर्माण",
  187: "कृपया फोन दर्ज करें",
  188 : "कृपया हमारे लिए जानकारी छोड़ दें ताकि हमारे लिए आपके साथ काम करना आसान हो सके।",
  189 : "प्रदाता का नाम",
  190 : "होम सर्विस",
  191: "लॉगिन",
  192: "फोन",
  193: "मेरा कार्य क्षेत्र निर्धारित करें",
  194 : "प्रदाता लोगो सेट करें",
  195 : "कृपया प्रदाता का नाम दर्ज करें",
  196: "कृपया विवरण दर्ज करें",
  197: "कृपया पता दर्ज करें",
  198: "कृपया प्रदाता लोगो अपलोड करें",
  199: "कृपया कार्य क्षेत्र का चयन करें",
  200: "कृपया उस श्रेणी का चयन करें जहाँ आप काम करेंगे",
  201 : "कृपया लॉगिन दर्ज करें",
  202: "भुगतान विधि",
  203 : "सबटोटल",
  204: "छूट",
  205 : "उपयोगकर्ता प्रदाता होना चाहिए",
  206: "प्रदाता की जानकारी नहीं मिली",
  207 : "क्या आप वाकई बाहर निकलना चाहते हैं?",
  208: "बाहर निकलें",
  209: "मानचित्र पर",
  210 : "ग्राहक स्थान",
  211: "ग्राहक का पता",
  212: "सूचना सक्षम करें",
  213 : "प्रदाता उपलब्ध/अनुपलब्ध",
  214 : "अपने खाते को अस्थायी रूप से अक्षम करें",
  215 : "वैट/टैक्स",
  216: "कुल राशि",
  217: "बुकिंग एट",
  218: "ग्राहक का नाम",
  219 : "टू एडमिन",
  220: "प्रदाता के लिए",
  221 : "कर/वैट",
  222: "पेआउट",
  223: "बैलेंस",
  224: "आदेश",
  225 : "मेरे उत्पाद",
  226: "उत्पाद जानकारी संपादित करें",
  227: "इस सूची में खोजें",
  228: "नया उत्पाद बनाएं",
  229: "अभी उपलब्ध नहीं है",
  230 : "छवि URL जोड़ें",
  231: "विवरण:",
  232 : "आप HTML टैग्स (<p>, <br>, <h1> और अन्य) का उपयोग कर सकते हैं",
  233 : "वेरिएंट",
  234 : "नया समूह जोड़ें",
  235 : "नया संस्करण जोड़ें",
  236 : "वर्तमान उत्पाद सहेजें",
  237 : "नया उत्पाद जोड़ें",
  238: "यूनिट",
  239: "स्टॉक में",
  240: "पीसी",
  241 : "कृपया प्रकार चुनें",
  242: "समूह सहेजें",
  243: "समूह जोड़ें",
  244: "समूह का नाम",
  245: "पूर्वावलोकन",
  246: "यूआरएल",
  247: "छवि जोड़ें",
  248: "संस्करण नाम",
  249: "गैलरी से छवि जोड़ें (वैकल्पिक)",
  250: "या",
  251 : "छवि URL जोड़ें (वैकल्पिक)",
  252 : "कीमत +/- पर प्रभाव",
  253 : "वैरिएंट सहेजें",
  254 : "वैरिएंट जोड़ें",
  255: "कृपया स्टॉक चुनें",
  256 : "प्रभाव + या - से शुरू होना चाहिए",
  257: "बंद करें",
  258 : "कैमरे से छवि जोड़ें",
  259: "कैमरे से छवि जोड़ें (वैकल्पिक)",
  260: "कृपया छवि अपलोड करें",
  261: "रद्द करें",
  262 : "आपने सेवाओं की संख्या की सीमा पार कर ली है। अधिक जानकारी के लिए समर्थन से संपर्क करें।",
  263 : "श्रेणी वृक्ष",
  264 : "कीमत 0 नहीं हो सकती",
  265 : "आप एक सेवा पर ऐडऑन की संख्या की सीमा पार कर चुके हैं। अधिक जानकारी के लिए समर्थन से संपर्क करें।",
  266 : "आप उत्पादों की संख्या की सीमा पार कर चुके हैं। अधिक जानकारी के लिए समर्थन से संपर्क करें।",
  267: "न्यूनतम आदेश राशि",
  268: "अधिकतम आदेश राशि",
  269: "सेटिंग्स",
  270 : "न्यूनतम और अधिकतम आदेश मात्रा निर्धारित करें",
  271 : "कृपया न्यूनतम आदेश राशि दर्ज करें",
  272 : "कृपया अधिकतम आदेश राशि दर्ज करें",
  273: "बुकिंग की अनुमति तभी दें जब ग्राहक प्रदाता कार्य क्षेत्र में स्थित हो",
  274 : "सदस्यता की स्थिति",
  275: "समाप्ति तिथि",
  276: "सदस्यता ली",
  277: "सदस्यता नहीं ली",
  278 : "अभी सदस्यता लें",
  279 : "अपनी सदस्यता बढ़ाएँ",
  280: "",
  281 : "अभी नि:शुल्क परीक्षण शुरू करें",
  282: "प्रारंभ",
  283: "के साथ भुगतान करें",
  284 : "आपकी सदस्यता समाप्त हो गई",
  285: "समाप्त हो गया",
  286: "सदस्यता की पुष्टि करें। क्या आप दो महीने के लिए सदस्यता लेना चाहते हैं",
  287: "नि:शुल्क परीक्षण",
};
