Map<int, String> siteLangEng = {
  0 : "HANDYMAN",
  1 : "View all",
  2 : "Providers",
  3 : "Phone",
  4 : "WWW",
  5 : "Instagram",
  6 : "Provider",
  7 : "Telegram",
  8 : "Monday",
  9 : "Tuesday",
  10 : "Wednesday",
  11 : "Thursday",
  12 : "Friday",
  13 : "Saturday",
  14 : "Sunday",
  15 : "Galleries",
  16 : "Services",
  17 : "Service",
  18 : "Top Services",
  19 : "Blog",
  20 : "Category",
  21 : "fixed",
  22 : "hourly",
  23 : "Addons",
  24 : "Duration",
  25 : "This service can take up to",
  26 : "min",
  27 : "Privacy Policy",
  28 : "About Us",
  29 : "Terms & Conditions",
  30 : "Search service",
  31 : "Search",
  32 : "Welcome, Please Login to continue",
  33 : "Email",
  34 : "Password",
  35 : "Remember me",
  36 : "Sign In",
  37 : "Username or password is incorrect",
  38 : "Permission denied",
  39 : "Forgot password?",
  40 : "Sign Out",
  41 : "or continue with",
  42 : "Reset password",
  43 : "Email",
  44 : "Send new password",
  45 : "Reset password email sent, Please check your mail,",
  46 : "Back to Login",
  47 : "Go back",
  48 : "Don't have account, Register",
  49 : "Register",
  50 : "in less than a minute",
  51 : "Name",
  52 : "Confirm Password",
  53 : "User don't create",
  54 : "Please Enter Email",
  55 : "Please enter password",
  56 : "Passwords are not equal",
  57 : "Email are wrong",
  58 : "Select Address",
  59 : "Verification",
  60 : "Phone number",
  61 : "We'll sent verification code,",
  62 : "CONTINUE",
  63 : "Enter your phone number",
  64 : "Enter code",
  65 : "We've sent 6 digit verification code,",
  66 : "Current address",
  67 : "Other addresses",
  68 : "Address not found",
  69 : "Add address",
  70 : "Find services near your",
  71 : "By allowing location access, you can search for services and providers near your,",
  72 : "Use currents location",
  73 : "Set from map",
  74 : "Latitude",
  75 : "Longitude",
  76 : "Pick here",
  77 : "Please enter address",
  78 : "Add the location",
  79 : "Label as",
  80 : "Home",
  81 : "Delivery Address",
  82 : "Office",
  83 : "Other",
  84 : "Contact name",
  85 : "Contact phone number",
  86 : "Save location",
  87 : "Please Enter name",
  88 : "Please enter phone",
  89 : "Book this service",
  90 : "Your address",
  91 : "Add new",
  92 : "Your address is outside provider work area",
  93 : "See details",
  94 : "Special Requests",
  95 : "Any Time",
  96 : "Schedule an Order",
  97 : "Select a Date & Time",
  98 : "Requested Service on",
  99 : "CLOSE",
  100 : "Please select address",
  101 : "Coupon Code",
  102 : "Coupon not found",
  103 : "Coupon has expired",
  104 : "Coupon not supported by this provider",
  105 : "Coupon not support this category",
  106 : "Coupon not support this service",
  107 : "Coupon activated",
  108 : "Quantity",
  109 : "Pricing",
  110 : "Coupon",
  111 : "no",
  112 : "Tax amount",
  113 : "Total",
  114 : "Requested Service on",
  115 : "Cash payment",
  116 : "CONFIRM & BOOKING NOW",
  117 : "From user:",
  118 : "New Booking was arrived",
  119 : "Thank you!",
  120 : "Your booking has been successfully submitted, you will receive a confirmation soon,",
  121 : "Ok",
  122 : "Please enter valid code",
  123 : "Account",
  124 : "Booking",
  125 : "Profile",
  126 : "Favorites",
  127 : "Notifications",
  128 : "My Address",
  129 : "Notifications not found",
  130 : "SAVE",
  131 : "Data saved",
  132 : "Change password",
  133 : "New password",
  134 : "Confirm New password",
  135 : "CHANGE PASSWORD",
  136 : "Enter Password",
  137 : "Enter Confirm Password",
  138 : "Passwords are not equal",
  139 : "Password changed",
  140 : "Favorites not found",
  141 : "Full address",
  142 : "Please tap on map for select location",
  143 : "Not found ,,,",
  144 : "Any Time",
  145 : "Code sent, Please check your phone for the verification code,",
  146 : "Your phone number verified, You can't edit phone number",
  147 : "Requested on",
  148 : "by administrator",
  149 : "by provider",
  150 : "by customer",
  151 : "Now status:",
  152 : "Booking status was changed",
  153 : "Rate this provider",
  154 : "Id",
  155 : "Back to bookings list",
  156 : "Time creation",
  157 : "Booking ID",
  158 : "Rate this service",
  159 : "Click on the stars to rate this service",
  160 : "Tell us something about this service",
  161 : "Add image",
  162 : "",
  163 : "Submit Review",
  164 : "You can add images",
  165 : "Please enter text",
  166 : "Search on ",
  167 : " or ",
  168 : "Filter",
  169 : "Sort by",
  170 : "Ascending (A-Z)",
  171 : "Descending (Z-A)",
  172 : "Nearby you",
  173 : "Far",
  174 : "Price",
  175 : "Reset Filter",
  176 : "Apply Filter",
  177 : "Payment cancel!",
  178 : "Your booking has been cancelled, you can making booking again,",
  179 : "Login",
  180 : "Current",
  181 : "Subtotal",
  182 : "Discount",
  183 : "Subcategory",
  184 : "Change avatar",
  185 : "Favorite Providers",
  186 : "Not available Now",
  187 : "Related products",
  188 : "See more",
  189 : "Sort by provider",
  190 : "Not select",
  191 : "Search service, provider or product",
  193 : "Products",
  194 : "Add to cart",
  195 : "in stock",
  196 : "Total amount",
  197 : "Please select variant",
  198 : "Product added to cart",
  199 : "This product already in the cart",
  200 : "My Cart",
  201 : "Proceed to checkout",
  202 : "Your cart in empty",
  203 : "Addons:",
  204 : "Quantity",
  205 : "Item price",
  206 : "Other products",
  207 : "Is there anything else",
  208 : "VAT/TAX",
  209 : "Search products",
  210 : "Provider products",
  211 : "Reviews & Ratings",
  212 : "Maximum purchase amount for this provider: ",
  213 : "Minimum purchase amount for this provider: ",
  214 : "Promo code",
  215 : "Remove",
  216 : "Add promo",
  217 : "Promo not found",
  218 : "My rewards",
  219 : "Enter code",
  220 : "Special offer",
  221 : "Use now",
  222 : "Valid until",
  223 : "Coupon not support this product",
  224 : "Apply code",
  225 : "Your promo code",
};

Map<int, String> siteLangDeu = {
  0: "HANDYMAN",
  1 : "Alle anzeigen",
  2: "Anbieter",
  3: "Telefon",
  4: "WWW",
  5: "Instagram",
  6 : "Anbieter",
  7 : "Telegramm",
  8 : "Montag",
  9 : "Dienstag",
  10 : "Mittwoch",
  11 : "Donnerstag",
  12 : "Freitag",
  13 : "Samstag",
  14 : "Sonntag",
  15 : "Galerien",
  16 : "Dienste",
  17 : "Dienstleistung",
  18 : "Top-Services",
  19 : "Blog",
  20 : "Kategorie",
  21 : "fest",
  22 : "stündlich",
  23 : "Add-ons",
  24 : "Dauer",
  25 : "Dieser Dienst kann bis zu dauern",
  26 : "min",
  27 : "Datenschutzerklärung",
  28 : "Über uns",
  29 : "Allgemeine Geschäftsbedingungen",
  30 : "Suchdienst",
  31 : "Suche",
  32 : "Willkommen, Bitte loggen Sie sich ein, um fortzufahren",
  33 : "E-Mail",
  34 : "Passwort",
  35 : "Erinnere dich an mich",
  36 : "Anmelden",
  37 : "Benutzername oder Passwort ist falsch",
  38 : "Erlaubnis verweigert",
  39 : "Passwort vergessen?",
  40 : "Abmelden",
  41 : "oder weiter mit",
  42 : "Passwort zurücksetzen",
  43 : "E-Mail",
  44 : "Neues Passwort senden",
  45 : "E-Mail zum Zurücksetzen des Passworts gesendet, Bitte überprüfen Sie Ihre E-Mail,",
  46 : "Zurück zum Login",
  47 : "Zurück gehen",
  48 : "Kein Konto, Registrieren",
  49 : "Registrieren",
  50 : "in weniger als einer Minute",
  51 : "Name",
  52 : "Passwort bestätigen",
  53 : "Benutzer erstellt nicht",
  54 : "Bitte E-Mail eingeben",
  55 : "Bitte Passwort eingeben",
  56 : "Passwörter sind nicht gleich",
  57 : "E-Mail ist falsch",
  58 : "Adresse auswählen",
  59 : "Verifizierung",
  60 : "Telefonnummer",
  61 : "Wir senden den Bestätigungscode,",
  62 : "WEITER",
  63 : "Geben Sie Ihre Telefonnummer ein",
  64 : "Code eingeben",
  65 : "Wir haben einen 6-stelligen Bestätigungscode gesendet,",
  66 : "Aktuelle Adresse",
  67 : "Andere Adressen",
  68 : "Adresse nicht gefunden",
  69 : "Adresse hinzufügen",
  70 : "Finden Sie Dienste in Ihrer Nähe",
  71 : "Indem Sie den Standortzugriff zulassen, können Sie nach Diensten und Anbietern in Ihrer Nähe suchen,",
  72 : "Stromstandort verwenden",
  73 : "Aus Karte setzen",
  74 : "Breitengrad",
  75 : "Längengrad",
  76 : "Wählen Sie hier",
  77 : "Bitte Adresse eingeben",
  78 : "Ort hinzufügen",
  79 : "Kennzeichnen als",
  80 : "Zuhause",
  81 : "Lieferadresse",
  82 : "Büro",
  83 : "Andere",
  84 : "Kontaktname",
  85 : "Telefonnummer kontaktieren",
  86 : "Standort speichern",
  87 : "Bitte Namen eingeben",
  88 : "Bitte Telefon eingeben",
  89 : "Diesen Service buchen",
  90 : "Ihre Adresse",
  91 : "Neu hinzufügen",
  92 : "Ihre Adresse liegt außerhalb des Arbeitsbereichs des Anbieters",
  93 : "Siehe Details",
  94 : "Sonderwünsche",
  95: "Jederzeit",
  96 : "Bestellung planen",
  97 : "Wählen Sie ein Datum und eine Uhrzeit",
  98 : "Angeforderter Service ein",
  99 : "SCHLIESSEN",
  100 : "Bitte Adresse auswählen",
  101 : "Gutscheincode",
  102 : "Gutschein nicht gefunden",
  103 : "Gutschein ist abgelaufen",
  104 : "Gutschein wird von diesem Anbieter nicht unterstützt",
  105 : "Gutschein unterstützt diese Kategorie nicht",
  106 : "Gutschein unterstützt diesen Dienst nicht",
  107 : "Gutschein aktiviert",
  108 : "Menge",
  109 : "Preise",
  110 : "Gutschein",
  111 : "nein",
  112 : "Steuerbetrag",
  113 : "Gesamt",
  114 : "Angeforderter Service ein",
  115 : "Barzahlung",
  116 : "JETZT BESTÄTIGEN & BUCHEN",
  117 : "Von Benutzer:",
  118 : "Neue Buchung ist eingetroffen",
  119 : "Danke!",
  120 : "Ihre Buchung wurde erfolgreich übermittelt, Sie erhalten in Kürze eine Bestätigung,",
  121 : "Okay",
  122 : "Bitte gültigen Code eingeben",
  123 : "Konto",
  124 : "Buchung",
  125 : "Profil",
  126 : "Favoriten",
  127 : "Benachrichtigungen",
  128 : "Meine Adresse",
  129 : "Benachrichtigungen nicht gefunden",
  130 : "SPEICHERN",
  131 : "Daten gespeichert",
  132 : "Passwort ändern",
  133 : "Neues Passwort",
  134 : "Neues Passwort bestätigen",
  135 : "PASSWORT ÄNDERN",
  136 : "Passwort eingeben",
  137 : "Passwort zur Bestätigung eingeben",
  138 : "Passwörter sind nicht gleich",
  139 : "Passwort geändert",
  140 : "Favoriten nicht gefunden",
  141 : "Vollständige Adresse",
  142 : "Bitte tippen Sie auf die Karte, um den Standort auszuwählen",
  143 : "Nicht gefunden ,,,",
  144 : "Jederzeit",
  145 : "Code gesendet, Bitte überprüfen Sie Ihr Telefon auf den Bestätigungscode,",
  146 : "Ihre Telefonnummer bestätigt, Sie können die Telefonnummer nicht bearbeiten",
  147 : "Angefordert am",
  148 : "vom Administrator",
  149 : "nach Anbieter",
  150 : "vom Kunden",
  151 : "Jetzt Status:",
  152 : "Buchungsstatus wurde geändert",
  153 : "Diesen Anbieter bewerten",
  154 : "Kennung",
  155 : "Zurück zur Buchungsliste",
  156 : "Zeiterstellung",
  157 : "Buchungs-ID",
  158 : "Bewerten Sie diesen Service",
  159 : "Klicken Sie auf die Sterne, um diesen Service zu bewerten",
  160 : "Erzählen Sie uns etwas über diesen Service",
  161 : "Bild hinzufügen",
  162 : "",
  163 : "Bewertung abgeben",
  164 : "Sie können Bilder hinzufügen",
  165 : "Bitte Text eingeben",
  166 : "Suchen auf",
  167 : " oder ",
  168 : "Filter",
  169 : "Sortieren nach",
  170 : "Aufsteigend (A-Z)",
  171 : "Absteigend (Z-A)",
  172 : "In deiner Nähe",
  173 : "Weit",
  174 : "Preis",
  175 : "Filter zurücksetzen",
  176 : "Filter anwenden",
  177 : "Zahlungsabbruch!",
  178 : "Ihre Buchung wurde storniert, Sie können erneut buchen,",
  179 : "Anmelden",
  180 : "Aktuell",
  181 : "Zwischensumme",
  182 : "Rabatt",
  183 : "Unterkategorie",
  184 : "Avatar ändern",
  185 : "Lieblingsanbieter",
  186 : "Jetzt nicht verfügbar",
  187 : "Verwandte Produkte",
  188 : "Mehr sehen",
  189 : "Nach Anbieter sortieren",
  190 : "Nicht auswählen",
  191 : "Suchdienst, Anbieter oder Produkt",
  193 : "Produkte",
  194 : "In den Warenkorb",
  195 : "auf Lager",
  196 : "Gesamtbetrag",
  197 : "Bitte Variante auswählen",
  198 : "Produkt in den Warenkorb gelegt",
  199 : "Dieses Produkt befindet sich bereits im Warenkorb",
  200 : "Mein Warenkorb",
  201 : "Zur Kasse gehen",
  202 : "Ihr Warenkorb ist leer",
  203 : "Addons:",
  204 : "Menge",
  205 : "Artikelpreis",
  206 : "Andere Produkte",
  207 : "Gibt es noch etwas",
  208 : "Mehrwertsteuer/Steuer",
  209 : "Produkte suchen",
  210 : "Anbieterprodukte",
  211 : "Rezensionen & Bewertungen",
  212 : "Maximaler Einkaufsbetrag für diesen Anbieter: ",
  213 : "Mindestkaufbetrag für diesen Anbieter: ",
  214 : "Aktionscode",
  215 : "Entfernen",
  216 : "Angebot hinzufügen",
  217 : "Promo nicht gefunden",
  218 : "Meine Belohnungen",
  219 : "Code eingeben",
  220 : "Sonderangebot",
  221 : "Jetzt verwenden",
  222 : "Gültig bis",
  223 : "Gutschein unterstützt dieses Produkt nicht",
  224 : "Code anwenden",
  225 : "Ihr Promo-Code",
};

Map<int, String> siteLangEsp = {
  0: "HANDYMAN",
  1: "Ver todo",
  2: "Proveedores",
  3: "Teléfono",
  4: "WWW",
  5: "Instagram",
  6: "Proveedor",
  7: "Telegrama",
  8: "Lunes",
  9: "martes",
  10: "miércoles",
  11: "jueves",
  12: "viernes",
  13: "sábado",
  14: "domingo",
  15: "Galerías",
  16: "Servicios",
  17: "Servicio",
  18: "Servicios principales",
  19: "Blog",
  20: "Categoría",
  21: "fijo",
  22: "por hora",
  23: "Complementos",
  24: "Duración",
  25: "Este servicio puede tardar hasta",
  26: "min",
  27: "Política de privacidad",
  28: "Acerca de nosotros",
  29: "Términos y condiciones",
  30: "Servicio de búsqueda",
  31: "Buscar",
  32: "Bienvenido, Inicie sesión para continuar",
  33: "Correo electrónico",
  34: "Contraseña",
  35: "Recuérdame",
  36: "Iniciar sesión",
  37: "El nombre de usuario o la contraseña son incorrectos",
  38: "Permiso denegado",
  39: "¿Olvidaste tu contraseña?",
  40: "Cerrar sesión",
  41: "o continuar con",
  42: "Restablecer contraseña",
  43: "Correo electrónico",
  44: "Enviar nueva contraseña",
  45: "Se envió el correo electrónico para restablecer la contraseña, Por favor revise su correo,",
  46: "Volver al inicio de sesión",
  47: "Regresar",
  48: "No tengo cuenta, Registrarse",
  49: "Registrarse",
  50: "en menos de un minuto",
  51: "Nombre",
  52: "Confirmar contraseña",
  53: "El usuario no crea",
  54: "Introduzca su correo electrónico",
  55: "Introduzca la contraseña",
  56: "Las contraseñas no son iguales",
  57: "El correo electrónico es incorrecto",
  58: "Seleccionar dirección",
  59: "Verificación",
  60: "Número de teléfono",
  61: "Enviaremos el código de verificación",
  62: "CONTINUAR",
  63: "Ingrese su número de teléfono",
  64: "Introducir código",
  65: "Hemos enviado un código de verificación de 6 dígitos",
  66: "Dirección actual",
  67: "Otras direcciones",
  68: "Dirección no encontrada",
  69: "Agregar dirección",
  70: "Encuentra servicios cercanos a tu",
  71: "Al permitir el acceso a la ubicación, puede buscar servicios y proveedores cerca de usted",
  72: "Usar ubicación de corrientes",
  73: "Establecer desde mapa",
  74: "Latitud",
  75: "Longitud",
  76: "Elija aquí",
  77: "Introduzca la dirección",
  78: "Agregar la ubicación",
  79: "Etiquetar como",
  80: "Inicio",
  81: "Dirección de entrega",
  82: "Oficina",
  83: "Otro",
  84: "Nombre de contacto",
  85: "Número de teléfono de contacto",
  86: "Guardar ubicación",
  87: "Introduzca el nombre",
  88: "Por favor ingrese el teléfono",
  89: "Reservar este servicio",
  90: "Tu dirección",
  91: "Agregar nuevo",
  92: "Su dirección está fuera del área de trabajo del proveedor",
  93: "Ver detalles",
  94: "Solicitudes especiales",
  95: "En cualquier momento",
  96: "Programar un pedido",
  97: "Seleccionar fecha y hora",
  98: "Servicio solicitado en",
  99: "CERRAR",
  100: "Seleccione la dirección",
  101: "Código de cupón",
  102: "Cupón no encontrado",
  103: "El cupón ha caducado",
  104: "Cupón no admitido por este proveedor",
  105: "El cupón no es compatible con esta categoría",
  106: "El cupón no es compatible con este servicio",
  107: "Cupón activado",
  108: "Cantidad",
  109: "Precios",
  110: "Cupón",
  111: "no",
  112: "Importe de impuestos",
  113: "Total",
  114: "Servicio solicitado en",
  115: "Pago en efectivo",
  116: "CONFIRMAR Y RESERVAR AHORA",
  117: "Del usuario:",
  118: "Se llegó una nueva reserva",
  119: "¡Gracias!",
  120: "Su reserva se ha enviado correctamente, pronto recibirá una confirmación",
  121: "Ok",
  122: "Introduzca un código válido",
  123: "Cuenta",
  124: "Reserva",
  125: "Perfil",
  126: "Favoritos",
  127: "Notificaciones",
  128: "Mi dirección",
  129: "Notificaciones no encontradas",
  130: "GUARDAR",
  131: "Datos guardados",
  132: "Cambiar contraseña",
  133: "Nueva contraseña",
  134: "Confirmar nueva contraseña",
  135: "CAMBIAR CONTRASEÑA",
  136: "Ingresar contraseña",
  137: "Ingrese Confirmar contraseña",
  138: "Las contraseñas no son iguales",
  139: "Contraseña cambiada",
  140: "Favoritos no encontrados",
  141: "Dirección completa",
  142: "Toque en el mapa para seleccionar la ubicación",
  143: "No encontrado ,,,",
  144: "En cualquier momento",
  145: "Código enviado, Por favor revise su teléfono para el código de verificación,",
  146: "Tu número de teléfono se verificó, No puedes editar el número de teléfono",
  147: "Solicitado el",
  148: "por administrador",
  149: "por proveedor",
  150: "por cliente",
  151: "Ahora estado:",
  152: "Se cambió el estado de la reserva",
  153: "Califica este proveedor",
  154: "Id",
  155: "Volver a la lista de reservas",
  156: "Creación de tiempo",
  157: "ID de reserva",
  158: "Califica este servicio",
  159: "Haga clic en las estrellas para calificar este servicio",
  160: "Cuéntanos algo sobre este servicio",
  161: "Agregar imagen",
  162: "",
  163: "Enviar revisión",
  164: "Puede agregar imágenes",
  165: "Por favor ingrese texto",
  166: "Buscar en",
  167: "o",
  168: "Filtro",
  169: "Ordenar por",
  170: "Ascendente (A-Z)",
  171: "Descendente (Z-A)",
  172: "Cerca de ti",
  173: "Lejos",
  174: "Precio",
  175: "Restablecer filtro",
  176: "Aplicar filtro",
  177: "¡Pago cancelado!",
  178: "Su reserva ha sido cancelada, puede hacer la reserva de nuevo,",
  179: "Iniciar sesión",
  180: "Actual",
  181: "Subtotal",
  182: "Descuento",
  183: "Subcategoría",
  184: "Cambiar avatar",
  185: "Proveedores favoritos",
  186: "No disponible ahora",
  187: "Productos relacionados",
  188: "Ver más",
  189: "Ordenar por proveedor",
  190: "No seleccionar",
  191: "Buscar servicio, proveedor o producto",
  193: "Productos",
  194: "Añadir al carrito",
  195: "en stock",
  196: "Importe total",
  197: "Seleccione la variante",
  198: "Producto añadido al carrito",
  199: "Este producto ya está en el carrito",
  200: "Mi carrito",
  201: "Continuar con el pago",
  202: "Su carrito está vacío",
  203: "Complementos:",
  204: "Cantidad",
  205: "Precio del artículo",
  206: "Otros productos",
  207: "¿Hay algo más?",
  208: "IVA / IMPUESTOS",
  209: "Buscar productos",
  210: "Productos del proveedor",
  211: "Reseñas y calificaciones",
  212: "Monto máximo de compra para este proveedor: ",
  213: "Monto mínimo de compra para este proveedor: ",
  214: "Código de promoción",
  215: "Eliminar",
  216: "Añadir promoción",
  217: "Promoción no encontrada",
  218: "Mis recompensas",
  219: "Ingrese el código",
  220: "Oferta especial",
  221: "Usar ahora",
  222: "Válido hasta",
  223: "El cupón no es compatible con este producto",
  224: "Aplicar código",
  225: "Tu código de promoción",
};

Map<int, String> siteLangFrench = {
  0: "HANDYMAN",
  1 : "Voir tout",
  2 : "Fournisseurs",
  3 : "Téléphone",
  4 : "WWW",
  5 : "Instagram",
  6 : "Fournisseur",
  7 : "Télégramme",
  8 : "Lundi",
  9 : "mardi",
  10 : "mercredi",
  11 : "Jeudi",
  12 : "Vendredi",
  13 : "Samedi",
  14 : "Dimanche",
  15 : "Galeries",
  16 : "Prestations",
  17 : "Service",
  18 : "Les meilleurs services",
  19 : "Blog",
  20 : "Catégorie",
  21 : "fixe",
  22 : "horaire",
  23 : "Ajouts",
  24 : "Durée",
  25 : "Ce service peut prendre jusqu'à",
  26 : "min",
  27 : "Politique de confidentialité",
  28 : "À propos de nous",
  29 : "Conditions Générales",
  30 : "Service de recherche",
  31 : "Rechercher",
  32 : "Bienvenue, Veuillez vous connecter pour continuer",
  33 : "Courriel",
  34 : "Mot de passe",
  35 : "Souviens-toi de moi",
  36 : "Connexion",
  37 : "Le nom d'utilisateur ou le mot de passe est incorrect",
  38 : "Autorisation refusée",
  39 : "Mot de passe oublié ?",
  40 : "Déconnexion",
  41 : "ou continuer avec",
  42 : "Réinitialiser le mot de passe",
  43 : "Courriel",
  44 : "Envoyer nouveau mot de passe",
  45 : "E-mail de réinitialisation du mot de passe envoyé, Veuillez vérifier votre courrier,",
  46 : "Retour à la connexion",
  47 : "Retour",
  48 : "Je n'ai pas de compte, Inscrivez-vous",
  49 : "S'inscrire",
  50 : "en moins d'une minute",
  51 : "Nom",
  52 : "Confirmer le mot de passe",
  53 : "L'utilisateur ne crée pas",
  54 : "Veuillez entrer l'e-mail",
  55 : "Veuillez saisir le mot de passe",
  56 : "Les mots de passe ne sont pas égaux",
  57 : "Les e-mails sont erronés",
  58 : "Sélectionner l'adresse",
  59 : "Vérification",
  60 : "Numéro de téléphone",
  61 : "Nous vous enverrons le code de vérification,",
  62 : "CONTINUER",
  63 : "Entrez votre numéro de téléphone",
  64 : "Entrez le code",
  65 : "Nous avons envoyé un code de vérification à 6 chiffres,",
  66 : "Adresse actuelle",
  67 : "Autres adresses",
  68 : "Adresse non trouvée",
  69 : "Ajouter une adresse",
  70 : "Trouvez des services près de chez vous",
  71 : "En autorisant l'accès à la localisation, vous pouvez rechercher des services et des fournisseurs à proximité de chez vous,",
  72 : "Utiliser la localisation des courants",
  73 : "Définir à partir de la carte",
  74 : "Latitude",
  75 : "Longitude",
  76 : "Choisir ici",
  77 : "Veuillez saisir l'adresse",
  78 : "Ajouter la localisation",
  79 : "Étiqueter comme",
  80 : "Maison",
  81 : "Adresse de livraison",
  82 : "Bureau",
  83 : "Autre",
  84 : "Nom du contact",
  85 : "Numéro de téléphone à contacter",
  86 : "Enregistrer l'emplacement",
  87 : "Veuillez entrer le nom",
  88 : "Veuillez entrer le téléphone",
  89 : "Réservez ce service",
  90 : "Votre adresse",
  91 : "Ajouter nouveau",
  92 : "Votre adresse est en dehors de la zone de travail du prestataire",
  93 : "Voir détails",
  94 : "Demandes spéciales",
  95 : "À tout moment",
  96 : "Planifier une Commande",
  97 : "Sélectionnez une date et une heure",
  98 : "Service demandé le",
  99 : "FERMER",
  100 : "Veuillez sélectionner l'adresse",
  101 : "Code promo",
  102 : "Coupon non trouvé",
  103 : "Le coupon a expiré",
  104 : "Coupon non pris en charge par ce fournisseur",
  105 : "Le coupon ne supporte pas cette catégorie",
  106 : "Le coupon ne supporte pas ce service",
  107 : "Coupon activé",
  108 : "Quantité",
  109 : "Tarification",
  110 : "Coupon",
  111 : "non",
  112 : "Montant de la taxe",
  113 : "Total",
  114 : "Service demandé le",
  115 : "Paiement comptant",
  116 : "CONFIRMER & RÉSERVER MAINTENANT",
  117 : "De l'utilisateur :",
  118 : "Nouvelle réservation arrivée",
  119 : "Merci !",
  120 : "Votre réservation a été soumise avec succès, vous recevrez bientôt une confirmation,",
  121 : "D'accord",
  122 : "Veuillez saisir un code valide",
  123 : "Compte",
  124 : "Réservation",
  125 : "Profil",
  126 : "Favoris",
  127 : "Notifications",
  128 : "Mon Adresse",
  129 : "Notifications non trouvées",
  130 : "ENREGISTRER",
  131 : "Données sauvegardées",
  132 : "Changer le mot de passe",
  133 : "Nouveau mot de passe",
  134 : "Confirmer le nouveau mot de passe",
  135 : "CHANGER MOT DE PASSE",
  136 : "Entrer le mot de passe",
  137 : "Entrer Confirmer Mot de Passe",
  138 : "Les mots de passe ne sont pas égaux",
  139 : "Mot de passe modifié",
  140 : "Favoris non trouvés",
  141 : "Adresse complète",
  142 : "Veuillez appuyer sur la carte pour sélectionner l'emplacement",
  143 : "Non trouvé,,,",
  144 : "À tout moment",
  145 : "Code envoyé, Veuillez vérifier votre téléphone pour le code de vérification,",
  146 : "Votre numéro de téléphone vérifié, Vous ne pouvez pas modifier le numéro de téléphone",
  147 : "Demandé le",
  148 : "par l'administrateur",
  149 : "par fournisseur",
  150 : "par client",
  151 : "Actuellement état :",
  152 : "Le statut de la réservation a été modifié",
  153 : "Évaluez ce fournisseur",
  154 : "Identifiant",
  155 : "Retour à la liste des réservations",
  156 : "Création du temps",
  157 : "Identifiant de réservation",
  158 : "Évaluez ce service",
  159 : "Cliquez sur les étoiles pour noter ce service",
  160 : "Parlez-nous de ce service",
  161 : "Ajouter une image",
  162 : "",
  163 : "Soumettre un avis",
  164 : "Vous pouvez ajouter des images",
  165 : "Veuillez saisir du texte",
  166 : "Rechercher sur ",
  167 : " ou ",
  168 : "Filtre",
  169 : "Trier par",
  170 : "Croissant (A-Z)",
  171 : "Descendant (Z-A)",
  172 : "A proximité",
  173 : "Loin",
  174 : "Prix",
  175 : "Réinitialiser le filtre",
  176 : "Appliquer le filtre",
  177 : "Annuler le paiement !",
  178 : "Votre réservation a été annulée, vous pouvez refaire une réservation,",
  179 : "Connexion",
  180 : "Courant",
  181 : "Sous-total",
  182 : "Réduction",
  183 : "Sous-catégorie",
  184 : "Changer d'avatar",
  185 : "Fournisseurs favoris",
  186 : "Non disponible maintenant",
  187 : "Produits associés",
  188 : "Voir plus",
  189 : "Trier par fournisseur",
  190 : "Ne pas sélectionner",
  191 : "Rechercher un service, un fournisseur ou un produit",
  193 : "Produits",
  194 : "Ajouter au panier",
  195 : "en stock",
  196 : "Montant total",
  197 : "Veuillez sélectionner une variante",
  198 : "Produit ajouté au panier",
  199 : "Ce produit déjà dans le panier",
  200 : "Mon panier",
  201 : "Passer à la caisse",
  202 : "Votre panier à vide",
  203 : "Modules complémentaires:",
  204 : "Quantité",
  205 : "Prix de l'article",
  206 : "Autres produits",
  207 : "Y a-t-il autre chose",
  208 : "TVA/TAXE",
  209 : "Rechercher des produits",
  210 : "Produits prestataires",
  211 : "Avis & Notes",
  212 : "Montant d'achat maximum pour ce fournisseur : ",
  213 : "Montant minimum d'achat pour ce prestataire : ",
  214 : "Code promotionnel",
  215 : "Supprimer",
  216 : "Ajouter une promotion",
  217 : "Promotion introuvable",
  218 : "Mes récompenses",
  219 : "Saisir le code",
  220 : "Offre spéciale",
  221 : "Utiliser maintenant",
  222 : "Valable jusqu'au",
  223 : "Le coupon ne prend pas en charge ce produit",
  224 : "Appliquer le code",
  225 : "Votre code promo",
};

Map<int, String> siteLangArabic = {
  0: "HANDYMAN",
  1: "عرض الكل" ,
  2: "المزودون" ,
  3: "الهاتف" ,
  4: "WWW" ,
  5: "Instagram" ,
  6: "مقدم الخدمة" ,
  7: "Telegram" ,
  8: "الاثنين" ,
  9: "الثلاثاء" ,
  10: "الأربعاء" ,
  11: "الخميس" ,
  12: "الجمعة" ,
  13: "السبت" ,
  14: "الأحد" ,
  15: "المعارض" ,
  16: "الخدمات" ,
  17: "الخدمة" ,
  18: "أفضل الخدمات" ,
  19: "مدونة",
  20: "الفئة" ,
  21: "ثابت" ,
  22: "كل ساعة",
  23: "الإضافات" ,
  24: "المدة" ,
  25: "يمكن أن تستغرق هذه الخدمة ما يصل إلى" ,
  26: "دقيقة",
  27: "سياسة الخصوصية" ,
  28: "نبذة عنا" ,
  29: "الشروط والأحكام" ,
  30: "خدمة البحث" ,
  31: "بحث" ,
  32: "مرحبًا, الرجاء تسجيل الدخول للمتابعة" ,
  33: "البريد الإلكتروني" ,
  34: "كلمة المرور" ,
  35: "تذكرني" ,
  36: "تسجيل الدخول" ,
  37: "اسم المستخدم أو كلمة المرور غير صحيحة" ,
  38: "تم رفض الإذن" ,
  39: "هل نسيت كلمة المرور؟" ,
  40: "تسجيل الخروج" ,
  41: "أو متابعة" ,
  42: "إعادة تعيين كلمة المرور" ,
  43: "البريد الإلكتروني" ,
  44: "إرسال كلمة مرور جديدة" ,
  45: "تم إرسال بريد إلكتروني لإعادة تعيين كلمة المرور, يرجى التحقق من بريدك,",
  46: "العودة إلى تسجيل الدخول" ,
  47: "العودة" ,
  48: "ليس لديك حساب, سجل" ,
  49: "تسجيل" ,
  50: "في أقل من دقيقة" ,
  51: "الاسم" ,
  52: "تأكيد كلمة المرور" ,
  53: "المستخدم لا ينشئ" ,
  54: "الرجاء إدخال البريد الإلكتروني" ,
  55: "الرجاء إدخال كلمة المرور" ,
  56: "كلمات المرور غير متساوية" ,
  57: "البريد الإلكتروني خاطئ" ,
  58: "حدد العنوان" ,
  59: "التحقق" ,
  60: "رقم الهاتف" ,
  61: "سنرسل رمز التحقق," ,
  62: "متابعة" ,
  63: "أدخل رقم هاتفك" ,
  64: "أدخل الرمز" ,
  65: "لقد أرسلنا رمز التحقق المكون من 6 أرقام," ,
  66: "العنوان الحالي" ,
  67: "عناوين أخرى" ,
  68: "لم يتم العثور على العنوان" ,
  69: "إضافة عنوان" ,
  70: "البحث عن خدمات بالقرب منك" ,
  71: "بالسماح بالوصول إلى الموقع , يمكنك البحث عن الخدمات والموفرين بالقرب منك," ,
  72: "استخدام موقع التيارات" ,
  73: "تعيين من الخريطة" ,
  74: "خط العرض" ,
  75: "خط الطول" ,
  76: "اختر هنا" ,
  77: "الرجاء إدخال العنوان" ,
  78: "أضف الموقع" ,
  79: "تسمية كـ" ,
  80: "الصفحة الرئيسية" ,
  81: "عنوان التسليم" ,
  82: "مكتب" ,
  83: "أخرى" ,
  84: "اسم جهة الاتصال" ,
  85: "رقم هاتف الاتصال" ,
  86: "حفظ الموقع" ,
  87: "الرجاء إدخال الاسم" ,
  88: "الرجاء إدخال الهاتف" ,
  89: "احجز هذه الخدمة" ,
  90: "عنوانك" ,
  91: "إضافة جديد" ,
  92: "عنوانك خارج منطقة عمل المزود" ,
  93: "انظر التفاصيل" ,
  94: "الطلبات الخاصة" ,
  95: "في أي وقت" ,
  96: "جدولة طلب" ,
  97: "حدد التاريخ والوقت" ,
  98: "الخدمة المطلوبة في" ,
  99: "إغلاق" ,
  100: "الرجاء تحديد العنوان" ,
  101: "رمز القسيمة" ,
  102: "القسيمة غير موجودة" ,
  103: "القسيمة انتهت صلاحيتها" ,
  104: "قسيمة غير مدعومة من قبل هذا الموفر" ,
  105: "قسيمة لا تدعم هذه الفئة" ,
  106: "قسيمة لا تدعم هذه الخدمة" ,
  107: "القسيمة نشطة" ,
  108: "الكمية" ,
  109: "التسعير" ,
  110: "قسيمة" ,
  111: "لا" ,
  112: "مبلغ الضريبة" ,
  113: "المجموع" ,
  114: "الخدمة المطلوبة في" ,
  115: "الدفع النقدي" ,
  116: "تأكيد وحجز الآن" ,
  117: "من المستخدم:" ,
  118: "وصل حجز جديد" ,
  119: "شكرا لك!" ,
  120: "تم تقديم حجزك بنجاح , ستتلقى تأكيدًا قريبًا,",
  121: "حسنًا" ,
  122: "الرجاء إدخال رمز صالح" ,
  123: "الحساب" ,
  124: "الحجز" ,
  125: "الملف الشخصي" ,
  126: "المفضلة" ,
  127: "الإخطارات" ,
  128: "عنواني" ,
  129: "إخطارات غير موجودة" ,
  130: "حفظ" ,
  131: "البيانات المحفوظة" ,
  132: "تغيير كلمة المرور" ,
  133: "كلمة مرور جديدة" ,
  134: "تأكيد كلمة المرور الجديدة" ,
  135: "تغيير كلمة المرور" ,
  136: "أدخل كلمة المرور" ,
  137: "أدخل تأكيد كلمة المرور" ,
  138: "كلمات المرور ليست متساوية" ,
  139: "تم تغيير كلمة المرور" ,
  140: "لم يتم العثور على المفضلة" ,
  141: "العنوان الكامل" ,
  142: "الرجاء النقر على الخريطة لتحديد الموقع" ,
  143: "غير موجود ,,," ,
  144: "في أي وقت" ,
  145: "تم إرسال الرمز, يرجى التحقق من هاتفك بحثًا عن رمز التحقق,",
  146: "تم التحقق من رقم هاتفك, لا يمكنك تعديل رقم الهاتف" ,
  147: "مطلوب في" ,
  148: "بواسطة المسؤول",
  149: "حسب المزود" ,
  150: "حسب الزبون" ,
  151: "الآن الحالة:" ,
  152: "تم تغيير حالة الحجز" ,
  153: "قيم هذا المزود" ,
  154: "معرف" ,
  155: "رجوع إلى قائمة الحجوزات" ,
  156: "خلق الوقت" ,
  157: "معرف الحجز" ,
  158: "قيم هذه الخدمة" ,
  159: "اضغط على النجوم لتقييم هذه الخدمة" ,
  160: "أخبرنا شيئًا عن هذه الخدمة" ,
  161: "إضافة صورة" ,
  162: "",
  163: "إرسال مراجعة" ,
  164: "يمكنك إضافة الصور" ,
  165: "الرجاء إدخال نص" ,
  166: "البحث في" ,
  167: "أو" ,
  168: "تصفية" ,
  169: "فرز حسب" ,
  170: "تصاعدي (أ-ي)" ,
  171: "تنازلي (ي - أ)" ,
  172: "بالقرب منك" ,
  173: "بعيد" ,
  174: "السعر" ,
  175: "إعادة تعيين عامل التصفية" ,
  176: "تطبيق عامل التصفية" ,
  177: "إلغاء الدفع!" ,
  178: "تم إلغاء حجزك , يمكنك إجراء الحجز مرة أخرى,",
  179: "تسجيل الدخول" ,
  180: "الحالي" ,
  181: "المجموع الفرعي" ,
  182: "خصم" ,
  183: "فئة فرعية",
  184: "تغيير الصورة الرمزية" ,
  185: "المزودون المفضلون" ,
  186: "غير متوفر الآن" ,
  187: "منتجات ذات صلة" ,
  188: "مشاهدة المزيد" ,
  189: "فرز حسب الموفر" ,
  190: "لم تحدد" ,
  191: "البحث عن خدمة أو مزود أو منتج" ,
  193: "المنتجات" ,
  194: "إضافة إلى عربة التسوق" ,
  195: "متوفر",
  196: "المبلغ الإجمالي" ,
  197: "الرجاء تحديد البديل" ,
  198: "تمت إضافة المنتج إلى سلة التسوق" ,
  199: "هذا المنتج موجود بالفعل في سلة التسوق" ,
  200: "عربتي" ,
  201: "تابع الدفع" ,
  202: "سلة التسوق الخاصة بك فارغة" ,
  203: "الإضافات:" ,
  204: "الكمية" ,
  205: "سعر السلعة" ,
  206: "منتجات أخرى" ,
  207: "هل هناك شيء آخر" ,
  208: "ضريبة القيمة المضافة / الضرائب" ,
  209: "البحث عن المنتجات" ,
  210: "منتجات الموفر" ,
  211: "التعليقات والتقييمات" ,
  212: "الحد الأقصى لمبلغ الشراء لهذا الموفر:" ,
  213: "الحد الأدنى لمبلغ الشراء لهذا الموفر:" ,
  214: "الرمز الترويجي" ,
  215: "إزالة" ,
  216: "إضافة عرض ترويجي",
  217: "لم يتم العثور على العرض الترويجي" ,
  218: "مكافآتي" ,
  219: "أدخل الرمز" ,
  220: "عرض خاص" ,
  221: "استخدم الآن" ,
  222: "صالح حتى" ,
  223: "قسيمة لا تدعم هذا المنتج" ,
  224: "تطبيق الرمز" ,
  225: "الرمز الترويجي الخاص بك",
};

Map<int, String> siteLangPort = {
  0: "HANDYMAN",
  1: "Ver tudo",
  2: "Provedores",
  3: "Telefone",
  4: "WWW",
  5: "Instagram",
  6: "Provedor",
  7: "Telegrama",
  8: "segunda-feira",
  9: "terça-feira",
  10: "quarta-feira",
  11: "quinta-feira",
  12: "sexta-feira",
  13: "sábado",
  14: "domingo",
  15: "Galerias",
  16: "Serviços",
  17: "Serviço",
  18: "Principais serviços",
  19: "Blog",
  20: "Categoria",
  21: "fixo",
  22: "de hora em hora",
  23: "Complementos",
  24: "Duração",
  25: "Este serviço pode levar até",
  26: "min",
  27: "Política de privacidade",
  28: "Sobre nós",
  29: "Termos e Condições",
  30: "Serviço de pesquisa",
  31: "Pesquisar",
  32: "Bem-vindo, Faça login para continuar",
  33: "Email",
  34: "Senha",
  35: "Lembre-se de mim",
  36: "Entrar",
  37: "Nome de usuário ou senha incorretos",
  38: "Permissão negada",
  39: "Esqueceu a senha?",
  40: "Sair",
  41: "ou continue com",
  42: "Redefinir senha",
  43: "Email",
  44: "Enviar nova senha",
  45: "Email de redefinição de senha enviado, Verifique seu e-mail,",
  46: "Voltar ao Login",
  47: "Voltar",
  48: "Não tem conta, Cadastre-se",
  49: "Registre-se",
  50: "em menos de um minuto",
  51: "Nome",
  52: "Confirme a senha",
  53: "O usuário não cria",
  54: "Digite o e-mail",
  55: "Digite a senha",
  56: "As senhas não são iguais",
  57: "Email está errado",
  58: "Selecionar Endereço",
  59: "Verificação",
  60: "Número de telefone",
  61: "Enviaremos o código de verificação,",
  62: "CONTINUAR",
  63: "Insira o seu número de telefone",
  64: "Insira o código",
  65: "Enviamos um código de verificação de 6 dígitos,",
  66: "Endereço atual",
  67: "Outros endereços",
  68: "Endereço não encontrado",
  69: "Adicionar endereço",
  70: "Encontre serviços perto de",
  71: "Ao permitir o acesso à localização, você pode pesquisar serviços e provedores próximos ao seu,",
  72: "Usar localização de correntes",
  73: "Definir do mapa",
  74: "Latitude",
  75: "Longitude",
  76: "Escolha aqui",
  77: "Por favor, insira o endereço",
  78: "Adicionar o local",
  79: "Marcar como",
  80: "Casa",
  81: "Endereço de entrega",
  82: "Escritório",
  83: "Outro",
  84: "Nome do contato",
  85: "Número de telefone do contato",
  86: "Salvar local",
  87: "Insira o nome",
  88: "Por favor, insira o telefone",
  89: "Reserve este serviço",
  90: "Seu endereço",
  91: "Adicionar novo",
  92: "Seu endereço está fora da área de trabalho do provedor",
  93: "Ver detalhes",
  94: "Pedidos Especiais",
  95: "Qualquer hora",
  96: "Agendar um pedido",
  97: "Selecione uma data e hora",
  98: "Serviço Solicitado em",
  99: "FECHAR",
  100: "Selecione o endereço",
  101: "Código do cupom",
  102: "Cupom não encontrado",
  103: "O cupom expirou",
  104: "Cupom não suportado por este provedor",
  105: "O cupom não é compatível com esta categoria",
  106: "O cupom não é compatível com este serviço",
  107: "Cupom ativado",
  108: "Quantidade",
  109: "Preços",
  110: "Cupom",
  111: "não",
  112: "Valor do imposto",
  113: "Total",
  114: "Serviço Solicitado em",
  115: "Pagamento em dinheiro",
  116: "CONFIRMAR E RESERVAR AGORA",
  117: "Do usuário:",
  118: "Nova reserva foi recebida",
  119: "Obrigado!",
  120: "Sua reserva foi enviada com sucesso, você receberá uma confirmação em breve,",
  121: "Ok",
  122: "Por favor, insira um código válido",
  123: "Conta",
  124: "Reserva",
  125: "Perfil",
  126: "Favoritos",
  127: "Notificações",
  128: "Meu endereço",
  129: "Notificações não encontradas",
  130: "SALVAR",
  131: "Dados salvos",
  132: "Alterar senha",
  133: "Nova senha",
  134: "Confirmar nova senha",
  135: "ALTERAR SENHA",
  136: "Digite a senha",
  137: "Digite a senha de confirmação",
  138: "As senhas não são iguais",
  139: "Senha alterada",
  140: "Favoritos não encontrados",
  141: "Endereço completo",
  142: "Por favor, toque no mapa para selecionar o local",
  143: "Não encontrado ,,,",
  144: "Qualquer hora",
  145: "Código enviado, Verifique o código de verificação em seu telefone,",
  146: "Seu número de telefone verificado, Você não pode editar o número de telefone",
  147: "Solicitado em",
  148: "pelo administrador",
  149: "por provedor",
  150: "por cliente",
  151: "Status agora:",
  152: "O status da reserva foi alterado",
  153: "Avalie este provedor",
  154: "Id",
  155: "Voltar para a lista de reservas",
  156: "Criação de tempo",
  157: "ID de reserva",
  158: "Avalie este serviço",
  159: "Clique nas estrelas para avaliar este serviço",
  160: "Conte-nos algo sobre este serviço",
  161: "Adicionar imagem",
  162: "",
  163: "Enviar avaliação",
  164: "Você pode adicionar imagens",
  165: "Por favor, insira o texto",
  166: "Pesquisar em",
  167: "ou",
  168: "Filtro",
  169: "Classificar por",
  170: "Ascendente (A-Z)",
  171: "Descendente (Z-A)",
  172: "Perto de você",
  173: "Longe",
  174: "Preço",
  175: "Reiniciar Filtro",
  176: "Aplicar filtro",
  177: "Cancelamento de pagamento!",
  178: "Sua reserva foi cancelada, você pode fazer a reserva novamente,",
  179: "Login",
  180: "Atual",
  181: "Subtotal",
  182: "Desconto",
  183: "Subcategoria",
  184: "Alterar avatar",
  185: "Provedores favoritos",
  186: "Não disponível agora",
  187: "Produtos relacionados",
  188: "Veja mais",
  189: "Classificar por provedor",
  190: "Não selecionar",
  191: "Pesquisar serviço, fornecedor ou produto",
  193: "Produtos",
  194: "Adicionar ao carrinho",
  195: "em estoque",
  196: "Montante total",
  197: "Selecione a variante",
  198: "Produto adicionado ao carrinho",
  199: "Este produto já está no carrinho",
  200: "Meu carrinho",
  201: "Prossiga para a finalização da compra",
  202: "Seu carrinho está vazio",
  203: "Complementos:",
  204: "Quantidade",
  205: "Preço do item",
  206: "Outros produtos",
  207: "Há mais alguma coisa",
  208: "VAT / TAX",
  209: "Pesquisar produtos",
  210: "Produtos do fornecedor",
  211: "Críticas e avaliações",
  212 : "Valor máximo de compra para este provedor: ",
  213 : "Valor mínimo de compra para este provedor: ",
  214 : "Código promocional",
  215 : "Remover",
  216 : "Adicionar promoção",
  217 : "Promoção não encontrada",
  218 : "Minhas recompensas",
  219 : "Digite o código",
  220 : "Oferta especial",
  221 : "Usar agora",
  222 : "Válido até",
  223 : "Cupom não compatível com este produto",
  224 : "Aplicar código",
  225 : "Seu código promocional",
};

Map<int, String> siteLangRus = {
  0: "HANDYMAN",
1: "Посмотреть все",
2: "Провайдеры",
3: "Телефон",
4: "WWW",
5: "Инстаграм",
6: "Провайдер",
7: "Telegram",
8: "Понедельник",
9: "Вторник",
10: "Среда",
11: "Четверг",
12: "Пятница",
13: "Суббота",
14: "Воскресенье",
15: "Галереи",
16: "Услуги",
17: "Сервис",
18: "Лучшие услуги",
19: "Блог",
20: "Категория",
21: "фиксированный",
22: "ежечасно",
23: "Дополнения",
24: "Продолжительность",
25: "Эта услуга может занять до",
26: "мин",
27: "Политика конфиденциальности",
28: "О нас",
29: "Положения и условия",
30: "Служба поиска",
31: "Поиск",
32: "Добро пожаловать, Пожалуйста, войдите, чтобы продолжить",
33: "Электронная почта",
34: "Пароль",
35: "Помни меня",
36: "Войти",
37: "Неверное имя пользователя или пароль",
38: "В разрешении отказано",
39: "Забыли пароль?",
40: "Выйти",
41: "или продолжить с",
42: "Сбросить пароль",
43: "Электронная почта",
44: "Отправить новый пароль",
45: "Сообщение для сброса пароля отправлено, Пожалуйста, проверьте свою почту,",
46: "Вернуться к входу в систему",
47: "Назад",
48: "Нет аккаунта, Зарегистрируйся",
49: "Регистр",
50: "менее чем за минуту",
51: "Имя",
52: "Подтвердите пароль",
53: "Пользователь не создает",
54: "Пожалуйста, введите адрес электронной почты",
55: "Пожалуйста, введите пароль",
56: "Пароли не равны",
57: "Неправильный адрес электронной почты",
58: "Выбрать адрес",
59: "Проверка",
60: "Номер телефона",
61: "Мы отправим проверочный код,",
62: "ПРОДОЛЖИТЬ",
63: "Введите свой номер телефона",
64: "Введите код",
65: "Мы отправили 6-значный проверочный код,",
66: "Текущий адрес",
67: "Прочие адреса",
68: "Адрес не найден",
69: "Добавить адрес",
70: "Найдите услуги рядом с вашим",
71: "Разрешив доступ к местоположению, вы можете искать услуги и поставщиков рядом с вашим,",
72: "Использование токов локации",
73: "Установить по карте",
74: "Широта",
75: "Долгота",
76: "Выбери здесь",
77: "Пожалуйста, введите адрес",
78: "Добавить местоположение",
79: "Отметить как",
80: "Дом",
81: "Адрес доставки",
82: "Офис",
83: "Другое",
84: "Контактное лицо",
85: "Контактный телефон",
86: "Сохранить местоположение",
87: "Пожалуйста, введите имя",
88: "Пожалуйста, введите телефон",
89: "Заказать эту услугу",
90: "Ваш адрес",
91: "Добавить новый",
92: "Ваш адрес находится за пределами рабочей зоны провайдера",
93: "Подробнее",
94: "Особые запросы",
95: "В любое время",
96: "Запланировать заказ",
97: "Выберите дату и время",
98: "Запрошенная услуга включена",
99: "ЗАКРЫТЬ",
100: "Пожалуйста, выберите адрес",
101: "Код купона",
102: "Купон не найден",
103: "Срок действия купона истек",
104: "Купон не поддерживается этим поставщиком",
105: "Купон не поддерживает эту категорию",
106: "Купон не поддерживает эту услугу",
107: "Купон активирован",
108: "Количество",
109: "Цены",
110: "Купон",
111: "нет",
112: "Сумма налога",
113: "Итого",
114: "Запрошенная услуга включена",
115: "Наличный расчет",
116: "ПОДТВЕРДИТЬ И БРОНИРОВАТЬ СЕЙЧАС",
117: "От пользователя:",
118: "Поступило новое бронирование",
119: "Спасибо!",
120: "Ваше бронирование было успешно отправлено, вскоре вы получите подтверждение,",
121: "Хорошо",
122: "Пожалуйста, введите действительный код",
123: "Учетная запись",
124: "Бронирование",
125: "Профиль",
126: "Избранное",
127: "Уведомления",
128: "Мой адрес",
129: "Уведомления не найдены",
130: "СОХРАНИТЬ",
131: "Данные сохранены",
132: "Сменить пароль",
133: "Новый пароль",
134: "Подтвердите новый пароль",
135: "ИЗМЕНИТЬ ПАРОЛЬ",
136: "Введите пароль",
137: "Введите пароль для подтверждения",
138: "Пароли не равны",
139: "Пароль изменен",
140: "Избранное не найдено",
141: "Полный адрес",
142: "Нажмите на карту, чтобы выбрать место",
143: "Не найдено ,,,",
144: "В любое время",
145: "Код отправлен, Проверьте свой телефон на наличие кода подтверждения,",
146: "Ваш номер телефона подтвержден, Вы не можете редактировать номер телефона",
147: "Запрошено",
148: "администратором",
149: "по провайдеру",
150: "по заказчику",
151: "Сейчас статус:",
152: "Статус бронирования изменен",
153: "Оцените этого провайдера",
154: "Идентификатор",
155: "Вернуться к списку бронирований",
156: "Время творения",
157: "Идентификатор бронирования",
158: "Оцените эту услугу",
159: "Нажмите на звездочки, чтобы оценить эту услугу",
160: "Расскажите что-нибудь об этой услуге",
161: "Добавить изображение",
162: "",
163: "Отправить обзор",
164: "Вы можете добавлять изображения",
165: "Пожалуйста, введите текст",
166: "Искать",
167: "или",
168: "Фильтр",
169: "Сортировать по",
170: "По возрастанию (A – Z)",
171: "По убыванию (Z-A)",
172: "Рядом с вами",
173: "Далеко",
174: "Цена",
175: "Сбросить фильтр",
176: "Применить фильтр",
177: "Платеж отменить!",
178: "Ваше бронирование было отменено, вы можете сделать заказ снова,",
179: "Вход",
180: "Текущий",
  181: "Итого",
  182: "Скидка",
  183: "Подкатегория",
  184: "Сменить аватар",
  185: "Любимые провайдеры",
  186: "Сейчас недоступно",
187: "Сопутствующие товары",
188: "Узнать больше",
189: "Сортировать по провайдеру",
190: "Не выбрать",
191: "Служба поиска, поставщик или продукт",
193: "Продукция",
194: "В корзину",
195: "в наличии",
196: "Общая сумма",
197: "Выберите вариант",
198: "Товар добавлен в корзину",
199: "Товар уже в корзине",
200: "Моя корзина",
201: "Перейти к оформлению заказа",
202: "Ваша корзина пуста",
203: "Дополнения:",
204: "Количество",
205: "Цена лота",
206: "Прочие товары",
207: "Есть еще что-нибудь",
208: "НДС / НАЛОГ",
209: "Поиск товаров",
210: "Продукты поставщика",
211: "Обзоры и оценки",
  212 : "Максимальная сумма покупки для этого провайдера: ",
  213 : "Минимальная сумма покупки для этого провайдера: ",
  214 : "Промокод",
  215 : "Удалить",
  216 : "Добавить промо",
  217 : "Промо не найдено",
  218: "Мои награды",
  219 : "Введите код",
  220 : "Специальное предложение",
  221: "Использовать сейчас",
  222 : "Действителен до",
  223 : "Купон не поддерживает этот продукт",
  224 : "Применить код",
  225 : "Ваш промокод",
};

Map<int, String> siteLangHindi = {
  0: "HANDYMAN",
  1: "सभी देखें",
  2: "प्रदाता",
  3: "फोन",
  4: "डब्ल्यूडब्ल्यूडब्ल्यू",
  5: "इंस्टाग्राम",
  6: "प्रदाता",
  7: "टेलीग्राम",
  8: "सोमवार",
  9: "मंगलवार",
  10: "बुधवार",
  11: "गुरुवार",
  12: "शुक्रवार",
  13: "शनिवार",
  14: "रविवार",
  15: "दीर्घाएँ",
  16: "सेवाएं",
  17: "सेवा",
  18: "शीर्ष सेवाएं",
  19: "ब्लॉग",
  20: "श्रेणी",
  21: "निश्चित",
  22: "प्रति घंटा",
  23 : "एडॉन्स",
  24: "अवधि",
  25 : "इस सेवा में अधिक समय लग सकता है",
  26: "मिनट",
  27: "गोपनीयता नीति",
  28: "हमारे बारे में",
  29: "नियम और शर्तें",
  30: "खोज सेवा",
  31: "खोज",
  32: "स्वागत है। जारी रखने के लिए कृपया लॉगिन करें",
  33: "ईमेल",
  34: "पासवर्ड",
  35: "मुझे याद करो",
  36: "साइन इन करें",
  37: "उपयोगकर्ता नाम या पासवर्ड गलत है",
  38: "अनुमति अस्वीकृत",
  39 : "पासवर्ड भूल गए?",
  40: "साइन आउट",
  41: "या जारी रखें",
  42: "पासवर्ड रीसेट करें",
  43: "ईमेल",
  44: "नया पासवर्ड भेजें",
  45 : "रीसेट पासवर्ड ईमेल भेजा गया। कृपया अपना मेल जांचें।",
  46: "लॉगिन पर वापस",
  47: "वापस जाओ",
  48: "खाता नहीं है। रजिस्टर करें",
  49: "रजिस्टर",
  50: "एक मिनट से भी कम समय में",
  51: "नाम",
  52: "पासवर्ड की पुष्टि करें",
  53: "उपयोगकर्ता नहीं बनाते",
  54: "कृपया ईमेल दर्ज करें",
  55: "कृपया पासवर्ड दर्ज करें",
  56: "पासवर्ड समान नहीं हैं",
  57: "ईमेल गलत हैं",
  58: "पता चुनें",
  59: "सत्यापन",
  60: "फोन नंबर",
  61 : "हम सत्यापन कोड भेजेंगे।",
  62: "जारी रखें",
  63: "अपना फोन नंबर दर्ज करें",
  64: "कोड दर्ज करें",
  65 : "हमने 6 अंकों का सत्यापन कोड भेजा है।",
  66: "वर्तमान पता",
  67: "अन्य पते",
  68: "पता नहीं मिला",
  69: "पता जोड़ें",
  70 : "अपने आस-पास की सेवाओं का पता लगाएं",
  71 : "लोकेशन एक्सेस की अनुमति देकर, आप अपने आस-पास की सेवाओं और प्रदाताओं की खोज कर सकते हैं।",
  72: "करंट लोकेशन का उपयोग करें",
  73 : "मानचित्र से सेट करें",
  74: "अक्षांश",
  75: "देशांतर",
  76: "यहाँ उठाओ",
  77: "कृपया पता दर्ज करें",
  78: "स्थान जोड़ें",
  79: "लेबल के रूप में",
  80: "होम",
  81: "डिलीवरी पता",
  82: "कार्यालय",
  83: "अन्य",
  84: "संपर्क नाम",
  85: "फोन नंबर से संपर्क करें",
  86: "स्थान सहेजें",
  87: "कृपया नाम दर्ज करें",
  88: "कृपया फोन दर्ज करें",
  89 : "इस सेवा को बुक करें",
  90: "आपका पता",
  91 : "नया जोड़ें",
  92 : "आपका पता प्रदाता कार्य क्षेत्र के बाहर है",
  93: "विवरण देखें",
  94: "विशेष अनुरोध",
  95: "किसी भी समय",
  96: "एक आदेश निर्धारित करें",
  97 : "एक तिथि और समय चुनें",
  98: "अनुरोधित सेवा चालू",
  99: "बंद करें",
  100: "कृपया पता चुनें",
  101: "कूपन कोड",
  102: "कूपन नहीं मिला",
  103 : "कूपन समाप्त हो गया है",
  104 : "कूपन इस प्रदाता द्वारा समर्थित नहीं है",
  105 : "कूपन इस श्रेणी का समर्थन नहीं करता",
  106 : "कूपन इस सेवा का समर्थन नहीं करता",
  107 : "कूपन सक्रिय",
  108: "मात्रा",
  109 : "मूल्य निर्धारण",
  110: "कूपन",
  111: "नहीं",
  112: "कर राशि",
  113 : "कुल",
  114: "अनुरोधित सेवा चालू",
  115: "नकद भुगतान",
  116 : "अभी पुष्टि करें और बुकिंग करें",
  117: "उपयोगकर्ता से:",
  118 : "नई बुकिंग आ गई",
  119: "धन्यवाद!",
  120 : "आपकी बुकिंग सफलतापूर्वक सबमिट कर दी गई है, आपको जल्द ही एक पुष्टिकरण प्राप्त होगा।",
  121: "ठीक है",
  122 : "कृपया वैध कोड दर्ज करें",
  123: "खाता",
  124 : "बुकिंग",
  125: "प्रोफाइल",
  126: "पसंदीदा",
  127: "सूचनाएं",
  128: "मेरा पता",
  129: "सूचना नहीं मिली",
  130: "बचाओ",
  131 : "डेटा सहेजा गया",
  132 : "पासवर्ड बदलें",
  133: "नया पासवर्ड",
  134 : "नए पासवर्ड की पुष्टि करें",
  135: "पासवर्ड बदलें",
  136 : "पासवर्ड दर्ज करें",
  137: "पासवर्ड की पुष्टि करें दर्ज करें",
  138: "पासवर्ड समान नहीं हैं",
  139: "पासवर्ड बदल गया",
  140: "पसंदीदा नहीं मिला",
  141 : "पूरा पता",
  142 : "कृपया चयनित स्थान के लिए मानचित्र पर टैप करें",
  143: "नहीं मिला ,,,",
  144: "किसी भी समय",
  145 : "कोड भेजा गया। कृपया सत्यापन कोड के लिए अपने फोन की जांच करें।",
  146 : "आपका फ़ोन नंबर सत्यापित है। आप फ़ोन नंबर संपादित नहीं कर सकते",
  147: "अनुरोध किया गया",
  148: "व्यवस्थापक द्वारा",
  149: "प्रदाता द्वारा",
  150: "ग्राहक द्वारा",
  151: "अब स्थिति:",
  152 : "बुकिंग की स्थिति बदली गई",
  153 : "इस प्रदाता को रेट करें",
  154: "आईडी",
  155 : "बुकिंग सूची पर वापस",
  156: "समय निर्माण",
  157: "बुकिंग आईडी",
  158 : "इस सेवा को रेट करें",
  159 : "इस सेवा को रेट करने के लिए सितारों पर क्लिक करें",
  160 : "हमें इस सेवा के बारे में कुछ बताएं",
  161: "छवि जोड़ें",
  162: "",
  163: "समीक्षा सबमिट करें",
  164 : "आप चित्र जोड़ सकते हैं",
  165: "कृपया टेक्स्ट दर्ज करें",
  166: "खोजें",
  167: "या",
  168: "फ़िल्टर",
  169: "क्रमबद्ध करें",
  170: "आरोही (ए-जेड)",
  171: "अवरोही (जेड-ए)",
  172: "आपके आस-पास",
  173: "सुदूर",
  174 : "कीमत",
  175 : "फ़िल्टर रीसेट करें",
  176: "फ़िल्टर लागू करें",
  177: "भुगतान रद्द!",
  178: "आपकी बुकिंग रद्द कर दी गई है, आप फिर से बुकिंग कर सकते हैं।",
  179: "लॉगिन",
  180: "वर्तमान",
  181 : "सबटोटल",
  182: "छूट",
  183 : "उपश्रेणी",
  184 : "अवतार बदलें",
  185 : "पसंदीदा प्रदाता",
  186 : "अभी उपलब्ध नहीं है",
  187: "संबंधित उत्पाद",
  188 : "और देखें",
  189 : "प्रदाता द्वारा क्रमबद्ध करें",
  190 : "नहीं चुनें",
  191: "सेवा, प्रदाता या उत्पाद खोजें",
  193 : "उत्पाद",
  194 : "कार्ट में जोड़ें",
  195: "स्टॉक में",
  196: "कुल राशि",
  197: "कृपया प्रकार चुनें",
  198: "कार्ट में जोड़ा गया उत्पाद",
  199 : "यह उत्पाद पहले से ही कार्ट में है",
  200: "माई कार्ट",
  201 : "चेकआउट के लिए आगे बढ़ें",
  202: "आपकी गाड़ी खाली है",
  203 : "एडॉन्स:",
  204: "मात्रा",
  205 : "आइटम की कीमत",
  206: "अन्य उत्पाद",
  207: "क्या कुछ और है",
  208: "वैट/टैक्स",
  209: "उत्पाद खोजें",
  210 : "प्रदाता उत्पाद",
  211 : "समीक्षा और रेटिंग",
  212 : "इस प्रदाता के लिए अधिकतम खरीद राशि:",
  213 : "इस प्रदाता के लिए न्यूनतम खरीद राशि:",
  214: "प्रोमो कोड",
  215: "निकालें",
  216 : "प्रोमो जोड़ें",
  217: "प्रोमो नहीं मिला",
  218: "मेरे पुरस्कार",
  219: "कोड दर्ज करें",
  220 : "विशेष पेशकश",
  221 : "अभी उपयोग करें",
  222: "जब तक वैध",
  223 : "कूपन इस उत्पाद का समर्थन नहीं करता",
  224: "कोड लागू करें",
  225 : "आपका प्रोमो कोड",
};