import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../main.dart';

Lang strings = Lang();

class Lang {

  var direction = TextDirection.ltr;
  var locale = "en";

  Map<int, String> langEng = {
    0 : "HANDYMAN",
    1 : "SERVICE",
    2 : "SUBMIT",
    3 : "Language",
    4 : "Preferred Language",
    5 : "Select Preferred Language",
    6 : "Home",
    7 : "Chat",
    8 : "Booking",
    9 : "Account",
    10 : "Change Language",
    11 : "Set your Preferred language",
    12 : "Enable Dark Mode",
    13 : "Set you favorite mode",
    14 : "Privacy Policy",
    15 : "Known our Privacy Policy",
    16 : "Press for view profile",
    17 : "Log Out",
    18 : "End the session",
    19 : "Notifications",
    20 : "Lots of important information",
    21 : "Name",
    22 : "Enter your name",
    23 : "Email",
    24 : "Enter your Email",
    25 : "Phone number",
    26 : "Enter your Phone number",
    27 : "Address",
    28 : "Enter address for customers",
    29 : "Description",
    30 : "Enter Short description about you",
    31 : "SAVE",
    32 : "Change password",
    33 : "New password",
    34 : "Enter Password",
    35 : "Confirm New password",
    36 : "Enter Password",
    37 : "CHANGE PASSWORD",
    38 : "My Profile",
    39 : "Everything about you",
    40 : "reviews",
    41 : "Read all",
    42 : "Average Ratings",
    43 : "Sign in now",
    44 : "Password",
    45 : "Enter your Password",
    46 : "CONTINUE",
    47 : "REGISTER",
    48 : "or continue with",
    49 : "Register",
    50 : "in less than a minute",
    51 : "Confirm Password",
    52 : "Verification",
    53 : "We'll sent verification code.",
    54 : "We've sent 6 digit verification code.",
    55 : "Enter code",
    56 : "Enter 6 digits code",
    57 : "Write your message ...",
    58 : "New",
    59 : "Accepted",
    60 : "In progress",
    61 : "Completed",
    62 : "Canceled",
    63 : "Booking",
    64 : "Call now",
    65 : "Message",
    66 : "Booking ID",
    67 : "New Request",
    68 : "Booking Accepted",
    69 : "Accepted on",
    70 : "Start a job",
    71 : "Scheduled on",
    72 : "Job Completed",
    73 : "Payment will appear here",
    74 : "Pricing",
    75 : "Quantity",
    76 : "Tax amount",
    77 : "Total",
    78 : "Requested on",
    79 : "Payment",
    80 : "Make payment",
    81 : "Cash payment",
    82 : "Confirm Payment",
    83 : "Review",
    84 : "Leave a Review",
    85 : "Chatting online",
    86 : "Write your review",
    87 : "Tell us something about this service",
    88 : "Click on the stars to rate this service",
    89 : "Submit Review",
    90 : "Add Images",
    91 : "From Gallery",
    92 : "From Camera",
    93 : "Home services",
    94 : "Find what you need",
    95 : "Search service",
    96 : "Notify",
    97 : "Duration",
    98 : "min",
    99 : "This service can take up to",
    100 : "Galleries",
    101 : "Reviews & Ratings",
    102 : "Book This Service",
    103 : "Your address",
    104 : "Add new",
    105 : "Hint",
    106 : "Is there anything else",
    107 : "Coupon Code",
    108 : "Apply",
    109 : "Any Time",
    110 : "Schedule an Order",
    111 : "Requested Service on",
    112 : "Select a Date & Time",
    113 : "CONFIRM & BOOKING NOW",
    114 : "OK",
    115 : "Your booking has been successfully submitted, you will receive a confirmation soon.",
    116 : "Thank you!",
    117 : "Add Address",
    118 : "My Home",
    119 : "Full address",
    120 : "Select address",
    121 : "Pick here",
    122 : "Search",
    123 : "Monday",
    124 : "Tuesday",
    125 : "Wednesday",
    126 : "Thursday",
    127 : "Friday",
    128 : "Saturday",
    129 : "Sunday",
    130 : "fixed",
    131 : "hourly",
    132 : "start from",
    133 : "Please enter address",
    134 : "Please select address",
    135 : "Please Enter Email",
    136 : "Please Enter Password",
    137 : "User not found",
    138 : "User don't create",
    139 : "Email are wrong",
    140 : "Passwords are not equal",
    141 : "Phone number must be ",
    142 : "symbols",
    143 : "Code sent. Please check your phone for the verification code.",
    144 : "Time Out",
    145 : "Today",
    146 : "About Us",
    147 : "Known About Us",
    148 : "Terms & Conditions",
    149 : "Known Terms & Conditions",
    150 : "Not found ...",
    151 : "Enter Confirm Password",
    152 : "Password changed",
    153 : "Please Enter name",
    154 : "Data saved",
    155 : "Provider",
    156 : "Chat message",
    157 : "New Booking was arrived",
    158 : "Now status:",
    159 : "Booking status was changed",
    160 : "From user:",
    161 : "Rate this service",
    162 : "Coupon not found",
    163 : "Coupon activated",
    164 : "Coupon not supported by this provider",
    165 : "Coupon not support this category",
    166 : "Coupon not support this service",
    167 : "Coupon",
    168 : "no",
    169 : "Coupon has expired",
    170 : "Your Favorites",
    171 : "View your favorite services",
    172 : "Top Services",
    173 : "User is disabled. Connect to Administrator for more information.",
    174 : "Blog",
    175 : "View all",
    176 : "Loading ...",
    177 : "Service",
    178 : "Are you sure you want to exit?",
    179 : "No",
    180 : "Exit",
    181 : "Filter",
    182 : "Sort by",
    183 : "Ascending (A-Z)",
    184 : "Descending (Z-A)",
    185 : "Price",
    186 : "Reset Filter",
    187 : "Apply Filter",
    188 : "My Address",
    189 : "Address not found",
    190 : "Home",
    191 : "Office",
    192 : "Other",
    193 : "Set Location",
    194 : "Find services near your",
    195 : "By allowing location access, you can search for services and providers near your.",
    196 : "Use currents location",
    197 : "Set from map",
    198 : "Add the location",
    199 : "Label as",
    200 : "Delivery Address",
    201 : "Enter Delivery Address",
    202 : "Contact name",
    203 : "Enter Contact name",
    204 : "Contact phone number",
    205 : "Enter Contact phone number",
    206 : "Save location",
    207 : "Latitude",
    208 : "Longitude",
    209 : "Please enter phone",
    210 : "by administrator",
    211 : "by provider",
    212 : "by customer",
    213 : "Enter address",
    214 : "Current address",
    215 : "Other addresses",
    216 : "Location",
    217 : "Your address is outside provider work area",
    218 : "See details",
    219 : "Special Requests",
    220 : "Provider Location",
    221 : "Addons",
    222 : "Nearby you",
    223 : "Far",
    224 : "Providers",
    225 : "Please enter valid code",
    226 : "Your phone number verified. You can't edit phone number",
    227 : "Forgot password?",
    228 : "Reset password",
    229 : "Send new password",
    230 : "Reset password email sent. Please check your mail.",
    231 : "Time creation",
    232 : "Booking ID",
    233 : "Please enter text",
    234 : "Please enter code",
    235 : "Subtotal",
    236 : "Discount",
    237 : "Subcategory",
    238 : "Share this app",
    239 : "Services nearby",
    240 : "Open Provider Page",
    241 : "Report ...",
    242 : "Block user",
    243 : "Block",
    244 : "They won't be able to message you. You won't be able to message them. They won't be notified that you blocked them. ",
    245 : "User",
    246 : "Cancel",
    247 : "blocked",
    248 : "Why are you reporting this user?",
    249 : "Your report is anonymous, except if you're reporting an intellectual property infringement. ",
    250 : "Thanks for letting us know",
    251 : "Your feedback is important in helping us keep the community safe. ",
    252 : "Unblock",
    253 : "They be able to message you. You be able to message them. They won't be notified that you unblocked them. ",
    254 : "unblocked",
    255 : "Your Favorite Providers",
    256 : "View your favorite providers",
    257 : "Favorite Providers",
    258 : "Enable Notify",
    259 : "Not available Now",
    260 : "Services",
    261 : "Provider products",
    262 : "Not available Now",
    263 : "Total amount",
    264 : "Add to cart",
    265 : "Please select variant",
    266 : "in stock",
    267 : "Product added to cart",
    268 : "Cart",
    269 : "My Cart",
    270 : "Proceed to checkout",
    271 : "Your cart is empty",
    272 : "Item price",
    273 : "This service already in the cart",
    274 : "This product already in the cart",
    275 : "Service added to cart",
    276 : "VAT/TAX",
    277 : "See more",
    278 : "Products",
    279 : "Search products",
    280 : "Sort by provider",
    281 : "Not select",
    282 : "Related products",
    283 : "Other products",
    284 : "Booking At",
    285 : "Minimum purchase amount for this provider: ",
    286 : "Maximum purchase amount for this provider: ",

    287 : "Pay with",
    288 : "Provider can't enter to customer app. Please use another credentials.",
    289 : "Add promo",
    290 : "Promo not found",
    291 : "My rewards",
    292 : "Enter code",
    293 : "Special offer",
    294 : "Use now",
    295 : "Valid until",
    296 : "Your promo code",
    297 : "Apply code",
    298 : "Coupon not support this product",
    299 : "Promo code",
    300 : "Remove",

  };

  Map<String, dynamic>? defaultLang;

  setLang(Map<String, dynamic> _def, String _locale, BuildContext context, TextDirection _direction){
    defaultLang = _def;
    locale = _locale;
    direction = _direction;
    Provider.of<LanguageChangeNotifierProvider>(context,listen:false).changeLocale(locale);
  }

  String get(int id){
    if (defaultLang == null) {
      return langEng[id] == null ? "" : langEng[id]!;
    }else{
      if (defaultLang![id.toString()] != null)
        return defaultLang![id.toString()];
      return langEng[id] == null ? "" : langEng[id]!;
    }
  }
}

